## Custom Fields [/customFieldDefinitions]

### customFieldDefinitions.list [GET /customFieldDefinitions.list]

Get a list of all the definitions of custom fields.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `74855f4a-2b61-429c-81d8-c79ad3675a76`,`1a68ac98-b41f-4c60-af12-895c43771385` (array[string], optional)
            + context: `contact` (enum[string], optional) - The context of the custom field definition
                + Members
                    + contact
                    + company
                    + deal
                    + project
                    + milestone
                    + product
                    + invoice
                    + subscription
                    + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                    + ticket
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + label
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `label`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `74855f4a-2b61-429c-81d8-c79ad3675a76` (string)
                + context: `contact` (enum[string])
                    + Members
                        + contact
                        + company
                        + deal
                        + project
                        + milestone
                        + product
                        + invoice
                        + subscription
                        + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                        + ticket
                + type (enum[string])
                    + Members
                        + single_line - Single line text
                        + multi_line - Multiline text
                        + single_select - Single selection - has configuration
                        + multi_select - Multiple selection - has configuration
                        + auto_complete - has configuration
                        + date - Date
                        + money - Money
                        + auto_increment - Automatically incrementing field  - has configuration
                        + integer - Integer
                        + number - Number
                        + boolean - Yes/No
                        + email - Email address
                        + telephone - Phone number
                        + url - URL
                        + company - Company
                        + contact - Contact
                        + product - Product
                        + user - User
                + label (string)
                + group (string, nullable)
                + required: `false` (boolean)
                + configuration (object, nullable)
                    + One Of
                        + options: foo, bar (array[string])
                        + start_value: 1 (number)
                + client (object) - The oauth client that is the owner for this custom field definition
                    + type: `client` (string)
                    + id: `37f07aae-b07c-47ee-bb52-cbe81cf105df` (string)
                + readable (enum[string])
                    + Members
                        + by_owning_client
                        + by_all_clients
                + writable (enum[string])
                    + Members
                        + by_owning_client
                        + by_all_clients

### customFieldDefinitions.info [GET /customFieldDefinitions.info]

Get a info about a specific custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `9c64570b-4ec1-4e03-9662-af904f78f7fa` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `57e851e2-3d3b-4523-82f8-fe77df5a5d6c` (string)
            + context: `contact` (enum[string])
                + Members
                    + contact
                    + company
                    + deal
                    + project
                    + milestone
                    + product
                    + invoice
                    + subscription
                    + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                    + ticket
            + type (enum[string])
                + Members
                    + single_line - Single line text
                    + multi_line - Multiline text
                    + single_select - Single selection - has configuration
                    + multi_select - Multiple selection - has configuration
                    + auto_complete - has configuration
                    + date - Date
                    + money - Money
                    + auto_increment - Automatically incrementing field  - has configuration
                    + integer - Integer
                    + number - Number
                    + boolean - Yes/No
                    + email - Email address
                    + telephone - Phone number
                    + url - URL
                    + company - Company
                    + contact - Contact
                    + product - Product
                    + user - User
            + label (string)
            + group (string, nullable)
            + required: `false` (boolean)
            + configuration (object, nullable)
                + One Of
                    + options: foo, bar (array[string])
                    + start_value: 1 (number)
            + client (object) - The oauth client that is the owner for this custom field definition
                + type: `client` (string)
                + id: `079848eb-8d19-4586-a17d-e5d105569db2` (string)
            + readable (enum[string])
                + Members
                    + by_owning_client
                    + by_all_clients
            + writable (enum[string])
                + Members
                    + by_owning_client
                    + by_all_clients

### customFieldDefinitions.add [POST /customFieldDefinitions.add]

Add a custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + context: `contact` (enum[string], required)
            + Members
                + contact
                + company
                + deal
                + project
                + milestone
                + product
                + invoice
                + subscription
                + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                + ticket
        + type (enum[string], required)
            + Members
                + single_line - Single line text
                + multi_line - Multiline text
                + single_select - Single selection - has configuration
                + multi_select - Multiple selection - has configuration
                + auto_complete - has configuration
                + date - Date
                + money - Money
                + auto_increment - Automatically incrementing field  - has configuration
                + integer - Integer
                + number - Number
                + boolean - Yes/No
                + email - Email address
                + telephone - Phone number
                + url - URL
                + company - Company
                + contact - Contact
                + product - Product
                + user - User
        + label (string, required)
        + group (string, optional)
        + required: `false` (boolean, optional)
        + configuration (object, optional)
            + One Of
                + options: foo, bar (array[string])
                + start_value: 1 (number)
        + readable (enum[string], required)
            + Members
                + by_owning_client
                + by_all_clients
        + writable (enum[string], required)
            + Members
                + by_owning_client
                + by_all_clients

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `customFieldDefinition`
            + id: `b9ae9ae9-c22e-4e9f-98f7-01051223dd32` (string)

### customFieldDefinitions.update [POST /customFieldDefinitions.update]

Add a custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `ceca2dc6-b796-430a-80b5-9cda9ce17871` (string, required)
        + label (string, optional)
        + required: `false` (boolean, optional)
        + group (string, optional)
        + configuration (object, optional)
            + One Of
                + options: foo, bar (array[string])
                + start_value: 1 (number)
        + readable (enum[string], optional)
            + Members
                + by_owning_client
                + by_all_clients
        + writable (enum[string], optional)
            + Members
                + by_owning_client
                + by_all_clients

+ Response 204 (application/json;charset=utf-8)

### customFieldDefinitions.delete [POST /customFieldDefinitions.delete]

Delete a custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `83bf6e7e-32aa-4fae-824f-8457c5460b8c` (string, required)

+ Response 204
