## Migrating [/migrate]

WARNING! These endpoints are not guaranteed to stay backwards compatible.
Their only use is to allow older integrations to migrate their data to the new API.

### migrate.id [POST /migrate.id]

Translates an ID from the deprecated API into a new UUID.

+ Request (application/json)

    + Attributes (object)
        + type: `contact` (enum)
            + Members
                + account
                + user
                + department
                + product
                + contact
                + company
                + deal
                + dealPhase
                + project
                + milestone
                + task
                + meeting
                + call
                + ticket
                + invoice
                + creditNote
                + subscription
                + quotation
                + timeTracking
                + customFieldDefinition
        + id: `1` (number)

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + type: `contact` (enum)
                + Members
                    + account
                    + user
                    + department
                    + product
                    + contact
                    + company
                    + deal
                    + dealPhase
                    + project
                    + milestone
                    + todo
                    + event
                    + ticket
                    + invoice
                    + creditNote
                    + subscription
                    + quotation
                    + timeTracking
                    + customField
            + id: `6ad54ec6-ee2d-4500-afe6-0917c1aa7a38` (string)

### migrate.taxRate [POST /migrate.taxRate]

Translates tax rates from the deprecated API into a new UUID tax rate.

+ Request (application/json)

    + Attributes (object)
        + department_id: `6ad54ec6-ee2d-4500-afe6-0917c1aa7a38` (string)
        + tax_rate: `21` (string)

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + type: `taxRate` (string)
            + id: `6ad54ec6-ee2d-4500-afe6-0917c1aa7a38` (string)

### migrate.activityType [POST /migrate.activityType]

Translates "meeting", "call" and "task" into their respective activity type UUID.

+ Request (application/json)

    + Attributes (object)
        + type: `meeting` (enum)
            + Members
                + meeting
                + call
                + task

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + type: `activityType` (string)
            + id: `28f3639d-9b64-44a8-974d-a4df645af6a5` (string)
