## Webhooks [/webhooks]

### webhooks.register [POST /webhooks.register]

Register a new webhook.

+ Request (application/json)

    + Attributes (WebHook)

+ Response 204

### webhooks.list [POST /webhooks.list]

List registered webhooks ordered by URL.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (object)
        + data (array[WebHook])

### webhooks.unregister [POST /webhooks.unregister]

Unregister a webhook.

+ Request (application/json)

    + Attributes (WebHook)

+ Response 204
