## Webhooks [/webhooks]

### webhooks.register [POST /webhooks.register]

Register a new webhook.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + url: `https://example.com` (string, required) - Your webhook URL
        + types (array[enum[string]], required) - Array of event types that should fire the webhook
            + Members
                + company.added
                + company.deleted
                + company.updated
                + contact.added
                + contact.deleted
                + contact.linkedToCompany
                + contact.unlinkedFromCompany
                + contact.updated
                + deal.created
                + deal.deleted
                + deal.lost
                + deal.moved
                + deal.won
                + invoice.booked
                + invoice.deleted
                + invoice.drafted
                + invoice.paymentRegistered
                + invoice.paymentRemoved
                + invoice.sent
                + invoice.updated
                + milestone.created
                + milestone.updated
                + project.created
                + project.deleted
                + project.updated
                + timeTracking.added
                + timeTracking.deleted
                + timeTracking.updated

+ Response 204

### webhooks.list [GET /webhooks.list]

List registered webhooks.

+ Request (application/json;charset=utf-8)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + url: `https://example.org/webhook` (string) - Webhook URL
                + types: company.added, contact.deleted (array[string]) - Event types that fire the webhook
