FORMAT: 1A
HOST: https://api.teamleader.eu

# Teamleader API

#### New API - This is still a BETA version.

Our new API is currently available in beta version for you to test. We invite you to read through the documentation and test the new endpoints. Do you have any feedback? Don’t hesitate to let us know via [api@teamleader.eu](mailto://api@teamleader.eu).
This documentation isn’t final yet and is subject to change prior to our official release, although we will limit this to a minimum.

## AP-What?

An API is an Application Programming Interface. It is used to programmatically interact with Teamleader, integrate with other software tools or add custom functionalities to Teamleader.

Before creating a new integration, make sure to check our existing integrations built by our community in our [Teamleader Marketplace](https://marketplace.teamleader.eu).

## General principles

### Endpoints

Our API consists of HTTP RPC-style methods, in the form of `https://api.teamleader.eu/resource.action`.

We chose this action based approach over the more popular REST, because it enables us to have domain related actions on resources such as `invoices.book`, `timetracking.start` and `timetracking.stop`.

### Requests

All methods must be called using HTTPS. Data is passed as JSON data in a POST request or as GET query parameters.

For more complex actions we recommend using POST requests with JSON:

```
POST https://api.teamleader.eu/invoices.list

{
    "filter": {
        "department_id": "9d4096c3-813f-4bd5-b3c4-4091807b5b74"
    },
    "page": {
        "size": 50,
        "number": 3
    }
}
```

The GET equivalent:

```
GET https://api.teamleader.eu/invoices.list?filter[department_id]=9d4096c3-813f-4bd5-b3c4-4091807b5b74&page[number]=3&page[size]=50&company_id=3250c613-c478-4a43-9640-b97da923eb21
```

### Responses

Both single objects and collections are returned as JSON objects with a top-level `data` property:

```
{
    "data": {
        "id": "f1dfb84c-3c29-4548-9b9b-9090a080742a",
        "first_name": "Erlich",
        "last_name": "Bachman",
        "salutation": "Mr",
        "email": "info@piedpiper.eu"
    }
}
```

Responses may also contain meta data for pagination.

### Errors

Errors are always returned as an array of error objects under an `errors` top level property.

```
{
    "errors": [
        {
            "title": "Bad request"
        }
    ]
}
```

### Status codes

When objects are created, we return a `201` response containing the `id` and `type` of the new resource. When objects are updated or actions are performed, we often return an empty response with a `204` status code.

Common used status codes:

 - `200` - OK
 - `201` - Created, when resources are created
 - `204` - No Content, on resource updates or actions
 - `400` - Bad Request, the request contains invalid data or references non-existing resources
 - `401` - Unauthorized, invalid or missing access token
 - `403` - Forbidden, not allowed to access this resource
 - `404` - Not Found, resource not found
 - `429` - Too Many Requests, your client has reached the API rate limit
 - `500` - Internal Server Error, something went wrong on our end

## OAuth 2

OAuth 2 is an authorization framework that lets your integration request authorization to data in a user's Teamleader account without getting their password.

Before starting you will need to register your integration on our [marketplace](https://marketplace.teamleader.eu). Each integration is assigned a unique `client_id` and `client_secret` which will be used in the OAuth flow. Note that the `client_secret` key should not be shared.

### Authorization

To authenticate users for your integration, redirect the user to the Teamleader authorization page:

`https://app.teamleader.eu/oauth2/authorize`

With the following values as GET parameters:

 - `client_id` - issued when you create your integration
 - `response_type` - must be "code"
 - `state` - unique string to be passed back upon completion (optional)
 - `redirect_uri` - URL to redirect back to after authorization

The user will then be asked to login to Teamleader server and authorize your integration. If the user approves the client they will be redirected to the previously specified `redirect_uri` with a temporary authorization code and the original state parameter if it was provided. If the states don't match, the request may have been created by a third party and you should abort the process.

`https://YOUR_REDIRECT_URI?code=CODE&state=STATE`

If the user denies your request, we will redirect back to the `redirect_uri` with an `error` parameter:

`https://YOUR_REDIRECT_URI?error=access_denied`

With the authorization code that was sent back to your `redirect_uri`, you can request an access token to make API calls. Note that authorization codes can only be exchanged for an access token once and expire 10 minutes after issuance.

`https://app.teamleader.eu/oauth2/access_token`

The following values should be passed as POST parameters:

 - `client_id` - issued when you register your integration
 - `client_secret` - issued when you register your integration
 - `code` - the authorization code
 - `grant_type` - must be "authorization_code"
 - `redirect_uri` - the original submitted redirect URL

Please note that a `content-type` header is **required** for this request. These types are supported:

 - application/x-www-form-urlencoded
 - application/json

You will receive a JSON response containing an `access_token` and `refresh_token`:

```
{
    "token_type": "Bearer",
    "expires_in": 3600,
    "access_token": ACCESS_TOKEN,
    "refresh_token": REFRESH_TOKEN
}
```

Use this access token to make API calls on behalf of the user using the `Authorization` header. Example request:

```
GET https://api.teamleader.eu/contacts.list HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciO...
Accept: application/json;charset=utf-8
```

### Refresh tokens

Access tokens expire shortly (1 hour) after they are issued for security reasons. If your integration needs to communicate with the API beyond the access token's lifespan you will need to request a new access token using the refresh token which was issued with the access token. Note that refresh tokens can only used once to get a new access token and refresh token.

`https://app.teamleader.eu/oauth2/access_token`

The following values should be passed as POST parameters:

 - `client_id` - issued when you register your integration
 - `client_secret` - issued when you register your integration
 - `refresh_token` - the refresh token
 - `grant_type` - must be "refresh_token"

Refresh tokens will continue functioning until the user uninstalls your integration.

### Client side authentication (implicit grant)

Your client secret must remain private and can not be embedded within client side applications such as browser plugins. For these types of applications we have an alternative authentication method called [implicit grant](https://tools.ietf.org/html/rfc6749#section-1.3.2). The implicit grant is a simplified authorization code flow optimized for clients implemented in a browser using a scripting language such as JavaScript. In the implicit flow, instead of issuing the client an authorization code, the client is issued an access token directly.

Similar to the regular authentication flow, users are redirected to the Teamleader authorization page, but with different query parameters:

`https://app.teamleader.eu/oauth2/authorize`

The following values should be passed as GET parameters:

 - `client_id` - issued when you create your integration
 - `response_type` - must be "token" (instead of "code")
 - `state` - unique string to be passed back upon completion (optional)
 - `redirect_uri` - URL to redirect back to after authorization

If the user approves the client, they will be redirected back to the authorization server with the following parameters in the **fragment part of the url**:

 - `token_type` - with the value "Bearer"
 - `expires_in` - the TTL for this access token in seconds
 - `access_token` - the access token
 - `state` - the state parameter sent in the original request

Example url:

`https://YOUR_REDIRECT_URI#token_type=Bearer&expires_in=900&access_token=TOKEN&state=STATE`

Note that this implicit grant does not return refresh tokens, and that our access tokens have a short TTL value. If you opt for this authentication method, you will have to go through the authorization flow every time you want to make API calls on behalf of the user. Keep this in mind while developing client side applications.

### User Identity

To retrieve information about the user who authorized your application (the resource owner), you can call the following endpoint:

`https://api.teamleader.eu/users.me`

# Group General

## Departments [/departments]

Departments are used to split quotations and invoices for different legal entities or within one organisation.

### departments.list [GET /departments.list]

Get a list of departments.

+ Request (application/json)

    + Attributes (object)
        + filter (object)
            + ids: `92296ad0-2d61-4179-b174-9f354ca2157f`,`53635682-c382-4fbf-9fd9-9506ca4fbcdd` (array[string], optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + name
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `67c576e7-7e6f-465d-b6ab-a864f6e5e95b` (string)
                + name: `Human Resources` (string)

### departments.info [GET /departments.info]

Get details for a single department.

+ Request (application/json)

    + Attributes (object)
        + id: `92296ad0-2d61-4179-b174-9f354ca2157f` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data  (object)
            + id: `67c576e7-7e6f-465d-b6ab-a864f6e5e95b` (string)
            + name: `Human Resources` (string)

## Users [/users]

Users are co-workers in a Teamleader account.

### users.me [GET /users.me]

Get the current authenticated user.

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
            + account (object)
                + type: `account` (string)
                + id: `0fc55513-7f68-4865-aba0-de5da9e4e43d` (string)
            + first_name: `John` (string)
            + last_name: `Smith` (string)
            + email: `john@teamleader.eu` (string)
            + telephones (array[Telephone])
            + language: `nl` (string)
            + function: `Sales` (string)
            + time_zone: `Europe/Brussels` (string)

### users.list [GET /users.list]

Get a list of all users.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + name
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
                + account (object)
                    + type: `account` (string)
                    + id: `0fc55513-7f68-4865-aba0-de5da9e4e43d` (string)
                + first_name: `John` (string)
                + last_name: `Smith` (string)
                + email: `john@teamleader.eu` (string)
                + telephones (array[Telephone])
                + language: `nl` (string)
                + function: `Sales` (string)

### users.info [GET /users.info]

Get details for a single user.

+ Request (application/json)

    + Attributes (object)
        + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string, required)

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
            + account (object)
                + type: `account` (string)
                + id: `0fc55513-7f68-4865-aba0-de5da9e4e43d` (string)
            + first_name: `John` (string)
            + last_name: `Smith` (string)
            + email: `john@teamleader.eu` (string)
            + telephones (array[Telephone])
            + language: `nl` (string)
            + function: `Sales` (string)
            + time_zone: `Europe/Brussels` (string)

# Group CRM

## Contacts [/contacts]

Contacts are physical entities who are added to your CRM database.
Contacts might be linked to one or more companies.

### contacts.list [GET /contacts.list]

Get a list of contacts.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + email (object, optional)
                + type: `primary` (enum[string], required)
                    + Members
                         + primary
                + email: `info@piedpiper.eu` (string, required)
            + ids: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
            + term: `James` (string, optional) - Filters on first_name, last_name, email and telephone
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + added_at
                + order (enum[string], optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `added_at`
                    + order: `desc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2a39e420-3ba3-4384-8024-fa702ef99c9f` (string)
                + first_name: `Erlich` (string)
                + last_name: `Bachman` (string)
                + salutation: `Mr` (string)
                + emails (array)
                    + (object)
                        + type: `primary` (enum[string])
                            + Members
                                + primary
                                + invoicing
                        + email: `info@piedpiper.eu` (string)
                + telephones (array[Telephone])
                + website: `https://piedpiper.com` (string)
                + address (Address)
                + gender: `male` (enum[string])
                    + Members
                        + male
                        + female
                + birthdate: `1987-04-25` (string)
                + iban: `BE12123412341234` (string)
                + bic: `BICBANK` (string)
                + language: `en` (string)
                + added_at: `2016-02-04T16:44:33+00:00` (string)
                + updated_at: `2016-02-05T16:44:33+00:00` (string)

### contacts.info [GET /contacts.info]

Get details for a single contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string)
            + first_name: `Erlich` (string)
            + last_name: `Bachman` (string)
            + salutation: `Mr` (string)
            + emails (array)
                + (object)
                    + type: `primary` (enum[string])
                        + Members
                            + primary
                            + invoicing
                    + email: `info@piedpiper.eu` (string)
            + telephones (array[Telephone])
            + website: `https://piedpiper.com` (string)
            + addresses (array)
                + (object)
                    + type: `primary` (enum[string])
                        + Members
                            + primary
                            + invoicing
                            + delivery
                            + visiting
                    + address (Addressee)
            + gender: `male` (enum[string])
                + Members
                    + male
                    + female
            + birthdate: `1987-04-25` (string)
            + iban: `BE12123412341234` (string)
            + bic: `BICBANK` (string)
            + companies (array)
                + (object)
                    + position: `CEO` (string)
                    + decision_maker: true (boolean)
                    + company (object)
                        + type: `company` (string)
                        + id: `40157f9d-1322-4f2e-b245-188efdc52cc2` (string)
            + language: `en` (string)
            + remarks: `First contact at expo` (string)
            + added_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)

### contacts.add [POST /contacts.add]

Add a new contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + first_name: `John` (string, optional)
        + last_name: `Smith` (string, required)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                + email: `info@piedpiper.eu` (string, required)
        + salutation: `Mr` (string, optional)
        + telephones (array[Telephone], optional)
        + website: `http://example.com` (string, optional)
        + addresses (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (Addressee, required) - Primary addresses can not contain an addressee
        + language: `en` (string, optional)
        + gender: `male` (enum[string], optional)
            + Members
                + male
                + female
        + birthdate: `1989-08-19` (string, optional)
        + iban: `BE12123412341234` (string, optional)
        + bic: `BICBANK` (string, optional)
        + remarks: `Met at expo` (string, optional)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `contact` (string)
            + id: `7c1d8672-f502-4333-9ea4-7a45add15115` (string)

### contacts.update [POST /contacts.update]

Update a contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `76c9d03c-ec5c-4b21-9fc6-7ffee488b12d` (string, required)
        + first_name: `John` (string, optional, nullable)
        + last_name: `Smith` (string, optional)
        + salutation: `Mr` (string, optional, nullable)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                + email: `info@piedpiper.eu` (string, required, nullable)
        + telephones (array[Telephone], optional, nullable)
        + website: `http://example.com` (string, optional, nullable)
        + addresses (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (Addressee, required, nullable) - Primary addresses can not contain an addressee
        + language: `en` (string, optional)
        + gender: `male` (enum[string], optional, nullable)
            + Members
                + male
                + female
        + birthdate: `1989-08-19` (string, optional, nullable)
        + iban: `BE12123412341234` (string, optional, nullable)
        + bic: `BICBANK` (string, optional, nullable)
        + remarks: `Met at expo` (string, optional, nullable)

+ Response 204

### contacts.delete [POST /contacts.delete]

Delete a contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4e235f27-0af0-40e5-82f3-d32d0aa9edb3` (string, required)

+ Response 204

### contacts.linkToCompany [POST /contacts.linkToCompany]

Link a contact to a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `75596038-b9c8-4a37-969d-61059e300a28` (string, required)
        + company_id: `4da20f00-0628-4336-b885-aa90e580dd85` (string, required)
        + position: `CEO` (string, optional)
        + decision_maker: true (boolean, optional)

+ Response 204

### contacts.unlinkFromCompany [POST /contacts.unlinkFromCompany]

Unlink a contact from a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `b4b3160a-b55e-4033-bdae-25b6d22949b4` (string, required)
        + company_id: `3f1c8650-4292-4187-bb02-4aa00bbe9632` (string, required)

+ Response 204

## Companies [/companies]

Companies are legal entities, usually linked to a VAT and/or local business number.

### companies.list [GET /companies.list]

Get a list of companies.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + email (object, optional)
                + type: `primary` (enum[string], required)
                    + Members
                         + primary
                + email: `info@piedpiper.eu` (string, required)
            + ids: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
            + term: `Acme` (string, optional) - Filters on name, vat number, emails and telephones
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + added_at
                + order (enum[string], optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `added_at`
                    + order: `desc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `96a38bbf-24ed-4083-8a5c-20db92aa471e` (string)
                + name: `Pied Piper` (string)
                + business_type (object)
                    + type: `businessType` (string)
                    + id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string)
                + vat_number: `BE0899623035` (string)
                + local_business_number: `63326426` (string)
                + emails (array)
                    + (object)
                        + type: `primary` (enum[string])
                            + Members
                                + primary
                                + invoicing
                        + email: `info@piedpiper.eu` (string)
                + telephones (array[CompanyTelephone])
                + website: `https://piedpiper.com` (string)
                + address (Address)
                + iban: `BE12123412341234` (string)
                + bic: `BICBANK` (string)
                + language: `nl` (string)
                + responsible_user (object)
                    + type: `user` (string)
                    + id: `9b99d8f8-183b-4c7b-8354-9b98b47a192e` (string)
                + added_at: `2016-02-04T16:44:33+00:00` (string)
                + updated_at: `2016-02-05T16:44:33+00:00` (string)

### companies.info [GET /companies.info]

Get details for a single company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e8d31ae7-8258-4fcd-9b2d-78f41b0aa5d5` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `e8d31ae7-8258-4fcd-9b2d-78f41b0aa5d5` (string)
            + name: `Pied Piper` (string)
            + business_type (object)
                + type: `businessType` (string)
                + id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string)
            + vat_number: `BE0899623035` (string)
            + local_business_number: `63326426` (string)
            + emails (array)
                + (object)
                    + type: `primary` (enum[string])
                        + Members
                            + primary
                            + invoicing
                    + email: `info@piedpiper.eu` (string)
            + telephones (array[CompanyTelephone])
            + website: `https://piedpiper.com` (string)
            + addresses (array)
                + (object)
                    + type: `primary` (enum[string])
                        + Members
                            + primary
                            + invoicing
                            + delivery
                            + visiting
                    + address (Addressee)
            + iban: `BE12123412341234` (string)
            + bic: `BICBANK` (string)
            + language: `nl` (string)
            + responsible_user (object)
                + type: `user`
                + id: `7ba98a20-5e2b-4b46-81b9-a3364432d4f0` (string)
            + remarks: `First contact at expo` (string)
            + added_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)

### companies.add [POST /companies.add]

Add a new company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + name: `Pied Piper` (string, required)
        + business_type_id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string, optional)
        + vat_number: `BE0899623035` (string, optional)
        + local_business_number: `63326426` (string, optional)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                + email: `info@piedpiper.eu` (string, required)
        + telephones (array[CompanyTelephone], optional)
        + website: `http://example.com` (string, optional)
        + addresses (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (Addressee, required) - Primary addresses can not contain an addressee
        + iban: `BE12 1234 1234 1234` (string)
        + bic: `BICBANK` (string, optional)
        + language: `en` (string, optional)
        + responsible_user_id: `2b12bd5d-d2d9-43ac-8755-36a1e00bd67f` (string, optional)
        + remarks: `Met at expo` (string, optional)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `company` (string)
            + id: `4784189d-610b-4488-b3a5-5f324f752417` (string)

### companies.update [POST /companies.update]

Update a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4784189d-610b-4488-b3a5-5f324f752417` (string, required)
        + name: `Pied Piper` (string, optional)
        + business_type_id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string, optional, nullable)
        + vat_number: `BE0899623035` (string, optional, nullable)
        + local_business_number: `63326426` (string, optional, nullable)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                + email: `info@piedpiper.eu` (string, required)
        + telephones (array[CompanyTelephone], optional)
        + website: `http://example.com` (string, optional)
        + addresses (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (Addressee, required) - Primary addresses can not contain an addressee
        + iban: `BE12 1234 1234 1234` (string, optional, nullable)
        + bic: `BICBANK` (string, optional, nullable)
        + language: `en` (string, optional, nullable)
        + responsible_user_id: `0ea94804-401d-4dbd-a577-c2d60998f798` (string, optional, nullable)
        + remarks: `Met at expo` (string, optional, nullable)

+ Response 204

### companies.delete [POST /companies.delete]

Delete a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `f3d67f3e-b8a9-45e8-99b1-17a3b14de8a6` (string, required)

+ Response 204

### companies.tag [POST /companies.tag]

Add a new or existing tag to a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `cadd94ba-a41e-4eb4-a46e-39a7f6f96070` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204

## Business Types [/businessTypes]

Each country has a specific set of business types or range of legal entities.
You can specify the business type when adding or updating a company.

### businessTypes.list [GET /businessTypes.list]

Get the names of business types (legal structures) a company can have within a certain country, sorted alphabetically.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + country: `BE` (string, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string)
            + name: `VZW/ASBL` (string)
            + country: `BE` (string)

## Deals [/deals]

### deals.list [GET /deals.list]

Get a list of deals.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `3f507137-e599-41d4-8625-0e2adba0be4c`,`ae97f6d3-0bb4-43d3-b13d-f06069d07e98` (array[string], optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + created_at
                + order (enum[string], optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `created_at`
                    + order: `desc`


+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `6e7fe84d-d4b3-4723-abae-9bc082d8f65a` (string)
                + title: `Interesting deal` (string)
                + reference: `2017/2` (string)
                + status: `won` (enum[string])
                    + Members
                        + new
                        + open
                        + won
                        + lost
                + customer (object)
                    + customer (object)
                        + type: `contact`
                        + id: 1 (string)
                    + for_attention_of (object, optional)
                         + name: `Radja Nainggolan` (string)
                         + contact (object)
                             + type: `contact` (string)
                             + id: `456` (string)
                + id: `456` (string)
                + department (object)
                    + type: `department`
                    + id: `33121d39-44e2-426a-92ef-62178edeec8a` (string)
                + estimated_value (Money)
                + estimated_closing_date: `2017-05-09` (string)
                + estimated_probability: `0.5` (number)
                + current_phase (object)
                    + type: `dealPhase`
                    + id: `521a331d-60d1-4920-bde3-ccd01d09f9f1` (string)
                + responsible_user (object)
                    + type: `user`
                    + id: `bac1c91b-bc86-489b-8590-9be9478f62bb` (string)
                + closed_at: `2017-05-09T11:31:30+00:00` (string)
                + lost (object)
                    + notes (string)
                + source (object)
                    + type: `dealSource` (string)
                    + id: `52a4bbb2-d196-48d7-8e43-9ec2f44d06f9` (string)
                + created_at: `2017-05-09T11:25:11+00:00` (string)
                + updated_at: `2017-05-09T11:30:58+00:00` (string)

### deals.info [GET /deals.info]

Get details for a single deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `f6871b06-6513-4750-b5e6-ff3503b5a029` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `f6871b06-6513-4750-b5e6-ff3503b5a029` (string)
            + title: `Interesting deal` (string)
            + reference: `2017/2` (string)
            + status: `won` (enum[string])
                + Members
                    + open
                    + won
                    + lost
            + customer (object)
                + customer (object)
                    + type: `contact`
                    + id: 1 (string)
                + for_attention_of (object, optional)
                     + name: `Radja Nainggolan` (string)
                     + contact (object)
                         + type: `contact` (string)
                         + id: `456` (string)
            + department (object)
                + type: `department`
                + id: `92247818-643e-4f5a-bf87-25cd908e8ad9` (string)
            + estimated_value (Money)
            + estimated_closing_date: `2017-05-09` (string)
            + estimated_probability: `0.5` (number)
            + current_phase (object)
                + type: dealPhase (string)
                + id: `676a6070-f7d3-43a6-bc08-cda0d32c27ab` (string)
            + responsible_user (object)
                + type: user (string)
                + id: `4e81f3c4-7dca-44cb-b126-6158bec392a2` (string)
            + closed_at: `2017-05-09T11:31:30+00:00` (string)
            + lost (object)
                + notes (string)
            + source (object)
                + type: `dealSource` (string)
                + id: `aba0ad66-bf59-49fa-b546-45dcbc5e7e6e` (string)
            + phase_history (array)
                + (object)
                    + phase (object)
                        + type: dealPhase (string)
                        + id: `d5a629f2-7b58-4748-aaca-acf9b6d62404` (string)
                    + started_at: `2017-05-01 12:00:00` (string)
                    + started_by (object)
                        + type: user (string)
                        + id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string)
            + created_at: `2017-05-09T11:25:11+00:00` (string)
            + updated_at: `2017-05-09T11:30:58+00:00` (string)

### deals.create [POST /deals.create]

Create a new deal for a customer.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + customer (object, required)
            + type (enum[string], required)
                + Members
                    + contact
                    + company
            + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
        + title: `Interesting business deal` (string, required)
        + source_id: `b38ebb9b-6e46-4bf4-a1e2-af747d6b64ae` (string, optional)
        + department_id: `6a6343fc-fdd8-4bc0-aa69-3a004c710e87` (string, optional)
        + responsible_user_id: `98b2863e-7b01-4232-82f5-ede1f0b9db22` (string, optional)
        + phase_id: `060687bb-a742-4882-a538-199a5e5feb60` (string, optional)
        + estimated_value (Money, optional)
        + estimated_probability: `0.75` (number, optional)
        + estimated_closing_date: `2017-05-09` (string, optional)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `deal` (string)
            + id: `65a35860-dcca-4850-9fd6-47ff08469e0c` (string)

## Quotations [/quotations]

### quotations.info [GET /quotations.info]

Get a quotation

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string)
            + deal (object)
                + type: `deal` (string)
                + id: `53474a7a-f9b2-4dd4-88a8-40ce773c7a64` (string)
            + grouped_lines (array)
                + (object)
                    + section (object)
                        + title (string)
                    + line_items (array)
                        + (object)
                            + product (object, nullable)
                                + type: `product` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                            + quantity: 3 (number)
                            + description: `An awesome product` (string)
                            + unit_price (object)
                                + Include Money
                                + tax: `excluding` (enum[string])
                                    + Members
                                        + excluding
                            + tax (object)
                                + rate: 0.21 (number)
                            + discount (object, nullable)
                                + type: `percentage` (enum[string])
                                    + Members
                                        + percentage
                                + value: 15.00 (number)

## Tags [/tags]

### tags.list [GET /tags.list]

Get a list of tags.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + tag
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `tag`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + tag: `campaign` (string)

# Group Calendar

## Calendar events [/events]

Calendar events are scheduled events in your calendar.
A calendar event involves a particular activity type: a task, meeting or call.
They can also be linked to one to-do.

### events.list [GET /events.list]

Get a list of calendar events.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + user_id: `5309c8c9-e313-47b0-90ba-6850c3dc3e33` (string, required)
            + activity_type_id: `edd94120-63e2-4b10-80ed-fdfcfaa0a515` (string, optional)
            + ends_after: `2017-01-01T00:00:00+00:00` (string, optional) - Start of the period for which to return events
            + starts_before: `2018-01-01T00:00:00+00:00` (string, optional) - End of the period for which to return events
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field: `starts_at` (enum[string], required)
                    + Members
                        + starts_at
                + order: `asc` (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: starts_at
                    + order: asc

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `6d64488c-75d8-4de9-b140-2555566fa27d` (string)
                + creator (object)
                    + type: `user` (string)
                    + id: `e51d1a0e-452e-4d5d-a2a1-2c8f75dde560` (string)
                + todo (object)
                    + type: `todo` (string)
                    + id: `eb399573-e1ae-4377-bbaf-34358eb19831` (string)
                + activity_type (object)
                    + type: `activityType` (string)
                    + id: `28158af3-2ef3-4178-ac8b-2542b1481af0` (string)
                + title: `Erlich Bachman's birthday` (string)
                + description (string)
                + starts_at: `2016-02-04T16:00:00+00:00` (string)
                + ends_at: `2016-02-04T18:00:00+00:00` (string)
                + location (string)

### events.info [GET /events.info]

Get details for a single calendar event.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `9a5a3984-abfc-40cd-a880-f97683c6a99c` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `9a5a3984-abfc-40cd-a880-f97683c6a99c` (string)
            + title: `Meeting with stakeholders` (string)
            + description (string)
            + creator (object)
                + type: `user` (string)
                + id: `6f45600a-4402-40e0-9dcc-7665384bcd48` (string)
            + todo (object)
                + type: `todo` (string)
                + id: `be80d753-f2ee-426d-9596-2a2e1a23a82e` (string)
            + activity_type (object)
                + type: `activityType` (string)
                + id: `4a1b1d8e-45da-4c5f-a986-3f93d174d352` (string)
            + starts_at: `2016-02-04T16:00:00+00:00` (string)
            + ends_at: `2016-02-04T18:00:00+00:00` (string)
            + location (string)
            + attendees (array)
                + (object)
                    + type: `contact` (enum[string])
                        + Members
                            + user
                    + id: `8b3afad7-648d-4b4c-b38b-5726d3222282` (string)

### events.create [POST /events.create]

Create a new calendar event.

+ Request (application/json;charset=utf-8)

    + Attributes
        + title: `Meeting with stakeholders` (string, required)
        + description (string, optional)
        + activity_type_id: `b0a9ace5-fe82-4827-9d90-fc52f2c93050` (string, required)
        + starts_at: `2016-02-04T16:00:00+00:00` (string, required)
        + ends_at: `2016-02-04T18:00:00+00:00` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `event` (string)
            + id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string)

## Activity Types [/activityTypes]

Activity types are the different types of events (i.e. tasks, meetings or calls) and to-do’s.
Currently there are three activity types available: tasks, meetings and calls.
Extra (custom) activities types might become available in the future.

### activityTypes.list [GET /activityTypes.list]

Get a list of all activity types.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `7fcf5609-25fe-47e2-97b2-dbd9c817796e`,`366b6100-7005-4b1b-a16a-7e88f445f496` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `9feb5f61-c6dd-4f9d-9b37-2813ada4e343` (string)
                + name (string)

# Group Invoicing

## Invoices [/invoices]

Teamleader provides a whole set of endpoints to make it easy to develop integrations with invoices.
New invoices are created in accordance with this flow: `invoice.draft` → `invoice.book`.
Invoices can also be updated, deleted or credited.

### invoices.list [GET /invoices.list]

Get a list of invoices.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + department_id: `080aac72-ff1a-4627-bfe3-146b6eee979c` (string, optional) - The ID of the department you wish to filter on.
            + status: `booked` (enum[string], optional) - Only return booked or draft invoices. Leave blank to return everything
                + Members
                    + draft
                    + booked
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + invoice_number
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `invoice_number`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2aa4a6a9-9ce8-4851-a9b3-26aea2ea14c4` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
                + invoice_number: `2017/5` (string, nullable)
                + invoice_date: `2016-02-04` (string, nullable)
                + status: `booked` (enum[string])
                    + Members
                        + booked
                        + draft
                + due_on: `2016-03-03` (string, nullable)
                + paid: true (boolean)
                + paid_at: `2016-02-04T16:44:33+00:00` (string, nullable)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + vat_number: `BE0899623035` (string, nullable)
                    + customer (object)
                        + type: `contact` (string)
                        + id: `4b0f959a-27e3-4080-b1b2-a05b374863cb` (string)
                    + for_attention_of (object, nullable)
                        + name: `Radja Nainggolan` (string)
                        + contact (object)
                            + type: `contact` (string)
                            + id: `d4391f46-a32c-458c-b2ee-833fd27a348d` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: 0.21 (number)
                            + taxable (Money)
                            + tax (Money)

### invoices.info [GET /invoices.info]

Get details for a single invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `27300f09-6250-4a23-8557-d84c52f99ecf` (string)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `e540fe7e-dce2-459e-bf7e-24e605fc18b3` (string)
            + department (object)
                + type: `department` (string)
                + id: `8f802cba-443b-4c69-800f-5852e967000b` (string)
            + invoice_number: `2017/5` (string, nullable)
            + invoice_date: `2016-02-04` (string, nullable)
            + status: `booked` (enum[string])
                + Members
                    + booked
                    + draft
            + due_on: `2016-03-03` (string, nullable)
            + paid: true (boolean)
            + paid_at: `2016-02-04T16:44:33+00:00` (string, nullable)
            + invoicee (object)
                + name: `De Rode Duivels` (string)
                + vat_number: `BE0899623035` (string, nullable)
                + customer (object)
                    + type: `contact` (string)
                    + id: `c7db7f80-762a-4e65-8d0c-522700198284` (string)
                + for_attention_of (object, nullable)
                    + name: `Radja Nainggolan` (string)
                    + contact (object)
                        + type: `contact` (string)
                        + id: `f88ab83c-b8ca-497b-a2c6-1ad631fe1cea` (string)
            + discounts (array)
                + (object)
                    + description: `Discount` (string)
                    + type: `percentage` (enum[string])
                        + Members
                            + percentage
                    + value: 15.00 (number)
            + grouped_lines (array)
                + (object)
                    + section (object)
                        + title (string)
                    + line_items (array)
                        + (object)
                            + product (object, nullable)
                                + type: `product` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                            + quantity: 3 (number)
                            + description: `An awesome product` (string)
                            + unit_price (object)
                                + Include Money
                                + tax: `excluding` (enum[string])
                                    + Members
                                        + excluding
                            + tax (object)
                                + rate: 0.21 (number)
                            + discount (object, nullable)
                                + type: `percentage` (enum[string])
                                    + Members
                                        + percentage
                                + value: 15.00 (number)
            + total (object)
                + tax_exclusive (Money)
                + tax_inclusive (Money)
                + payable (Money)
                + taxes (array)
                    + (object)
                        + rate: 0.21 (number)
                        + taxable (Money)
                        + tax (Money)
                + due: 0 (number)
            + payment_term (PaymentTerm)
            + payments (array)
                + (object)
                    + paid_at: `2016-03-03T16:44:33+00:00` (string)
                    + payment (object)
                        + Include Money

### invoices.draft [POST /invoices.draft]

Draft a new invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + customer (object, required)
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id: `ebafa4c5-fa8a-4409-92e5-1b192243372f` (string)
        + department_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac7` (string, required)
        + payment_term (PaymentTerm, required)
        + grouped_lines (array, required)
            + (object)
                + section (object, optional)
                    + title (string, required)
                + line_items (array, required)
                    + (object)
                        + quantity: `3` (number, required)
                        + description: `An awesome product` (string, required)
                        + unit_price (object)
                            + Include Money
                            + tax: `excluding` (enum[string], required)
                                + Members
                                    + excluding
                        + tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `invoice` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### invoices.update [POST /invoices.update]

Update an invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)
        + customer (object, required) - Who is the invoice for?
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id: `2cc40a9c-e674-43db-9b15-447ccb478200` (string)
        + payment_term (PaymentTerm, required)
        + for_attention_of (object, required)
            + One Of
                + name (string, required)
                + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + grouped_lines (array, required)
            + (object)
                + section (object, required)
                    + title (string, required)
                + line_items (array, required)
                    + (object)
                        + quantity: `3` (number, required)
                        + description: `An awesome product` (string, required)
                        + unit_price (object)
                            + Include Money
                            + tax: `excluding` (enum[string])
                                + Members
                                    + excluding
                        + tax_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)

+ Response 204

### invoices.copy [POST /invoices.copy]

Creates a new draft invoice based on another invoice

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `invoice` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### invoices.book [POST /invoices.book]

Book a draft invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `7abb325c-e063-42a4-8fb4-1b730759645a` (string, required)
        + on: `2016-02-04` (string, optional) - If not provided, today will be used

+ Response 204

### invoices.delete [POST /invoices.delete]

Delete an existing invoice. Only possible for draft invoices or the last booked invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `7517d21c-75c1-4b89-8956-0e67f46c8532` (string, required)

+ Response 204

### invoices.registerPayment [POST /invoices.registerPayment]

Register a payment for an invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `7abb325c-e063-42a4-8fb4-1b730759645a` (string, required)
        + payment (object, required)
            + Include Money
        + paid_at: `2016-03-03T16:44:33+00:00` (string, required)

+ Response 204


## Creditnotes [/creditNotes]

### creditNotes.list [GET /creditNotes.list]

List credit notes

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + credit_note_number
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `credit_note_number`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2b43633b-22d1-41b6-b87b-e1fd742325d4` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + credit_note_number: `2017/5` (string, nullable)
                + credit_note_date: `2016-02-04` (string, nullable)
                + status: `booked` (enum[string])
                    + Members
                        + booked
                + invoice (object, nullable)
                    + type: `invoice` (string)
                    + id: `53484141-8382-4948-9a4c-9cd7e79b30bd` (string)
                + paid: `true` (boolean)
                + paid_at: `2016-03-03T16:44:33+00:00` (string, nullable)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + vat_number: `BE0899623035` (string, nullable)
                    + customer (object)
                        + type: `contact` (string)
                        + id: `dc2a40bf-f050-4c8e-a002-872a051150b9` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)


### creditNotes.info [GET /creditNotes.info]

Get details for a single credit note

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `27300f09-6250-4a23-8557-d84c52f99ecf` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `27300f09-6250-4a23-8557-d84c52f99ecf` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + credit_note_number: `2017/5` (string, nullable)
                + credit_note_date: `2016-02-04` (string, nullable)
                + status: `booked` (enum[string])
                    + Members
                        + booked
                + invoice (object, nullable)
                    + type: `invoice` (string)
                    + id: `53484141-8382-4948-9a4c-9cd7e79b30bd` (string)
                + paid: `true` (boolean)
                + paid_at: `2016-03-03T16:44:33+00:00` (string, nullable)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + vat_number: `BE0899623035` (string, nullable)
                    + customer (object)
                        + type: `contact` (string)
                        + id: `dc2a40bf-f050-4c8e-a002-872a051150b9` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)
                + grouped_lines (array)
                    + (object)
                        + section (object)
                            + title (string)
                        + line_items (array)
                            + (object)
                                + product (object, nullable)
                                    + type: `product` (string)
                                    + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                                + quantity: `3` (number)
                                + description: `An awesome product` (string)
                                + unit_price (object)
                                    + Include Money
                                    + tax: `excluding` (enum[string])
                                        + Members
                                            + excluding
                                + tax (object)
                                    + rate: `0.21` (number)
                                + discount (object, nullable)
                                    + type: `percentage` (enum[string])
                                        + Members
                                            + percentage
                                    + value: `15.00` (number)

## Tax Rates [/taxRates]

Tax rates provide an overview of different taxation rates used to bill customers.
Teamleader provides a default list of tax rates based on the country of residence of the company that’s using Teamleader.
The end user also has the option to add additional tax rates.

### taxRates.list [GET /taxRates.list]

Get a list of available tax rates.

+ Request (application/json;charset=utf-8)

+ Attributes (object)
    + filter (object, optional)
        + department_id: `080aac72-ff1a-4627-bfe3-146b6eee979c` (string, optional) - The ID of the department you wish to filter on.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `c93ddb52-0af8-47d9-8551-441435be66a7` (string)
                + description: `21%` (string)
                + rate: 0.21 (number)
                + department (object)
                    + type: `department` (string)
                    + id: `182af0a8-3f68-409b-8941-cf8caf8f28a0` (string)

# Group Projects

## Projects [/projects]

Projects allow users to work together as a team on a single project.
They comprise of one or more milestones, have one or more participants and are limited in time and budget.

### projects.list [GET /projects.list]

Get a list of projects.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + due_on
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `due_on`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `624ca743-8998-4f8c-add1-c427bb022166` (string)
                + reference: `PRO-2` (string)
                + title: `New company website` (string)
                + description (string)
                + status: `active` (enum[string])
                    + Members
                        + active
                        + on_hold
                        + done
                        + cancelled
                + customer (object)
                    + type: `contact` (string)
                    + id: `abbf02c0-8ff9-4048-b83f-5195035161e1` (string)
                + starts_on: `2016-02-04` (string)
                + due_on: `2016-10-14` (string)
                + source (object)
                    + type: `deal` (string)
                    + id: `5023d7c2-80d7-4d4b-b2bd-0fcaa6a1f069` (string)


### projects.info [GET /projects.info]

Get details for a single project.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `8a04371b-2ffb-407b-9b24-d5b5452009c7` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `8a04371b-2ffb-407b-9b24-d5b5452009c7` (string)
            + reference: `PRO-1` (string)
            + title: `New company website` (string)
            + description (string)
            + status: `active` (enum[string])
                + Members
                    + active
                    + on_hold
                    + done
                    + cancelled
            + customer (object)
                + type: `contact` (enum[string])
                    + Members
                        + contact
                        + company
                + id: `de41d3e8-808f-4279-b6ff-4706b04c8df2` (string)
            + starts_on: `2016-02-04` (string)
            + due_on: `2016-02-04` (string)
            + source (object)
                + type: `deal` (string)
                + id: `39abbf9e-9692-4cca-b20d-79577890752c` (string)
            + milestones (array)
                + (object)
                    + type: `milestone` (string)
                    + id: `7c6b5e26-3068-47a6-bf3b-431d7ab7e704` (string)
            + participants (array)
                + (object)
                    + participant (object)
                        + type: `user` (enum[string])
                            + Members
                                + user
                        + id: `b0ef899b-143c-4708-90ce-aecb3350e116` (string)
                    + role (enum[string])
                        + Members
                            + decision_maker
                            + member


### projects.create [POST /projects.create]

Create a new project.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + title: `New company website` (string, required)
        + description (string, optional)
        + starts_on: `2016-02-04` (string, required)
        + milestones (array, required) - At least one milestone is required
            + (object)
                + due_on: `2018-01-01` (string, required)
                + name: `Initial setup` (string, required)
                + responsible_user_id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string, required)
        + participants (array, required) - At least one decision making participant is required
            + (object)
                + participant (object, required)
                    + type: `user` (string, required)
                    + id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string, required)
                + role (enum[string], optional)
                    + Members
                        + decision_maker
                        + member
                    + Default: `member`

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `project` (string)
            + id: `c47e8e40-9a16-468f-9b29-38aea8ae4210` (string)


### projects.update [POST /projects.update]

Update a project.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `dcc2e8ed-51be-4cb6-9c01-034aedac86fd` (string, required)
        + title: `New company website` (string, required)
        + description (string, required)
        + status: `active` (enum[string], required)
            + Members
                + active
                + on_hold
                + done
                + cancelled
        + starts_on: `2016-02-04` (string, required)

+ Response 204 (application/json;charset=utf-8)


### projects.delete [POST /projects.delete]

Delete a project.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `01548b10-4932-4a18-8a89-005ad09db2c8` (string, required)

+ Response 204 (application/json;charset=utf-8)


### projects.addParticipant [POST /projects.addParticipant]

Add a participant to a project.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `8dbfa9db-c53f-410c-97d3-755b19685809` (string, required)
        + participant (object, required)
            + type: `user` (string)
            + id: `a1388f3d-6116-4792-ac1c-04657697539e` (string)
        + role (enum[string], optional)
            + Members
                + decision_maker
                + member
            + Default: `member`

+ Response 204


### projects.updateParticipant [POST /projects.updateParticipant]

Update a participant's role for a project.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `55fbe14f-7399-48e5-b4e0-64b7f5c50451` (string, required)
        + participant (object, optional)
            + type: `user` (string)
            + id: `5ccbc008-f65e-4192-836c-4d7e21f54052` (string)
        + role (enum[string], required)
            + Members
                + decision_maker
                + member

+ Response 204

## Milestones [/milestones]

Every projects consists of one or more milestones which are limited in time and budget.
Budget is however not included in this endpoints (yet).

### milestones.list [GET /milestones.list]

Get a list of project milestones.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `bbbfe0da-e692-4ee3-9d3d-0716808d6523`,`722e1eb9-53d5-4b8c-9d17-154dcc65c610` (array[string], optional)
            + project_id: `082e6289-30c5-45ad-bcd0-190b02d21e81` (string, optional)
            + status (enum[string], optional)
                + Members
                    + open
                    + closed
            + due_before: `2017-01-01` (string, optional)
            + due_after: `2017-01-01` (string, optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + due_on
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `due_on`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `cfb4146d-06be-41f1-bb39-aa3c929c71dc` (string)
                + project (object)
                    + type: `project` (string)
                    + id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string)
                + due_on: `2018-01-01` (string)
                + name: `Initial setup` (string)
                + responsible_user (object)
                    + type: `user` (string)
                    + id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string)
                + status: `done` (enum[string])
                    + Members
                        + open
                        + closed

### milestones.info [GET /milestones.info]

Get details for a single milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `64349fa2-6ca2-4b19-82e6-d3258ceab2d8` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `64349fa2-6ca2-4b19-82e6-d3258ceab2d8` (string)
            + project (object)
                + type: `project` (string)
                + id: `fffaf951-b65a-4cb1-bfb6-4b93e0e60c10` (string)
            + due_on: `2018-01-01` (string)
            + name: `Initial setup` (string)
            + responsible_user (object)
                + type: `user` (string)
                + id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string)
            + status: `done` (enum[string])
                + Members
                    + open
                    + closed

### milestones.create [POST /milestones.create]

Create a new milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + project_id: `1c159f98-4b07-438a-9f42-fb4206b9530d` (string, required)
        + due_on: `2018-01-01` (string, required)
        + name: `Initial setup` (string, required)
        + responsible_user_id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `milestone` (string)
            + id: `51f19f91-6343-4001-a628-3afe45f674ad` (string)

### milestones.update [POST /milestones.update]

Update a milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `67e80ad8-d14f-4510-a2bd-a4c6aa578c37` (string, required)
        + due_on: `2018-01-01` (string, optional)
        + name: `Initial setup` (string, optional)
        + responsible_user_id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string, optional)

+ Response 204 (application/json;charset=utf-8)

# Group Other

## Migrating [/migrate]

WARNING! These endpoints are not guaranteed to stay backwards compatible.
Their only use is to allow older integrations to migrate their data to the new API.

### migrate.id [GET /migrate.id]

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + type: `contact` (enum[string])
            + Members
                + account
                + user
                + product
                + contact
                + company
                + deal
                + dealPhase
                + project
                + milestone
                + task
                + meeting
                + call
                + ticket
                + invoice
                + creditNote
                + subscription
        + id: `1` (number)

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + type: `contact` (enum[string])
                + Members
                    + account
                    + user
                    + product
                    + contact
                    + company
                    + deal
                    + dealPhase
                    + project
                    + milestone
                    + todo
                    + event
                    + ticket
                    + invoice
                    + creditNote
                    + subscription
            + id: `6ad54ec6-ee2d-4500-afe6-0917c1aa7a38` (string)

### migrate.taxRate [GET /migrate.taxRate]

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + department_id: `6ad54ec6-ee2d-4500-afe6-0917c1aa7a38` (string)
        + tax_rate: `21` (string)

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + type: `taxRate` (string)
            + id: `6ad54ec6-ee2d-4500-afe6-0917c1aa7a38` (string)

### migrate.activityType [GET /migrate.activityType]

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + type: `meeting` (enum[string])
            + Members
                + meeting
                + call
                + task

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + type: `activityType` (string)
            + id: `28f3639d-9b64-44a8-974d-a4df645af6a5` (string)


# Data Structures

## Telephone (object)
+ type: `phone` (enum[string], required)
    + Members
        + phone
        + mobile
        + fax
+ number: `092980615` (string, required)

## CompanyTelephone (object)
+ type: `phone` (enum[string], required)
    + Members
        + phone
        + fax
+ number: `092980615` (string, required)

## Address (object)
+ line_1: `Dok Noord 3A 101` (string, optional)
+ postal_code: `9000` (string, optional)
+ city: `Ghent` (string, optional)
+ country: `BE` (string, required)

## Addressee (object)
+ addressee: `Teamleader HQ` (string, optional)
+ Include Address

## Money (object)
+ amount: `123.30` (number, required)
+ currency: `EUR` (enum[string], required)
    + Members
        + BAM
        + CAD
        + CHF
        + CLP
        + CNY
        + COP
        + CZK
        + DKK
        + EUR
        + GBP
        + INR
        + ISK
        + JPY
        + MAD
        + MXN
        + NOK
        + PEN
        + PLN
        + RON
        + SEK
        + TRY
        + USD
        + ZAR

## Page
+ size: `20` (number, optional)
    + Default: `20`
+ number: `1` (number, optional)
    + Default: `1`

## PaymentTerm  (object)
+ type (enum[string])
    + Members
        + cash - Direct payment, often cash
        + end_of_month - End of the month of Xth day after the invoice date
        + after_invoice_date - X days after invoice date
+ days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.
