## Creditnotes [/creditNotes]

### creditNotes.list [GET /creditNotes.list]

List credit notes

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `685bd765-9197-42ce-9c31-29287b51132d`,`0cc9af77-2c82-4788-92a4-80cdf0d26875` (array[string], optional)
            + customer (object, optional)
                + type: `contact` (enum[string], required)
                    + Members
                        + contact
                        + company
                + id: `90162683-d5ff-4ec0-b3d1-6a26022c5009` (string, required)
            + credit_note_date_after: `2016-01-01` (string, optional) - Format: yyyy-mm-dd
            + credit_note_date_before: `2016-01-01` (string, optional) - yyyy-mm-dd
            + department_id: `320c7e39-26c1-45b5-84aa-75ef89e8890f` (string, optional) - The ID of the department you wish to filter on.
            + invoice_id: `841b63a5-1b38-4480-8538-25a0d6a237b9` (string, optional) - The ID of the invoice you wih to filter on.
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + credit_note_number
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `credit_note_number`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2b43633b-22d1-41b6-b87b-e1fd742325d4` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + invoice (object)
                    + type: `invoice` (string)
                    + id: `53484141-8382-4948-9a4c-9cd7e79b30bd` (string)
                + credit_note_number: `2017/5` (string)
                + credit_note_date: `2016-02-04` (string)
                + status: `booked` (enum[string])
                    + Members
                        + booked
                + paid: `true` (boolean)
                + paid_at: `2016-03-03T16:44:33+00:00` (string)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + address (Address)
                    + vat_number: `BE0899623035` (string)
                    + customer (object)
                        + type: `contact` (string)
                        + id: `dc2a40bf-f050-4c8e-a002-872a051150b9` (string)
                    + for_attention_of (object)
                        + name: `Radja Nainggolan` (string)
                        + contact (object)
                            + type: `contact` (string)
                            + id: `0fe33f4a-7a77-4e1b-8f34-b70d47e377fd` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)
                    + withheld_taxes (array)
                        + (object)
                            + type: `Trabajo`
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)


### creditNotes.info [GET /creditNotes.info]

Get a single credit note

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `27300f09-6250-4a23-8557-d84c52f99ecf` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `2b43633b-22d1-41b6-b87b-e1fd742325d4` (string)
            + department (object)
                + type: `department` (string)
                + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
            + invoice (object)
                + type: `invoice` (string)
                + id: `53484141-8382-4948-9a4c-9cd7e79b30bd` (string)
            + credit_note_number: `2017/5` (string)
            + credit_note_date: `2016-02-04` (string)
            + status: `booked` (enum[string])
                + Members
                    + booked
            + paid: `true` (boolean)
            + paid_at: `2016-03-03T16:44:33+00:00` (string)
            + invoicee (object)
                + name: `De Rode Duivels` (string)
                + address (Address)
                + vat_number: `BE0899623035` (string)
                + customer (object)
                    + type: `contact` (string)
                    + id: `dc2a40bf-f050-4c8e-a002-872a051150b9` (string)
                + for_attention_of (object)
                    + name: `Radja Nainggolan` (string)
                    + contact (object)
                        + type: `contact` (string)
                        + id: `0fe33f4a-7a77-4e1b-8f34-b70d47e377fd` (string)
            + grouped_lines (array[ReadLineItemGroup])
            + total (object)
                + tax_exclusive (Money)
                + tax_inclusive (Money)
                + payable (Money)
                + taxes (array)
                    + (object)
                        + rate: `0.21` (number)
                        + taxable (Money)
                        + tax (Money)
                + withheld_taxes (array)
                    + (object)
                        + type: `Trabajo`
                        + rate: `0.21` (number)
                        + taxable (Money)
                        + tax (Money)


### creditNotes.draft [POST /creditNotes.draft]

Create a draft credit note.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `5ff010c0-7d88-457b-98ae-7ddee607cd8c`  (string, optional)
        + customer (object, optional)
            + type (enum[string], required)
                + Members
                    + contact
                    + company
            + id: `adf63e53-689a-4efb-9521-1dc2a300cec4` (string, required)
        + for_attention_of (object, optional)
            + One Of
                + name (string, required)
                + contact_id: `3f31dfd3-f238-4909-8ff0-e891da9beba2` (string, required)
        + department_id: `ac44fb43-8fb0-4b80-82c6-676117d558e5` (string, required)
        + payment_term (object, optional)
            + type (enum[string], required)
                + Members
                    + cash - Direct payment, often cash
                    + end_of_month - End of the month of Xth day after the invoice date
                    + after_invoice_date - X days after invoice date
            + days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.
        + layout_id: `fbc2edb9-f2ab-4a3f-b49f-3602a5e2a09b` (string, optional)
        + purchase_order_number (string, optional) - The external order number. Overrides possible PO number coming from project.
        + remarks (string, optional) - Free form text. Visible on the invoice depending on the template.
        + grouped_lines (array[WriteLineItemGroup], optional)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `creditNote` (string)
            + id: `af89d055-ffa0-4832-8af1-cc1bc1700daf` (string)

### creditNotes.update [POST /creditNotes.update]

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `41aadb77-9d31-4e68-8670-de30dd0c7e39` (string, required)
        + customer (object, optional)
            + type (enum[string], required)
                + Members
                    + contact
                    + company
            + id: `fdb8a326-8696-4dae-927e-7c001f99b4bb` (string, required)
        + for_attention_of (object, optional)
            + One Of
                + name (string, required)
                + contact_id: `3dacb02f-aa3b-4ff4-bfac-1a585f87ebfe` (string, required)
        + department_id: `c8d8e910-1d17-48ff-b09e-2f77f2551c96` (string, optional)
        + payment_term (object, optional)
            + type (enum[string], required)
                + Members
                    + cash - Direct payment, often cash
                    + end_of_month - End of the month of Xth day after the invoice date
                    + after_invoice_date - X days after invoice date
            + days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.
        + layout_id: `fdd68c4a-77bf-4888-97c2-a81682fe9330` (string, optional)
        + purchase_order_number (string, optional) - The external order number. Overrides possible PO number coming from project.
        + remarks (string, optional) - Free form text. Visible on the invoice depending on the template.
        + grouped_lines (array[WriteLineItemGroup], optional)

+ Response 204

### creditNotes.book [POST /creditNotes.book]

Book a draft creditNote.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `dfe72aa9-7812-496c-ac60-2c259941036f` (string, required)
        + on: `2016-02-04` (string, optional) - If not provided, today will be used

+ Response 204
