## Invoices [/invoices]

Teamleader provides a whole set of endpoints to make it easy to develop integrations with invoices.
New invoices are created in accordance with this flow: `invoice.draft` → `invoice.book`.
Invoices can also be updated, deleted or credited.

### invoices.list [GET /invoices.list]

Get a list of invoices.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + department_id: `080aac72-ff1a-4627-bfe3-146b6eee979c` (string, optional) - The ID of the department you wish to filter on.
            + status: `booked` (enum[string], optional) - Only return booked or draft invoices. Leave blank to return everything
                + Members
                    + draft
                    + booked
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + invoice_number
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `invoice_number`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2aa4a6a9-9ce8-4851-a9b3-26aea2ea14c4` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
                + invoice_number: `2017/5` (string, nullable)
                + invoice_date: `2016-02-04` (string, nullable)
                + status: `booked` (enum[string])
                    + Members
                        + booked
                        + draft
                + due_on: `2016-03-03` (string, nullable)
                + paid: true (boolean)
                + paid_at: `2016-02-04T16:44:33+00:00` (string, nullable)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + vat_number: `BE0899623035` (string, nullable)
                    + customer (object)
                        + type: `contact` (string)
                        + id: `4b0f959a-27e3-4080-b1b2-a05b374863cb` (string)
                    + for_attention_of (object, nullable)
                        + name: `Radja Nainggolan` (string)
                        + contact (object)
                            + type: `contact` (string)
                            + id: `d4391f46-a32c-458c-b2ee-833fd27a348d` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: 0.21 (number)
                            + taxable (Money)
                            + tax (Money)

### invoices.info [GET /invoices.info]

Get details for a single invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `27300f09-6250-4a23-8557-d84c52f99ecf` (string)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `e540fe7e-dce2-459e-bf7e-24e605fc18b3` (string)
            + department (object)
                + type: `department` (string)
                + id: `8f802cba-443b-4c69-800f-5852e967000b` (string)
            + invoice_number: `2017/5` (string, nullable)
            + invoice_date: `2016-02-04` (string, nullable)
            + status: `booked` (enum[string])
                + Members
                    + booked
                    + draft
            + due_on: `2016-03-03` (string, nullable)
            + paid: true (boolean)
            + paid_at: `2016-02-04T16:44:33+00:00` (string, nullable)
            + invoicee (object)
                + name: `De Rode Duivels` (string)
                + vat_number: `BE0899623035` (string, nullable)
                + customer (object)
                    + type: `contact` (string)
                    + id: `c7db7f80-762a-4e65-8d0c-522700198284` (string)
                + for_attention_of (object, nullable)
                    + name: `Radja Nainggolan` (string)
                    + contact (object)
                        + type: `contact` (string)
                        + id: `f88ab83c-b8ca-497b-a2c6-1ad631fe1cea` (string)
            + discounts (array)
                + (object)
                    + description: `Discount` (string)
                    + type: `percentage` (enum[string])
                        + Members
                            + percentage
                    + value: 15.00 (number)
            + grouped_lines (array)
                + (object)
                    + section (object)
                        + title (string)
                    + line_items (array)
                        + (object)
                            + product (object, nullable)
                                + type: `product` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                            + quantity: 3 (number)
                            + description: `An awesome product` (string)
                            + unit_price (object)
                                + Include Money
                                + tax: `excluding` (enum[string])
                                    + Members
                                        + excluding
                            + tax (object)
                                + rate: 0.21 (number)
                            + discount (object, nullable)
                                + type: `percentage` (enum[string])
                                    + Members
                                        + percentage
                                + value: 15.00 (number)
            + total (object)
                + tax_exclusive (Money)
                + tax_inclusive (Money)
                + payable (Money)
                + taxes (array)
                    + (object)
                        + rate: 0.21 (number)
                        + taxable (Money)
                        + tax (Money)
                + total_due: 0 (number)
            + payment_term (PaymentTerm)
            + payments (array)
                + (object)
                    + paid_at: `2016-03-03T16:44:33+00:00` (string)
                    + payment (object)
                        + Include Money

### invoices.draft [POST /invoices.draft]

Draft a new invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + customer (object, required)
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id: `ebafa4c5-fa8a-4409-92e5-1b192243372f` (string)
        + department_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac7` (string, required)
        + payment_term (PaymentTerm, required)
        + grouped_lines (array, required)
            + (object)
                + section (object, optional)
                    + title (string, required)
                + line_items (array, required)
                    + (object)
                        + quantity: `3` (number, required)
                        + description: `An awesome product` (string, required)
                        + unit_price (object)
                            + Include Money
                            + tax: `excluding` (enum[string], required)
                                + Members
                                    + excluding
                        + tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `invoice` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### invoices.update [POST /invoices.update]

Update an invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)
        + customer (object, required) - Who is the invoice for?
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id: `2cc40a9c-e674-43db-9b15-447ccb478200` (string)
        + payment_term (PaymentTerm, required)
        + for_attention_of (object, required)
            + One Of
                + name (string, required)
                + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + grouped_lines (array, required)
            + (object)
                + section (object, required)
                    + title (string, required)
                + line_items (array, required)
                    + (object)
                        + quantity: `3` (number, required)
                        + description: `An awesome product` (string, required)
                        + unit_price (object)
                            + Include Money
                            + tax: `excluding` (enum[string])
                                + Members
                                    + excluding
                        + tax_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)

+ Response 204

### invoices.copy [POST /invoices.copy]

Creates a new draft invoice based on another invoice

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `invoice` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### invoices.book [POST /invoices.book]

Book a draft invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `7abb325c-e063-42a4-8fb4-1b730759645a` (string, required)
        + on: `2016-02-04` (string, optional) - If not provided, today will be used

+ Response 204

### invoices.delete [POST /invoices.delete]

Delete an existing invoice. Only possible for draft invoices or the last booked invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `7517d21c-75c1-4b89-8956-0e67f46c8532` (string, required)

+ Response 204

### invoices.registerPayment [POST /invoices.registerPayment]

Register a payment for an invoice.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `7abb325c-e063-42a4-8fb4-1b730759645a` (string, required)
        + payment (object, required)
            + Include Money
        + paid_at: `2016-03-03T16:44:33+00:00` (string, required)

+ Response 204

