## Settings [/invoicing]

### taxRates.list [GET /taxRates.list]

Get a list of available tax rates.

+ Request (application/json;charset=utf-8)

+ Attributes (object)
    + filter (object, optional)
        + department_id: `080aac72-ff1a-4627-bfe3-146b6eee979c` (string, optional) - The ID of the department you wish to filter on.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `c93ddb52-0af8-47d9-8551-441435be66a7` (string)
                + description: `21%` (string)
                + rate: `0.21` (number)
                + department (object)
                    + type: `department` (string)
                    + id: `182af0a8-3f68-409b-8941-cf8caf8f28a0` (string)
