## Subscriptions [/subscriptions]

### subscriptions.info [GET /subscriptions.info]

+ Request (application/json)

    + Attributes (object)
        + id: `e3dd1c91-afd2-42e8-a3d7-37694d54536b` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `e3dd1c91-afd2-42e8-a3d7-37694d54536b` (string)
            + department (object)
                + type: `department` (string)
                + id: `182af0a8-3f68-409b-8941-cf8caf8f28a0` (string)
            + starts_on (string)
            + ends_on (string)
            + frequency (object)
                + every: 10 (number)
                + period (enum[string])
                    + Members
                        + day
                        + week
                        + month
                        + quarter
                        + year
            + payment_term (object)
                + type (enum[string])
                    + Members
                        + cash - Direct payment, often cash
                        + end_of_month - End of the month of Xth day after the invoice date
                        + after_invoice_date - X days after invoice date
                + days (number) - Modifier "X" for the above statements. Not required when type is 'cash'.
            + invoicee (object)
                + name: `De Rode Duivels` (string)
                + address (Address)
                + vat_number: `BE0899623035` (string)
                + customer (object)
                    + type: `contact` (string)
                    + id: `4c596fba-92d2-447c-99c8-a41afec997c6` (string)
                + for_attention_of (object)
                    + name: `Radja Nainggolan` (string)
                    + contact (object)
                        + type: `contact` (string)
                        + id: `e37c2197-fb79-4b70-b9a0-9992f14750ad` (string)
            + grouped_lines (array[ReadLineItemGroup])
            + total (object)
                + tax_exclusive (Money)
                + tax_inclusive (Money)
                + payable (Money)
                + taxes (array)
                    + (object)
                        + rate: `0.21` (number)
                        + taxable (Money)
                        + tax (Money)
                + withheld_taxes (array)
                    + (object)
                        + type: `Trabajo`
                        + rate: `0.21` (number)
                        + taxable (Money)
                        + tax (Money)
