## Deal Pipelines [/dealPipelines]

Each deal belongs to a specific pipeline, in which it goes through the different deal phases.

*Required scopes: `deals`*

### dealPipelines.list [GET /dealPipelines.list]

Get a list of all deal pipelines.

+ Request (application/json)
    + Attributes (object)
        + filter (object, optional)
            + `ids`: `46156648-87c6-478d-8aa7-1dc3a00dacab`, `46156648-87c6-478d-8aa7-1dc3a00daca4` (array[string])
            + status (array, optional)
                + (enum)
                    + Members
                        + open
                        + pending_deletion
        + page (Page, optional)

+ Response 200 (application/json)
    + Attributes (object)
        + data (array)
            + (object)
                + id: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string)
                + name: `Main Pipeline` (string)
        + meta (object) - Only included with request parameter `includes=pagination`
            + default: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string)
            + page (Pagination)
            + matches: `12` (number)
