## Deal Pipelines [/dealPipelines]

Each deal belongs to a specific pipeline, in which it goes through the different deal phases.

*Required scopes: `deals`*

### dealPipelines.list [GET /dealPipelines.list]

Get a list of all deal pipelines.

+ Request (application/json)
    + Attributes (object)
        + filter (object, optional)
            + `ids`: `46156648-87c6-478d-8aa7-1dc3a00dacab`, `46156648-87c6-478d-8aa7-1dc3a00daca4` (array[string])
            + status (array, optional)
                + (enum)
                    + Members
                        + open
                        + pending_deletion
        + page (Page, optional)

+ Response 200 (application/json)
    + Attributes (object)
        + data (array)
            + (object)
                + id: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string)
                + name: `Main Pipeline` (string)
        + meta (object)
            + `default`: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string)
            + `page` (Pagination) - Only included with request parameter `includes=pagination`
            + `matches`: `12` (number) - Only included with request parameter `includes=pagination`

### dealPipelines.create [POST /dealPipelines.create]

Create a new deal pipeline.

+ Request (application/json)

    + Attributes (object)
        + name: `Primary Pipeline` (string, required)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `dealPipeline` (string)
            + id: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string)

### dealPipelines.update [POST /dealPipelines.update]

Update a single deal pipeline.

+ Request (application/json)

    + Attributes (object)
        + id: `254dc5ee-f8de-0791-9e31-a4f7817e64d2` (string, required)
        + name: `Main Pipeline` (string, required)

+ Response 204

### dealPipelines.markAsDefault [POST /dealPipelines.markAsDefault]

Mark a pipeline as default.

+ Request (application/json)

    + Attributes (object)
        + id: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string, required)

+ Response 202 (application/json)

### dealPipelines.duplicate [POST /dealPipelines.duplicate]

Create a new deal pipeline by duplicating an existing one.

+ Request (application/json)

    + Attributes (object)
        + id: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string, required) - Id from source pipeline

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `dealPipeline` (string)
            + id: `5876126e-11c2-4731-b9e3-6e2fecd01d80` (string, required)

### dealPipelines.delete [POST /dealPipelines.delete]

Delete a deal pipeline.

+ Request (application/json)

    + Attributes (object)
        + id: `f350e48a-fbc3-0a79-e62a-53aa1ae86d44` (string, required)
        + migrate_phases (array, optional) - Array of phase ids to migrate deals to
            + (object)
                + `old_phase_id`: `57785244-0d45-0f01-9c18-5ce1cb68e4c1` (string, required)
                + `new_phase_id`: `29648aea-52f9-09f7-8e1e-cc5c08b4c742` (string, required)

+ Response 204 (application/json)
