## Deals [/deals]

Deals are sale opportunities, which need to be followed up by their responsible user. A deal can move through specific deal phases, and be marked as won or lost.

*Required scopes: `deals`*

### deals.list [GET /deals.list]

Get a list of deals.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `3f507137-e599-41d4-8625-0e2adba0be4c`,`ae97f6d3-0bb4-43d3-b13d-f06069d07e98` (array[string], optional)
            + customer (object, optional)
                + type (enum[string], required)
                    + Members
                        + company
                        + contact
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
            + phase_id: `1758e847-cc1f-04ce-bd17-5a852e8c01b4` (string, optional)
            + responsible_user_id: `98b2863e-7b01-4232-82f5-ede1f0b9db22` (string, optional)
            + updated_since: `2018-02-11T16:45:30+00:00` (string, optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + created_at
                + order (enum[string], optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `created_at`
                    + order: `desc`


+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `6e7fe84d-d4b3-4723-abae-9bc082d8f65a` (string)
                + title: `Interesting deal` (string)
                + reference: `2017/2` (string)
                + status: `won` (enum[string])
                    + Members
                        + new
                        + open
                        + won
                        + lost
                + lead (object)
                    + customer (object)
                        + type: `company` (enum[string])
                            + Members
                                + contact
                                + company
                        + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
                    + contact_person (object)
                        + type: `contact` (string)
                        + id: `74c6769e-815a-4774-87d7-dfab9b1a0abb` (string)
                + department (object)
                    + type: `department`
                    + id: `33121d39-44e2-426a-92ef-62178edeec8a` (string)
                + estimated_value (Money)
                + estimated_closing_date: `2017-05-09` (string)
                + estimated_probability: `0.5` (number)
                + current_phase (object)
                    + type: `dealPhase`
                    + id: `521a331d-60d1-4920-bde3-ccd01d09f9f1` (string)
                + responsible_user (object)
                    + type: `user`
                    + id: `bac1c91b-bc86-489b-8590-9be9478f62bb` (string)
                + closed_at: `2017-05-09T11:31:30+00:00` (string)
                + source (object)
                    + type: `dealSource` (string)
                    + id: `52a4bbb2-d196-48d7-8e43-9ec2f44d06f9` (string)
                + created_at: `2017-05-09T11:25:11+00:00` (string)
                + updated_at: `2017-05-09T11:30:58+00:00` (string)

### deals.info [GET /deals.info]

Get details for a single deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `f6871b06-6513-4750-b5e6-ff3503b5a029` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `f6871b06-6513-4750-b5e6-ff3503b5a029` (string)
            + title: `Interesting deal` (string)
            + reference: `2017/2` (string)
            + status: `won` (enum[string])
                + Members
                    + open
                    + won
                    + lost
            + lead (object)
                + customer (object)
                    + type: `company` (enum[string])
                        + Members
                            + contact
                            + company
                    + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
                + contact_person (object)
                    + type: `contact` (string)
                    + id: `74c6769e-815a-4774-87d7-dfab9b1a0abb` (string)
            + department (object)
                + type: `department`
                + id: `92247818-643e-4f5a-bf87-25cd908e8ad9` (string)
            + estimated_value (Money)
            + estimated_closing_date: `2017-05-09` (string)
            + estimated_probability: `0.5` (number)
            + current_phase (object)
                + type: dealPhase (string)
                + id: `676a6070-f7d3-43a6-bc08-cda0d32c27ab` (string)
            + responsible_user (object)
                + type: user (string)
                + id: `4e81f3c4-7dca-44cb-b126-6158bec392a2` (string)
            + closed_at: `2017-05-09T11:31:30+00:00` (string)
            + source (object)
                + type: `dealSource` (string)
                + id: `aba0ad66-bf59-49fa-b546-45dcbc5e7e6e` (string)
            + phase_history (array)
                + (object)
                    + phase (object)
                        + type: dealPhase (string)
                        + id: `d5a629f2-7b58-4748-aaca-acf9b6d62404` (string)
                    + started_at: `2017-05-01 12:00:00` (string)
                    + started_by (object)
                        + type: user (string)
                        + id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string)
            + quotations (array)
                + (object)
                    + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)
                    + type: `quotation` (string)
            + created_at: `2017-05-09T11:25:11+00:00` (string)
            + updated_at: `2017-05-09T11:30:58+00:00` (string)
            + custom_fields (array[CustomField])

### deals.create [POST /deals.create]

Create a new deal for a customer.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + lead (object, required)
            + customer (object, required)
                + type (enum[string], required)
                    + Members
                        + contact
                        + company
                + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
            + contact_person_id: `b38ebb9b-6e46-4bf4-a1e2-af747d6b64ae` (string, optional)
        + title: `Interesting business deal` (string, required)
        + source_id: `b38ebb9b-6e46-4bf4-a1e2-af747d6b64ae` (string, optional)
        + department_id: `6a6343fc-fdd8-4bc0-aa69-3a004c710e87` (string, optional)
        + responsible_user_id: `98b2863e-7b01-4232-82f5-ede1f0b9db22` (string, optional)
        + phase_id: `060687bb-a742-4882-a538-199a5e5feb60` (string, optional)
        + estimated_value (Money, optional)
        + estimated_probability: `0.75` (number, optional) - A number between 0 and 1 (inclusive)
        + estimated_closing_date: `2017-05-09` (string, optional)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `deal` (string)
            + id: `65a35860-dcca-4850-9fd6-47ff08469e0c` (string)

### deals.update [POST /deals.update]

Update a deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `65a35860-dcca-4850-9fd6-47ff08469e0c` (string, required)
        + lead (object, required)
            + customer (object, required)
                + type (enum[string], required)
                    + Members
                        + contact
                        + company
                + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
            + contact_person_id: `b38ebb9b-6e46-4bf4-a1e2-af747d6b64ae` (string, optional)
        + title: `Interesting business deal` (string, optional)
        + source_id: `b38ebb9b-6e46-4bf4-a1e2-af747d6b64ae` (string, optional, nullable)
        + department_id: `6a6343fc-fdd8-4bc0-aa69-3a004c710e87` (string, optional, nullable)
        + responsible_user_id: `98b2863e-7b01-4232-82f5-ede1f0b9db22` (string, optional, nullable)
        + estimated_value (Money, optional, nullable)
        + estimated_probability: `0.75` (number, optional, nullable) - A number between 0 and 1 (inclusive)
        + estimated_closing_date: `2017-05-09` (string, optional, nullable)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 204

### deals.move [POST /deals.move]

Move the deal to a different phase.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e88131bf-50c4-49d3-8ae3-47e5d9626bf6` (string, required)
        + phase_id: `8776abee-d856-43c6-b98d-9ffc912e8b0b` (string, required)

+ Response 204

### deals.win [POST /deals.win]

Mark a deal as won.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e88131bf-50c4-49d3-8ae3-47e5d9626bf6` (string, required)

+ Response 204

### deals.lose [POST /deals.lose]

Mark a deal as lost.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `460df7b2-fe82-4c6c-b215-6d0a1bd3c742` (string, required)
        + reason_id: `da4c902f-2ae5-4c1f-be6f-b50308aabc5c` (string, optional)
        + extra_info: `Not ready for a change, decision postponed` (string, optional)

+ Response 204

### deals.delete [POST /deals.delete]

Delete a deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4e235f27-0af0-40e5-82f3-d32d0aa9edb3` (string, required)

+ Response 204

### lostReasons.list [GET /lostReasons.list]

Get a list of lost reasons for deals.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + name
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `6e7fe84d-d4b3-4723-abae-9bc082d8f65a` (string)
                + name: `Deal declined` (string)
