## Quotations [/quotations]

A quotation is a sales offer for a specific customer. It is always attached to a deal. Quotations can be signed online via Cloudsign.

*Required scopes: `quotations`*

### quotations.list [POST /quotations.list]

Get a list of quotations.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `5b16f6ee-e302-0079-901b-50c26c4a55b1`, `2700006a-b351-070b-b311-fb45ed99abe2` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `5b16f6ee-e302-0079-901b-50c26c4a55b1` (string)
                + deal (object)
                    + type: `deal` (string)
                    + id: `53474a7a-f9b2-4dd4-88a8-40ce773c7a64` (string)
                + currency_exchange_rate (object)
                    + from: `USD` (string)
                    + to: `EUR` (string)
                    + rate: 1.1234 (number)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + taxes (array)
                        + (object)
                            + rate: 0.21 (number)
                            + taxable (Money)
                            + tax (Money)
                    + purchase_price (Money, nullable)
                + created_at: `2017-05-09T11:25:11+00:00` (string, nullable)
                + updated_at: `2017-05-09T11:30:58+00:00` (string, nullable)
                + status: `open` (enum)
                    + Members
                        + open
                        + accepted
                        + expired
                        + rejected
                        + closed
                + name: `Webdevelopment` (string)
                + expiry (object) - returned if user has access to quotation expiry and `includes=expiry` is requested
                    + expires_after: `2023-04-05` (string)
                    + action_after_expiry (enum[string])
                        + Members
                            + lock
                            + none

### quotations.info [POST /quotations.info]

Get a quotation

+ Request (application/json)

    + Attributes (object)
        + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string)
            + deal (object)
                + type: `deal` (string)
                + id: `53474a7a-f9b2-4dd4-88a8-40ce773c7a64` (string)
            + grouped_lines (array)
                + (object)
                    + section (object)
                        + title (string)
                    + line_items (array)
                        + (object)
                            + product (object, nullable)
                                + type: `product` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                            + quantity: 3 (number)
                            + description: `An awesome product` (string)
                            + extended_description: `Some more information about this awesome product` (string) - Uses Markdown formatting
                            + unit (object, nullable)
                                + type: `unitOfMeasure` (string)
                                + id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string)
                            + unit_price (object)
                                + Include Money
                                + tax: `excluding` (enum)
                                    + Members
                                        + excluding
                            + tax (object)
                                + type: `taxRate` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449042`
                            + discount (object, nullable)
                                + type: `percentage` (enum)
                                    + Members
                                        + percentage
                                + value: 15.00 (number)
                            + purchase_price (Money, nullable)
                            + total
                                + tax_exclusive (Money)
                                + tax_exclusive_before_discount (Money)
                                + tax_inclusive (Money)
                                + tax_inclusive_before_discount (Money)
                            + periodicity (Periodicity)
            + currency: `USD` (string)
            + currency_exchange_rate (object)
                + from: `USD` (string)
                + to: `EUR` (string)
                + rate: 1.1234 (number)
            + total (object)
                + tax_exclusive (Money)
                + tax_inclusive (Money)
                + taxes (array)
                    + (object)
                        + rate: 0.21 (number)
                        + taxable (Money)
                        + tax (Money)
                + purchase_price (Money, nullable)
            + discounts (array[CommercialDiscount])
            + created_at: `2017-05-09T11:25:11+00:00` (string, nullable)
            + updated_at: `2017-05-09T11:30:58+00:00` (string, nullable)
            + status: `open` (enum)
                + Members
                    + open
                    + accepted
                    + expired
                    + rejected
                    + closed
            + name: `Webdevelopment` (string)
            + document_template (object)
                + type: `documentTemplate` (string)
                + id: `179e1564-493b-4305-8c54-a34fc80920fc` (string)
            + expiry (object) - returned if user has access to quotation expiry and `includes=expiry` is requested
                + expires_after: `2023-04-05` (string)
                + action_after_expiry (enum[string])
                    + Members
                        + lock
                        + none

### quotations.download [POST /quotations.download]

Download a quotation in a specific format.

+ Request (application/json)

    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)
        + format: `pdf` (enum, required)
            + Members
                + pdf

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + location: `https://cdn.teamleader.eu/file` (string) - A temporary url where the requested file can be downloaded
            + expires: `2018-02-05T16:44:33+00:00` (string) - Expiration time of the temporary download link

### quotations.create [POST /quotations.create]

Create a quotation.

+ Request (application/json)

    + Attributes (object)
        + deal_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac8` (string, required)
        + currency (object)
            + code: `EUR` (Currency, required)
            + exchange_rate: `1.1238` (number)
        + `grouped_lines` (array, optional) - A quotation needs `grouped_lines` and/or `text` to be valid
            + (object)
                + section (object, optional)
                    + title (string, required)
                + line_items (array, required)
                    + (object)
                        + quantity: `3` (number, required)
                        + description: `An awesome product` (string, required)
                        + extended_description: `Some more information about this awesome product` (string, optional) - Uses Markdown formatting
                        + unit_of_measure_id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string, optional, nullable)
                        + unit_price (object, required)
                            + amount: `123.30` (number)
                            + tax: `excluding` (enum, required)
                                + Members
                                    + excluding
                        + tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)
                        + discount (object, optional)
                            + value: 10 (number, required)
                            + type (enum, required)
                                + Members
                                    + percentage - Values between 0 and 100
                        + product_id: `d905ff57-e866-0f59-9d1e-1fd4538bfae1` (string, optional) - This is purely informational and does not affect the quotation besides adding a reference to the product
                        + purchase_price (Money, nullable, optional) - the currency must match the account currency
                        + periodicity (Periodicity, nullable, optional)
        + discounts (array[CommercialDiscount], optional)
        + text: `Quotation text` (string, optional) - Uses Markdown formatting. A quotation needs `grouped_lines` and/or `text` to be valid
        + document_template_id: `179e1564-493b-4305-8c54-a34fc80920fc` (string, optional)
        + expiry (object) - only available if user has access to quotation expiry
            + expires_after: `2023-04-05` (string, nullable)
            + action_after_expiry (enum[string], required)
                + Members
                    + lock
                    + none

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `quotation` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### quotations.send [POST /quotations.send]

Send a quotation.

+ Request (application/json)

    + Attributes (object)
        + quotations: `023a4609-eda4-006c-8d2c-314539ec5d85`, `b42635b7-ccd3-0bfc-9628-e90940694845` (array[string], required) - list of quotation ids you wish to send. These quotations need to come from the same deal.
        + from (object, optional)
            + sender (object, required)
                + type (enum, required)
                    + Members
                        + user
                        + department
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
            + email_address: `info@teamleader.eu` (string, required)
        + recipients (object, required)
            + to (array, required)
                + (object)
                    + customer (object, optional, nullable)
                        + type (enum, required)
                            + Members
                                + company
                                + contact
                        + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
                    + email_address: `info@teamleader.eu` (string, required)
            + cc (array, optional)
                + (object)
                    + customer (object, optional, nullable)
                        + type (enum, required)
                            + Members
                                + company
                                + contact
                        + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
                    + email_address: `info@teamleader.eu` (string, required)
           + bcc (array, optional)
                + (object)
                   + customer (object, optional, nullable)
                       + type (enum, required)
                           + Members
                               + company
                               + contact
                       + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
                   + email_address: `info@teamleader.eu` (string, required)
        + subject: `An offer you cannot refuse` (string, required)
        + content: `Sign your offer here #LINK` (string, required) - the shortcode '#LINK' will be replaced with the cloudsign url
        + attachments: `e76d381a-f7ea-04d1-9a32-14aab27bc1e2` (array[string], optional) - an array of file ids
        + language (Language, required)

+ Response 204

### quotations.update [POST /quotations.update]

Update a quotation.

+ Request (application/json)

    + Attributes (object)
        + id: `5b16f6ee-e302-0079-901b-50c26c4a55b1` (string, required)
        + currency (object)
            + code: `EUR` (Currency, required)
            + exchange_rate: `1.1238` (number)
        + `grouped_lines` (array, optional) - A quotation needs `grouped_lines` and/or `text` to be valid
            + (object)
                + section (object, optional)
                    + title (string, required)
                + line_items (array, required)
                    + (object)
                        + quantity: `3` (number, required)
                        + description: `An awesome product` (string, required)
                        + extended_description: `Some more information about this awesome product` (string, optional) - Uses Markdown formatting
                        + unit_of_measure_id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string, optional, nullable)
                        + unit_price (object, required)
                            + amount: `123.30` (number)
                            + tax: `excluding` (enum, required)
                                + Members
                                    + excluding
                        + tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)
                        + discount (object, optional)
                            + value: 10 (number, required)
                            + type (enum, required)
                                + Members
                                    + percentage - Values between 0 and 100
                        + product_id: `d905ff57-e866-0f59-9d1e-1fd4538bfae1` (string, optional) - This is purely informational and does not affect the quotation besides adding a reference to the product
                        + purchase_price (Money, nullable, optional) - the currency must match the account currency
                        + periodicity (Periodicity, nullable, optional)
        + discounts (array[CommercialDiscount], optional)
        + text: `Quotation text` (string, optional, nullable) - Uses Markdown formatting. A quotation needs `grouped_lines` and/or `text` to be valid
        + document_template_id: `179e1564-493b-4305-8c54-a34fc80920fc` (string, optional)
        + expiry (object) - only available if user has access to quotation expiry
            + expires_after: `2023-04-05` (string, nullable)
            + action_after_expiry (enum[string], required)
                + Members
                    + lock
                    + none

+ Response 204

### quotations.accept [POST /quotations.accept]

Mark a quotation as accepted.

+ Request (application/json)

    + Attributes (object)
        + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string, required)

+ Response 204

### quotations.delete [POST /quotations.delete]

Delete a quotation.

+ Request (application/json)

    + Attributes (object)
        + id: `4e235f27-0af0-40e5-82f3-d32d0aa9edb3` (string, required)

+ Response 204
