## Quotations [/quotations]

A quotation is a sales offer for a specific customer. It is always attached to a deal. Quotations can be signed online via Cloudsign.

*Required scopes: `quotations`*

### quotations.info [GET /quotations.info]

Get a quotation

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `e7a3fe2b-2c75-480f-87b9-121816b5257b` (string)
            + deal (object)
                + type: `deal` (string)
                + id: `53474a7a-f9b2-4dd4-88a8-40ce773c7a64` (string)
            + grouped_lines (array)
                + (object)
                    + section (object)
                        + title (string)
                    + line_items (array)
                        + (object)
                            + product (object, nullable)
                                + type: `product` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                            + quantity: 3 (number)
                            + description: `An awesome product` (string)
                            + extended_description: `Some more information about this awesome product` (string) - Uses Markdown formatting
                            + unit_price (object)
                                + Include Money
                                + tax: `excluding` (enum[string])
                                    + Members
                                        + excluding
                            + tax (object)
                                + rate: 0.21 (number)
                            + tax_rate (object)
                                + type: `taxRate` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449042` (string)
                            + discount (object, nullable)
                                + type: `percentage` (enum[string])
                                    + Members
                                        + percentage
                                + value: 15.00 (number)
                            + total
                                + tax_exclusive (Money)
                                + tax_exclusive_before_discount (Money)
                                + tax_inclusive (Money)
                                + tax_inclusive_before_discount (Money)

### quotations.download [POST /quotations.download]

Download a quotation in a specific format.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)
        + format: `pdf` (enum[string], required)
            + Members
                + pdf

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + location: `https://cdn.teamleader.eu/file` (string) - A temporary url where the requested file can be downloaded
            + expires: `2018-02-05T16:44:33+00:00` (string) - Expiration time of the temporary download link
