## Milestones [/milestones]

Every projects consists of one or more milestones which are limited in time and budget. Budget is however not included in this endpoints (yet).

*Required scopes: `projects`*

### milestones.list [GET /milestones.list]

Get a list of project milestones.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `bbbfe0da-e692-4ee3-9d3d-0716808d6523`,`722e1eb9-53d5-4b8c-9d17-154dcc65c610` (array[string], optional)
            + project_id: `082e6289-30c5-45ad-bcd0-190b02d21e81` (string, optional)
            + status (enum, optional)
                + Members
                    + open
                    + closed
            + due_before: `2017-01-01` (string, optional)
            + due_after: `2017-01-01` (string, optional)
            + term: `coffee` (string, optional) - Searches for a term in title
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + due_on
                + order (enum, optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `due_on`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `cfb4146d-06be-41f1-bb39-aa3c929c71dc` (string)
                + project (object)
                    + type: `project` (string)
                    + id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string)
                + starts_on: `2020-06-15` (string, nullable)
                + due_on: `2020-07-01` (string)
                + name: `Initial setup` (string)
                + responsible_user (object)
                    + type: `user` (string)
                    + id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string)
                + status: `open` (enum)
                    + Members
                        + open
                        + closed
                + `invoicing_method`: `time_and_materials` (enum)
                    + Members
                        + time_and_materials
                        + fixed_price
                        + non_invoiceable
                + depends_on (object, nullable)
                    + type: `milestone` (string)
                    + id: `0488d792-ba9b-059f-bd57-bea75d3f4f4e` (string)
                + dependency_for (array)
                    + (object)
                        + type: `milestone` (string)
                        + id: `b71ff11f-074e-0705-9450-589342af4f4f` (string)
                + actuals (object) - Only accessible for administrators of the project this milestone belongs to
                    + `billable_amount` (Money)
                    + costs (Money)
                    + result (Money) - The billable amount minus the costs, so the profit or loss
                + budget (object) - Only accessible for administrators of the project this milestone belongs to
                    + provided (Money)
                    + spent (Money)
                    + remaining (Money)
                    + allocated (Money, nullable) - The amount of money still expected to be spent. This is null if there is not enough data to calculate
                    + forecasted (Money, nullable) - A prediction of the spent budget upon milestone completion. This is null if there is not enough data to calculate

### milestones.info [GET /milestones.info]

Get details for a single milestone.

+ Request (application/json)

    + Attributes (object)
        + id: `64349fa2-6ca2-4b19-82e6-d3258ceab2d8` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `64349fa2-6ca2-4b19-82e6-d3258ceab2d8` (string)
            + project (object)
                + type: `project` (string)
                + id: `fffaf951-b65a-4cb1-bfb6-4b93e0e60c10` (string)
            + starts_on: `2020-06-15` (string, nullable)
            + due_on: `2020-07-01` (string)
            + name: `Initial setup` (string)
            + description (string)
            + responsible_user (object)
                + type: `user` (string)
                + id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string)
            + status: `open` (enum)
                + Members
                    + open
                    + closed
            + `invoicing_method`: `time_and_materials` (enum)
                + Members
                    + time_and_materials
                    + fixed_price
                    + non_invoiceable
            + depends_on (object, nullable)
                + type: `milestone` (string)
                + id: `0488d792-ba9b-059f-bd57-bea75d3f4f4e` (string)
            + dependency_for (array)
                + (object)
                    + type: `milestone` (string)
                    + id: `b71ff11f-074e-0705-9450-589342af4f4f` (string)
            + actuals (object) - Only accessible for administrators of the project this milestone belongs to
                + `billable_amount` (Money)
                + costs (Money)
                + result (Money) - The billable amount minus the costs, so the profit or loss
            + budget (object) - Only accessible for administrators of the project this milestone belongs to
                + provided (Money)
                + spent (Money)
                + remaining (Money)
                + allocated (Money, nullable) - The amount of money still expected to be spent. This is null if there is not enough data to calculate
                + forecasted (Money, nullable) - A prediction of the spent budget upon milestone completion. This is null if there is not enough data to calculate
            + custom_fields (array[CustomField])

### milestones.create [POST /milestones.create]

Create a new milestone.

+ Request (application/json)

    + Attributes (object)
        + project_id: `1c159f98-4b07-438a-9f42-fb4206b9530d` (string, required)
        + due_on: `2020-08-01` (string, required)
        + starts_on: `2020-06-15` (string, optional)
        + name: `Initial setup` (string, required)
        + description (string, optional)
        + responsible_user_id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string, required)
        + One Of
            + Properties
                + `billing_method` (enum)
                    + Members
                        + `non_invoiceable`
                        + `time_and_materials`
                    + Default
                        + `time_and_materials`
                + budget (Money) - If omitted, the budget will default to zero
            + Properties
                + `billing_method`: `fixed_price` (string, required)
                + price (Money, required)
        + depends_on: `0488d792-ba9b-059f-bd57-bea75d3f4f4e` (string, nullable)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `milestone` (string)
            + id: `51f19f91-6343-4001-a628-3afe45f674ad` (string)

### milestones.update [POST /milestones.update]

Update a milestone.

+ Request (application/json)

    + Attributes (object)
        + id: `67e80ad8-d14f-4510-a2bd-a4c6aa578c37` (string, required)
        + due_on: `2020-08-01` (string, optional)
        + starts_on: `2020-06-15` (string, nullable, optional)
        + name: `Initial setup` (string, optional)
        + description (string, optional)
        + responsible_user_id: `e1240972-6cfc-4549-b49c-edda7568cc48` (string, optional)
        + depends_on: `0488d792-ba9b-059f-bd57-bea75d3f4f4e` (string, nullable)
        + propagate_date_changes: false (boolean, optional)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 204 (application/json)

### milestones.delete [POST /milestones.delete]

Delete a milestone.

+ Request (application/json)

    + Attributes (object)
        + id: `67e80ad8-d14f-4510-a2bd-a4c6aa578c37` (string, required)

+ Response 204