## Project items [/projectItems]

Project items are added to a project and they affect the profitability. This information is only available for users with access to profit on projects.

*Required scopes: `projects`*

### projectItems.list [GET /projectItems.list]

Get a list of project items.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + project_id: `082e6289-30c5-45ad-bcd0-190b02d21e81` (string, optional)
            + type: `tracked_time` (enum[string], optional)
                + Members
                    + tracked_time
                    + external_cost_item
                    + time_tracking_product
            + milestone_id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string, optional)
            + internal_cost_per_unit: null (nullable, optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + occurred_at
                        + milestone_name
                        + unit_cost
                        + unit_price
                        + quantity
                        + cost
                        + price
                + order (enum[string], optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (object)
                    + field: `occurred_at`
                    + order: `desc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `cfb4146d-06be-41f1-bb39-aa3c929c71dc` (string)
                + project (object)
                    + type: `project` (string)
                    + id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string)
                + milestone (object, nullable)
                    + type: `milestone` (string)
                    + id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string)
                + type: `tracked_time` (enum[string])
                    + Members
                        + tracked_time
                        + external_cost_item
                        + time_tracking_product
                + description: `Drafted the document` (string, nullable)
                + occurred_at: `2018-11-26T16:44:33+00:00` (string)
                + participant (object, nullable)
                    + type: `user` (string)
                    + id: `a2d6bc44-2cf6-01c5-9a3c-67cabc1f029b` (string)
                + internal_cost_per_unit (Money, nullable)
                + billable_price_per_unit (Money, nullable)
                + quantity: `3.25` (number)
                + unit: `hour` (string, nullable)
                + total
                    + internal_cost (Money)
                    + billable_price (Money)
                + product (object, nullable)
                    + type: `product` (string)
                    + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                + added_at: `2018-12-04T16:44:33+00:00` (string)
                + updated_at: `2018-12-05T16:44:33+00:00` (string)
        + meta (object)
            + page (Pagination)
            + matches: `120` (number)

### projectItems.info [GET /projectItems.info]

Get details for a single project item.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `8a04371b-2ffb-407b-9b24-d5b5452009c7` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `cfb4146d-06be-41f1-bb39-aa3c929c71dc` (string)
            + project (object)
                + type: `project` (string)
                + id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string)
            + milestone (object, nullable)
                + type: `milestone` (string)
                + id: `944534fb-15f1-4eea-aab1-82a427aa2d0d` (string)
            + type: `tracked_time` (enum[string])
                + Members
                    + tracked_time
                    + external_cost_item
                    + time_tracking_product
            + description: `Drafted the document` (string, nullable)
            + occurred_at: `2018-11-26T16:44:33+00:00` (string)
            + participant (object, nullable)
                + type: `user` (string)
                + id: `a2d6bc44-2cf6-01c5-9a3c-67cabc1f029b` (string)
            + internal_cost_per_unit (Money, nullable)
            + billable_price_per_unit (Money, nullable)
            + quantity: `3.25` (number)
            + unit: `hour` (string, nullable)
            + total
                + internal_cost (Money)
                + billable_price (Money)
            + product (object, nullable)
                + type: `product` (string)
                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
            + added_at: `2018-12-04T16:44:33+00:00` (string)
            + updated_at: `2018-12-05T16:44:33+00:00` (string)

### projectItems.updateCost [POST /projectItems.updateCost]

Update a project item's internal cost.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `cfb4146d-06be-41f1-bb39-aa3c929c71dc` (string, required)
        + internal_cost_per_unit (Money, required, nullable)

+ Response 204 (application/json;charset=utf-8)

### projectItems.updateInternalRate [POST /projectItems.updateInternalRate]

Update the internal rate for a participant for one project, or all projects.
This does not update the global internal rate of the employee. See `users.updateRates`.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + participant_id: `b5094b3f-bb7a-0391-b01b-e709773f3509` (string)
        + project_id: `082e6289-30c5-45ad-bcd0-190b02d21e81` (string, optional) - If there is no specific project id, update for all projects
        + internal_cost (Money, nullable)

+ Response 204 (application/json;charset=utf-8)
