## Timers [/timers]

Timers are an easy way to track time. You can start, stop or resume a timer any time. However, only one timer can run simultaneously per user. Every action will result in the creation or update of a time tracking.

### timers.current [GET /timers.current]

Get the current running timer.

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `2b282dec-ba9d-4faa-9b39-944b99ee5c0a` (string)
            + user (object)
                + type: `user` (string)
                + id: `5443a1b9-7673-4922-921f-1da4ff557783` (string)
            + work_type (object)
                + type: `workType` (string)
                + id: `d02de940-9435-4e35-bc0b-3d17f3d0ea7b` (string)
            + started_at: `2017-04-26T10:01:49+00:00` (string)
            + description: `Timer description` (string)
            + subject (object)
                + type: `milestone` (enum[string])
                    + Members
                        + company
                        + contact
                        + event
                        + todo
                        + milestone
                        + ticket
                + id: `31931bc9-4ae8-4c50-ba8d-9ea88498c1c1` (string)
            + relates_to (array)
                + (object)
                    + type: `company` (enum[string])
                        + Members
                            + company
                            + contact
                            + event
                            + todo
                            + milestone
                            + project
                            + ticket
                    + id: `96a38bbf-24ed-4083-8a5c-20db92aa471e` (string)

### timers.start [POST /timers.start]

Start a new timer.

+ Request (application/json)

    + Attributes (object)
        + work_type_id: `db41328a-7a25-4e85-8fb9-830baacb7f40` (string, optional)
        + started_at: `2017-04-26T10:01:49+00:00` (string, optional) - If not provided, current time will be used
        + description (string, optional)
        + subject (object, optional)
            + type: `milestone` (enum[string], required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + milestone
                    + ticket
            + id: `29ff471c-7d8f-40d5-8c95-9a9cab841e65` (string, required)

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `timer` (string)
            + id: `4ff475b2-f45b-4803-800e-350b9c02aeca` (string)

### timers.stop [POST /timers.stop]

Stop the current timer. This will add a new time tracking in the background.

+ Request (application/json)

    + Attributes (object)
        + ended_at: `2017-04-26T10:01:49+00:00` (string, optional) - If not provided, current time will be used

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `timeTracking` (string)
            + id: `4ff475b2-f45b-4803-800e-350b9c02aeca` (string)

### timers.update [POST /timers.update]

Update the current timer. Only possible if there is a timer running.

+ Request (application/json)

    + Attributes (object)
        + work_type_id: `db41328a-7a25-4e85-8fb9-830baacb7f40` (string, optional, nullable)
        + description: `Timer Description` (string, optional, nullable)
        + subject (object, optional, nullable)
            + type: `milestone` (enum[string], required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + milestone
                    + ticket
            + id: `29ff471c-7d8f-40d5-8c95-9a9cab841e65` (string, required)

+ Response 204
