## Activity Types [/activityTypes]

Activity types identify the different types of events that take place within your organisation. Currently only three activity types are available: tasks, meetings and calls.

### activityTypes.list [GET /activityTypes.list]

Get a list of all activity types.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `7fcf5609-25fe-47e2-97b2-dbd9c817796e`,`366b6100-7005-4b1b-a16a-7e88f445f496` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `9feb5f61-c6dd-4f9d-9b37-2813ada4e343` (string)
                + name (string)
