## Calls [/calls]

### calls.add [POST /calls.add]

Add a new call.

+ Request (application/json)

    + Attributes
        + description: `Description of the call` (string, optional)
        + customer (object, optional)
            + type (enum, required)
                + Members
                    + company
                    + contact
            + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
        + due_date: `2016-02-04T16:00:00+00:00` (string, required)
        + responsible_user_id: `98b2863e-7b01-4232-82f5-ede1f0b9db22` (string, required)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `call` (string)
            + id: `65a35860-dcca-4850-9fd6-47ff08469e0c` (string)

### calls.info [GET /calls.info]

Get information about a call.

+ Request (application/json)

    + Attributes (object)
        + id: `6fac0bf0-e803-424e-af67-76863a3d7d16` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `13` (number)
            + status: `done` (string)
            + completed_at: `2016-02-04T16:44:33+00:00` (string, nullable)
            + outcome (object, nullable)
                + type: `callOutcome` (string)
                + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
            + outcome_summary: `Called, but was not available` (string, nullable)
            + description: `Description of the call` (string, nullable)
            + scheduled_at: `2016-02-04T16:00:00+00:00` (string)
            + responsible_user: (object, nullable)
                + type: `user` (string)
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
            + customer (object, nullable)
                + type: `company` (string)
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
            + optional_contact (object, nullable)
               + type: `contact` (string)
               + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
            + added_at: `2016-02-01T16:44:33+00:00` (string, nullable)