## Custom Fields [/customFieldDefinitions]

Custom fields are used to add additional data/properties to entities within Teamleader.

### customFieldDefinitions.list [POST /customFieldDefinitions.list]

Get a list of all the definitions of custom fields.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `9c64570b-4ec1-4e03-9662-af904f78f7fa`,`aa6d2560-63f9-4b2f-bf96-823dc7c34df7` (array[string], optional)
            + context (enum, optional) - Filters on status
                + Members
                    + contact
                    + company
                    + deal
                    + project
                    + milestone
                    + product
                    + invoice
                    + subscription
                    + ticket
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + label
                        + context
                + order (enum, optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (object)
                    + field: `label`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `74855f4a-2b61-429c-81d8-c79ad3675a76` (string)
                + context: `contact` (enum)
                    + Members
                        + contact
                        + company
                        + deal
                        + project
                        + milestone
                        + product
                        + invoice
                        + subscription
                        + ticket
                + type (enum)
                    + Members
                        + single_line - Single line text
                        + multi_line - Multiline text
                        + single_select - Single selection - has configuration
                        + multi_select - Multiple selection - has configuration
                        + date - Date
                        + money - Money
                        + auto_increment - Automatically incrementing field
                        + integer - Integer
                        + number - Number
                        + boolean - Yes/No
                        + email - Email address
                        + telephone - Phone number
                        + url - URL
                        + company - Company
                        + contact - Contact
                        + product - Product
                        + user - User
                + label (string)
                + group (string)
                + required: false (boolean)
                + configuration (object, optional)
                    + options (array, optional) - Only returned for `single_select` and `multi_select` types
                        + (object)
                            + id: `179e1564-493b-4305-8c54-a34fc80920fc` (string)
                            + value: `foo` (string)
                    + extra_option_allowed: true (boolean)

### customFieldDefinitions.info [POST /customFieldDefinitions.info]

Get info about a specific custom field definition.

+ Request (application/json)

    + Attributes (object)
        + id: `9c64570b-4ec1-4e03-9662-af904f78f7fa` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `57e851e2-3d3b-4523-82f8-fe77df5a5d6c` (string)
            + context: `contact` (enum)
                + Members
                    + contact
                    + company
                    + deal
                    + project
                    + milestone
                    + product
                    + invoice
                    + subscription
                    + ticket
            + type (enum)
                + Members
                    + single_line - Single line text
                    + multi_line - Multiline text
                    + single_select - Single selection - has configuration
                    + multi_select - Multiple selection - has configuration
                    + date - Date
                    + money - Money
                    + auto_increment - Automatically incrementing field
                    + integer - Integer
                    + number - Number
                    + boolean - Yes/No
                    + email - Email address
                    + telephone - Phone number
                    + url - URL
                    + company - Company
                    + contact - Contact
                    + product - Product
                    + user - User
            + label (string)
            + group (string)
            + required: false (boolean)
            + configuration (object, optional)
                + options (array, optional) - Only returned for `single_select` and `multi_select` types
                    + (object)
                        + id: `179e1564-493b-4305-8c54-a34fc80920fc` (string)
                        + value: `foo` (string)
                + extra_option_allowed: true (boolean)
