## Day Off Types [/dayOffTypes]

### dayOffTypes.list [POST /dayOffTypes.list]

Returns a list of day off types for the account

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `data` (array)
            + (object)
                + `id`: `39263c14-9c16-022d-8513-60cf722ab088` (string)
                + `name`: `Sick leave` (string)

