## Day Off Types [/dayOffTypes]

### dayOffTypes.list [POST /dayOffTypes.list]

Returns a list of day off types for the account

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `data` (array)
            + (object)
                + `id`: `39263c14-9c16-022d-8513-60cf722ab088` (string)
                + `name`: `Sick leave` (string)

### dayOffTypes.create [POST /dayOffTypes.create]

Create a new day off type.

+ Request (application/json)
    + Attributes (object)
        + name: `day off type` (string, required)
        + color: `#00B2B2` (string, nullable, optional)
        + date_validity (object, optional)
            + from: `2024-04-04` (string, optional)
            + unit: `2025-05-05` (string, optional)

+ Response 204 (application/json)
