## Departments [/departments]

Departments are used to split quotations and invoices for different legal entities or within one organisation.

*Required scopes: `departments`*

### departments.list [GET /departments.list]

Get a list of departments.

+ Request (application/json)

    + Attributes (object)
        + filter (object)
            + ids: `92296ad0-2d61-4179-b174-9f354ca2157f`,`53635682-c382-4fbf-9fd9-9506ca4fbcdd` (array[string], optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + name
                + order (enum, optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `67c576e7-7e6f-465d-b6ab-a864f6e5e95b` (string)
                + name: `Human Resources` (string)
                + vat_number: `BE0899623035` (string)
                + currency: `EUR` (string)
                + emails (array)
                    + (object)
                        + type: `primary` (enum)
                            + Members
                                + primary
                                + invoicing
                        + email: `info@piedpiper.eu` (string)
                + status: `active` (enum)
                    + Members
                        + active
                        + archived

### departments.info [GET /departments.info]

Get details for a single department.

+ Request (application/json)

    + Attributes (object)
        + id: `92296ad0-2d61-4179-b174-9f354ca2157f` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data  (object)
            + id: `67c576e7-7e6f-465d-b6ab-a864f6e5e95b` (string)
            + name: `Human Resources` (string)
            + vat_number: `BE0899623035` (string)
            + address (Address)
            + emails (array)
                + (object)
                    + type: `primary` (enum)
                        + Members
                            + primary
                            + invoicing
                    + email: `info@piedpiper.eu` (string)
            + telephones (array[object])
                + type: `phone` (enum, required)
                    + Members
                        + phone
                        + fax
                + number: `092980615` (string, required)
            + website: `https://piedpiper.com` (string)
            + currency: `EUR` (string)
            + iban: `BE12123412341234` (string)
            + bic: `BICBANK` (string)
            + fiscal_regime: `RF01` (string, nullable)
            + status: `active` (enum)
                + Members
                    + active
                    + archived
