## Document Templates [/documentTemplates]

### documentTemplates.list [POST /documentTemplates.list]

Get a list of all document templates.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, required)
            + department_id: `a344c251-2494-0013-b433-ccee8e8435e5` (string, required)
            + document_type: `invoice` (enum[string], required)
                + Members
                    + delivery_note
                    + invoice
                    + order
                    + order_confirmation
                    + quotation
                    + timetracking_report
                    + workorder
            + status (array[enum], optional) - Filters on status
                + Members
                    + active - Filters on active
                    + archived - Filters on archived

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `a344c251-2494-0013-b433-ccee8e8435e5` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + document_type: `invoice` (enum[string])
                    + Members
                        + delivery_note
                        + invoice
                        + order
                        + order_confirmation
                        + quotation
                        + timetracking_report
                        + workorder
                + is_default: true (boolean)
                + name: `new logo` (string)
                + status: `active` (enum[string])
                    + Members
                        + active
                        + archived