## Email Tracking [/emailTracking]

### emailTracking.list [POST /emailTracking.list]

Get a list of all email tracking.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, required)
            + subject (object, required)
                + type: `contact` (EmailTrackingSubjectTypes, required)
                + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string, required)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `a344c251-2494-0013-b433-ccee8e8435e5` (string)
                + title: `an email subject` (string)
                + content: `<p>the contents of the received email</p>` (string)
                + subject (object)
                    + type: `contact` (EmailTrackingSubjectTypes)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + added_at: `2016-01-01T00:00:00+00:00` (string)
                + attachments (array)
                    + (object)
                        + `type`: `file` (string)
                        + `id`: `0686d0da-1797-475b-ae94-27191b2eca4d` (string)


### emailTracking.create [POST /emailTracking.create]

Create a new email tracking.

+ Request (application/json)
    + Attributes (object)
        + subject (object, required)
            + type: `contact` (EmailTrackingSubjectTypes, required)
            + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string, required)
        + title: `an email subject` (string, optional)
        + content: `<p>the contents of the received email</p>` (string, required)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `emailTracking` (string)
            + id: `91e99ae3-16f9-01d7-9046-9a501cb2155f` (string)
