## History [/history]

### history.list [GET /history.list]

Retrieve a list of records about an item.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object)
            + about (object, required)
                + type (enum[string])
                     + Members
                         + contact
                         + company
                + id: `6e7fe84d-d4b3-4723-abae-9bc082d8f65a` (string, required)
