## Notes [/notes]

### notes.list [POST /notes.list]

Get a list of all notes.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, required)
            + subject (object, required)
                + type: `contact` (NoteSubjectTypes, required)
                + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string, required)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `a344c251-2494-0013-b433-ccee8e8435e5` (string)
                + content: `new note content` (string)
                + subject (object)
                    + type: `contact` (NoteSubjectTypes)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + added_at: `2016-01-01T00:00:00+00:00` (string)

### notes.create [POST /notes.create]

Add a new create.

+ Request (application/json)
    + Attributes (object)
        + subject (object, required)
            + type: `contact` (NoteSubjectTypes, required)
            + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string, required)
        + content: `new note content` (string, required)
        + notify (array, optional)
            + (object)
                + type: `user` (enum, required)
                    + Members
                        + `user`
                + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string, required)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `note` (string)
            + id: `ee94b4c0-5786-0517-9d26-8dd1e6406f20` (string)