## Notes [/notes]

### notes.list [POST /notes.list]

Get a list of all notes.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, required)
            + subject (object, required)
                + type: `contact` (NoteSubjectTypes, required)
                + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string, required)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `a344c251-2494-0013-b433-ccee8e8435e5` (string)
                + content: `new note content` (string)
                + subject (object)
                    + type: `contact` (NoteSubjectTypes)
                    + id: `36386b05-936e-4cc0-9523-bd20d797ebf5` (string)
                + added_at: `2016-01-01T00:00:00+00:00` (string)