## Teams [/teams]

*Required scopes: `users`*

### teams.list [POST /teams.list]

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `92296ad0-2d61-4179-b174-9f354ca2157f`,`53635682-c382-4fbf-9fd9-9506ca4fbcdd` (array[string], optional)
            + term: `Designers` (string, optional) - Filters on name

+ Response 200 (application/json)
    + Attributes (object)
        + data (array)
            + (object)
                + id: `4b5291aa-2d78-09d2-882c-6c1483f00d88` (string)
                + name: `Designers` (string)
                + `team_lead` (User, nullable) - If the team lead is deactivated or deleted, null is returned
                + members (array[User])