## Users [/users]

Users are co-workers in a Teamleader account.

*Required scopes: `users`*

### users.me [POST /users.me]

Get the current authenticated user.

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
            + account (object)
                + type: `account` (string)
                + id: `0fc55513-7f68-4865-aba0-de5da9e4e43d` (string)
            + first_name: `John` (string)
            + last_name: `Smith` (string)
            + email: `john@teamleader.eu` (string)
            + telephones (array[Telephone])
            + language: `nl-BE` (enum)
                + Members
                    + da-DK
                    + de-DE
                    + en-GB
                    + es-ES
                    + fi-FI
                    + fr-FR
                    + it-IT
                    + nb-NO
                    + nl-BE
                    + nl-NL
                    + pl-PL
                    + pt-PT
                    + sv-SE
                    + tr-TR
            + function: `Sales` (string)
            + time_zone: `Europe/Brussels` (string)
            + preferences (object)
                + invoiceable: true (boolean)
                + historic_time_tracking_limit (object, nullable)
                    + unit (enum)
                        + Members
                            + hour - Hours
                    + value: 24 (number)
                + whitelabeling: true (boolean)

### users.list [POST /users.list]

Get a list of all users.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
            + term: `John` (string, optional) - Filters on first name, last name, email and function
            + status (array[enum], optional) - Filters on status
                + Members
                    + active - Filters on active users
                    + deactivated - Filters on deactivated users
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + first_name
                        + last_name
                        + email
                        + function
                + order (enum, optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (array)
                    + (object)
                        + field: `first_name`
                        + order: `asc`
                    + (object)
                        + field: `last_name`
                        + order: `asc`
        + page (Page, optional)

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
                + account (object)
                    + type: `account` (string)
                    + id: `0fc55513-7f68-4865-aba0-de5da9e4e43d` (string)
                + first_name: `John` (string)
                + last_name: `Smith` (string)
                + email: `john@teamleader.eu` (string)
                + telephones (array[Telephone])
                + language: `nl` (string)
                + function: `Sales` (string)
                + status: `active` (enum)
                    + Members
                        + active
                        + deactivated

### users.info [POST /users.info]

Get details for a single user.

+ Request (application/json)

    + Attributes (object)
        + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string, required)

+ Response 200 (application/json)

    + Attributes
        + data (object)
            + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
            + account (object)
                + type: `account` (string)
                + id: `0fc55513-7f68-4865-aba0-de5da9e4e43d` (string)
            + first_name: `John` (string)
            + last_name: `Smith` (string)
            + email: `john@teamleader.eu` (string)
            + telephones (array[Telephone])
            + language: `nl-BE` (enum)
                + Members
                    + da-DK
                    + de-DE
                    + en-GB
                    + es-ES
                    + fi-FI
                    + fr-FR
                    + it-IT
                    + nb-NO
                    + nl-BE
                    + nl-NL
                    + pl-PL
                    + pt-PT
                    + sv-SE
                    + tr-TR
            + function: `Sales` (string)
            + time_zone: `Europe/Brussels` (string)
            + status: `active` (enum)
                + Members
                    + active
                    + deactivated
