## User Invites [/userInvites]

*Required scopes: `users`*

### userInvites.list [GET /userInvites.list]

Get a list of all user invites that have been sent.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + email: `john@teamleader.eu` (string, optional)

+ Response 200 (application/json)
    + Attributes
        + data (object)
            + id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string)
            + first_name: `john` (string)
            + last_name: `doe` (string)
            + email: `john@teamleader.eu` (string)
            + invited_at: `2017-05-09T11:25:11+00:00` (string)
            + expires_at: `2017-05-12T11:25:11+00:00` (string)

### userInvites.cancel [GET /userInvites.cancel]

Cancel a user invite.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e88131bf-50c4-49d3-8ae3-47e5d9626bf6` (string, required)

+ Response 204

### userInvites.resend [GET /userInvites.resend]

Resend a user invite.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e88131bf-50c4-49d3-8ae3-47e5d9626bf6` (string, required)

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `user-invite` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)
