## Work Orders [/workOrders]

### workOrders.draft [POST /workOrders.draft]

Add a draft work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + customer (object, required)
            + type (enum[string], required)
                + Members
                    + contact
                    + company
            + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
        + starts_at: `2017-05-26T10:01:49+00:00` (string, required)
        + description: `Pipework intervention` (string, optional)
        + department_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac7` (string, optional)
        + layout_id: `a05320f6-b3ef-4ff9-a287-2074a12fb3e9` (string, optional)
        + milestone_id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string, optional)
        + event_id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string, optional)
        + location (Address, optional)
        + distance (object, optional)
            + unit: `km` (enum[string], required)
                + Members
                    + km
            + value: `25.2` (number, required)
        + assignees (array, optional)
            + (object)
                + user_id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string, required)
                + hourly_rate (Money, optional)
                + work_hours (array, optional)
                    + (object)
                        + started_at: `2017-04-26T10:01:49+00:00` (string, required)
                        + duration: 3600 (number, required) - In seconds
                        + description (string, optional)
        + products (array, optional)
            + (object)
                + product_id: `e2314517-3cab-4aa9-8471-450e73449040` (string, required)
                + quantity: `3` (number, optional)
        + custom_fields (array[CustomField], optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `workOrder` (string)
            + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string)

### workOrders.update [POST /workOrders.update]

Update a draft work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + customer (object, optional)
            + type (enum[string], required)
                + Members
                    + contact
                    + company
            + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
        + starts_at: `2017-05-26T10:01:49+00:00` (string, optional)
        + description: `Pipework intervention` (string, optional, nullable)
        + department_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac7` (string, optional, nullable)
        + layout_id: `a05320f6-b3ef-4ff9-a287-2074a12fb3e9` (string, optional, nullable)
        + milestone_id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string, optional, nullable)
        + event_id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string, optional, nullable)
        + location (Address, optional, nullable)
        + distance (object, optional, nullable)
            + unit: `km` (enum[string], required)
                + Members
                    + km
            + value: `25.2` (number, required)
        + assignees (array, optional, nullable)
            + (object)
                + user_id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string, required)
                + hourly_rate (Money, optional)
                + work_hours (array, optional)
                    + (object)
                        + started_at: `2017-04-26T10:01:49+00:00` (string, required)
                        + duration: 3600 (number, required) - In seconds
                        + description (string, optional)
        + products (array, optional, nullable)
            + (object)
                + product_id: `e2314517-3cab-4aa9-8471-450e73449040` (string, required)
                + quantity: `3` (number, optional)
        + custom_fields (array[CustomField], optional, nullable)

+ Response 204

### workOrders.list [GET /workOrders.list]

Get a list of work orders.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + customer (object, optional)
                + type (enum[string], required)
                    + Members
                        + contact
                        + company
                + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
            + state: `draft`, `finalized` (array[string], optional)
                + (enum[string])
                    + draft
                    + finalized
                    + sent
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + starts_at
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `starts_at`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string)
                + state: `draft` (enum[string])
                    + Members
                        + draft
                        + finalized
                        + sent
                + customer (object)
                    + type (enum[string])
                        + Members
                            + contact
                            + company
                    + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string)
                + starts_at: `2017-05-26T10:01:49+00:00` (string)
                + description: `Pipework intervention` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
                + layout (object)
                    + type: `layout` (string)
                    + id: `a05320f6-b3ef-4ff9-a287-2074a12fb3e9` (string)
                + milestone (object)
                    + type: `milestone` (string)
                    + id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string)
                + event (object)
                    + type: `event` (string)
                    + id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string)
                + location (Address)
                + distance (object)
                    + unit: `km` (enum[string])
                        + Members
                            + km
                    + value: `25.2` (number)
                + created_at: `2019-05-09T11:25:11+00:00` (string)
                + updated_at: `2019-05-09T11:30:58+00:00` (string)

### workOrders.info [GET /workOrders.info]

Return info for a single work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string)
            + state: `draft` (enum[string])
                + Members
                    + draft
                    + finalized
                    + sent
            + customer (object)
                + type (enum[string])
                    + Members
                        + contact
                        + company
                + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string)
            + starts_at: `2017-05-26T10:01:49+00:00` (string)
            + description: `Pipework intervention` (string)
            + department (object)
                + type: `department` (string)
                + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
            + layout (object)
                + type: `layout` (string)
                + id: `a05320f6-b3ef-4ff9-a287-2074a12fb3e9` (string)
            + milestone (object)
                + type: `milestone` (string)
                + id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string)
            + event (object)
                + type: `event` (string)
                + id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string)
            + location (Address)
            + distance (object)
                + unit: `km` (enum[string])
                    + Members
                        + km
                + value: `25.2` (number)
            + created_at: `2019-05-09T11:25:11+00:00` (string)
            + updated_at: `2019-05-09T11:30:58+00:00` (string)
            + assignees (array)
                + (object)
                    + user (object)
                        + type: `user` (string)
                        + id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string)
                    + hourly_rate (Money)
                    + work_hours (array)
                        + (object)
                            + started_at: `2017-04-26T10:01:49+00:00` (string)
                            + duration: 3600 (number) - In seconds
                            + description (string)
            + products (array)
                + (object)
                    + product (object)
                        + type: `product` (string)
                        + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                    + quantity: `3` (number)
            + images (array)
                + (object)
                    + id: `a856642a-a476-4b69-8e42-e7d1badb2ce9` (string)
                    + image: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8AAAASUVORK5CYII=` (string) - PNG image, base64 encoded
            + custom_fields (array[CustomField])

### workOrders.attachImage [POST /workOrders.attachImage]

Attach image to a draft work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + image: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8AAAASUVORK5CYII=` (string, required) - PNG image, base64 encoded

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `workOrderImage` (string)
            + id: `a856642a-a476-4b69-8e42-e7d1badb2ce9` (string)

### workOrders.deleteImage [POST /workOrders.deleteImage]

Delete image from a draft work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + image_id: `a856642a-a476-4b69-8e42-e7d1badb2ce9` (string, required)

+ Response 204

### workOrders.sign [POST /workOrders.sign]

Sign a draft work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + signature: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8AAAASUVORK5CYII=` (string, required) - PNG image, base64 encoded

+ Response 204

### workOrders.delete [POST /workOrders.delete]

Delete a draft work order.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)

+ Response 204

### workOrders.finalize [POST /workOrders.finalize]

Finalize a draft work order by generating the PDF.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)

+ Response 204

### workOrders.download [POST /workOrders.download]

Download a work order in a specific format.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + format: `pdf` (enum[string], required)
            + Members
                + pdf

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + location: `https://cdn.teamleader.eu/file` (string) - A temporary url where the requested file can be downloaded
            + expires: `2018-02-05T16:44:33+00:00` (string) - Expiration time of the temporary download link

### workOrders.send [POST /workOrders.send]

Send a finalized work order to the customer.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)

+ Response 204
