## Work Types [/workTypes]

Work types define the type of work for events or time tracking. Hourly rates can be added to work types, so that the work can be billed to a customer.

### workTypes.list [POST /workTypes.list]

Get a list of all work types, sorted alphabetically (on their name).

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `6e342192-76d4-4b26-b1d7-e24df46bf603`,`1652ab6f-ad24-4f5c-a2fc-c6a30693a930` (array[string], optional)
            + term: `design` (string, optional) - Searches in the work type name only
        + page (Page, optional)
        + sort (array, optional)
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `811a5825-96f4-4318-83c3-2840935c6003` (string)
                + name: `Planning` (string)
