## Work Orders [/workOrders]

### workOrders.list [GET /workOrders.list]

Get a list of work orders.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + state (array[enum[string]], optional)
                + Members
                    + draft
                    + finalized
                    + sent
            + starts_after: `2017-03-26T10:01:49+00:00` (string, optional)
            + starts_before: `2017-05-26T10:01:49+00:00` (string, optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + starts_at
                + order (enum[string], optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (object)
                    + field: `starts_at`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string)
                + state (enum[string])
                    + Members
                        + draft
                        + finalized
                        + sent
                + customer (object, nullable)
                    + type (enum[string])
                        + Members
                            + contact
                            + company
                    + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string)
                + starts_at: `2019-05-08T10:12:01+00:00` (string)
                + description: `Pipework intervention` (string, nullable)
                + department (object, nullable)
                    + type: `department` (string)
                    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
                + milestone (object, nullable)
                    + type: `milestone` (string)
                    + id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string)
                + event (object, nullable)
                    + type: `event` (string)
                    + id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string)
                + location (Address, nullable)
                + distance (Distance, nullable)
                + signed: false (boolean)
                + created_at: `2019-05-09T11:25:11+00:00` (string)
                + updated_at: `2019-05-09T11:30:58+00:00` (string)

### workOrders.info [GET /workOrders.info]

Get details for a single work order.

+ Request (application/json)

    + Attributes (object)
        + id: `cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string)
            + state: `draft` (enum[string])
                + Members
                    + draft
                    + finalized
                    + sent
            + customer (object, nullable)
                + type (enum[string])
                    + Members
                        + contact
                        + company
                + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string)
            + starts_at: `2017-05-26T10:01:49+00:00` (string)
            + description: `Pipework intervention` (string, nullable)
            + department (object, nullable)
                + type: `department` (string)
                + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
            + milestone (object, nullable)
                + type: `milestone` (string)
                + id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string)
            + event (object, nullable)
                + type: `event` (string)
                + id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string)
            + location (Address, nullable)
            + distance (Distance, nullable)
            + signed: false (boolean)
            + time (array)
                + (object)
                    + user (object)
                        + type: `user` (string)
                        + id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string)
                    + started_at: `2019-02-27T10:01:49+00:00` (string)
                    + duration: 3600 (number) - In seconds
                    + description: `Replacing pipework` (string)
            + materials (array)
                + (object)
                    + product (object, nullable)
                        + type: `product` (string)
                        + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                    + quantity: 3 (number)
                    + name: `1/2" pipe` (string)
                    + unit_price: 30.20 (number)
            + images (array) - Only included with request parameter `includes=images`.
                + (object)
                    + id: `a856642a-a476-4b69-8e42-e7d1badb2ce9` (string)
                    + location: `https://cdn.teamleader.eu/file` (string) - A temporary URL where the image can be downloaded.
                    + expires: `2019-05-09T13:12:42+00:00` (string) - Expiration time of the temporary download URL.
            + created_at: `2019-05-09T11:25:11+00:00` (string)
            + updated_at: `2019-05-09T11:30:58+00:00` (string)

### workOrders.draft [POST /workOrders.draft]

Add a draft work order.

+ Request (application/json)

    + Attributes (object)
       + customer (object, required)
           + type (enum[string], required)
               + Members
                   + contact
                   + company
           + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
       + starts_at: `2017-05-26T10:01:49+00:00` (string, required)
       + description: `Pipework intervention` (string, optional)
       + department_id: `6a6343fc-fdd8-4bc0-aa69-3a004c710e87` (string, optional)
       + milestone_id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string, optional)
       + event_id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string, optional)
       + location (Address, optional)
       + distance (Distance, optional)
       + time (array, optional)
           + (object)
               + user_id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string, required)
               + started_at: `2019-02-27T10:01:49+00:00` (string, required)
               + duration: 3600 (number, required) - In seconds
               + description: `Replacing pipework` (string, optional)
       + materials (array, optional)
           + (object)
               + quantity: 3 (number, required)
               + One Of
                   + Properties
                       + product_id: `e2314517-3cab-4aa9-8471-450e73449040` (string, required)
                       + name: `1/2" pipe` (string, optional)
                       + unit_price: 30.20 (number, optional)
                   + Properties
                       + name: `1/2" pipe` (string, required)
                       + unit_price: 30.20 (number, required)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `workOrder` (string)
            + id: `7c1d8672-f502-4333-9ea4-7a45add15115` (string)

### workOrders.update [POST /workOrders.update]

Update a draft work order.

+ Request (application/json)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + customer (object, optional)
            + type (enum[string], required)
                + Members
                    + contact
                    + company
            + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string, required)
        + starts_at: `2017-05-26T10:01:49+00:00` (string, optional)
        + description: `Pipework intervention` (string, optional, nullable)
        + department_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac7` (string, optional, nullable)
        + milestone_id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string, optional, nullable)
        + location (Address, optional, nullable)
        + distance (Distance, optional, nullable)
        + time (array, optional)
            + (object)
                + user_id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string, required)
                + started_at: `2017-04-26T10:01:49+00:00` (string, required)
                + duration: 3600 (number, required) - In seconds
                + description (string, optional)
        + materials (array, optional)
            + (object)
                + quantity: `2.2` (number, required)
                + One Of
                    + Properties
                        + product_id: `e2314517-3cab-4aa9-8471-450e73449040` (string, required)
                        + name: `1/2" pipe` (string, optional, nullable)
                        + unit_price: 30.20 (number, optional, nullable)
                    + Properties
                        + name: `1/2" pipe` (string, required)
                        + unit_price: 30.20 (number, required)

+ Response 204

### workOrders.attachImage [POST /workOrders.attachImage]

Attach an image to a draft work order.

+ Request (application/json)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + image: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8AAAASUVORK5CYII=` (string, required) - PNG image, base64 encoded

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + type: `file` (string)
            + id: `a856642a-a476-4b69-8e42-e7d1badb2ce9` (string)

### workOrders.deleteImage [POST /workOrders.deleteImage]

Delete an attached image from a draft work order.

+ Request (application/json)

    + Attributes (object)
       + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
       + file_id: `a856642a-a476-4b69-8e42-e7d1badb2ce9` (string, required)

+ Response 204

### workOrders.delete [POST /workOrders.delete]

Delete a draft work order.

+ Request (application/json)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)

+ Response 204

### workOrders.finalize [POST /workOrders.finalize]

Finalize a draft work order with an optional signature. This will also generate the work order PDF.

+ Request (application/json)

    + Attributes (object)
       + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
       + signature: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8AAAASUVORK5CYII=` (string, optional) - PNG image, base64 encoded

+ Response 204

### workOrders.send [POST /workOrders.send]

Send a finalized work order to the customer.

+ Request (application/json)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)

+ Response 204

### workOrders.download [POST /workOrders.download]

Download a work order in a specific format.

+ Request (application/json)

    + Attributes (object)
        + id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string, required)
        + format: `pdf` (enum[string], required)
            + Members
                + pdf

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + location: `https://cdn.teamleader.eu/file` (string) - A temporary url where the requested file can be downloaded
            + expires: `2018-02-05T16:44:33+00:00` (string) - Expiration time of the temporary download link
