## Addresses [/levelTwoAreas]

We provide a set of data which can be used to build addresses.

### levelTwoAreas.list [GET /levelTwoAreas.list]

Get a list of level two areas (which correspond to provinces, departments or states in most countries).

+ Request (application/json)

    + Attributes (object)
        + country: `BE` (string, required)
        + language: `nl` (string, optional) - if not passed, the name is returned in the primary language of the country

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string)
                + name: `West-Vlaanderen` (string)
                + country: `BE` (string)
