## Companies [/companies]

Companies are legal entities, usually linked to a VAT and/or local business number.

### companies.list [GET /companies.list]

Get a list of companies.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + email (object, optional)
                + type: `primary` (enum[string], required)
                    + Members
                         + primary
                + email: `info@piedpiper.eu` (string, required)
            + ids: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
            + term: `Acme` (string, optional) - Filters on name, vat number, emails and telephones
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + added_at
                + order (enum[string], optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `added_at`
                    + order: `desc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `96a38bbf-24ed-4083-8a5c-20db92aa471e` (string)
                + name: `Pied Piper` (string)
                + business_type (object)
                    + type: `businessType` (string)
                    + id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string)
                + vat_number: `BE0899623035` (string)
                + local_business_number: `63326426` (string)
                + emails (array)
                    + (object)
                        + type: `primary` (enum[string])
                            + Members
                                + primary
                                + invoicing
                        + email: `info@piedpiper.eu` (string)
                + telephones (array[CompanyTelephone])
                + website: `https://piedpiper.com` (string)
                + address (Address)
                + iban: `BE12123412341234` (string)
                + bic: `BICBANK` (string)
                + language: `nl` (string)
                + responsible_user (object)
                    + type: `user` (string)
                    + id: `9b99d8f8-183b-4c7b-8354-9b98b47a192e` (string)
                + added_at: `2016-02-04T16:44:33+00:00` (string)
                + updated_at: `2016-02-05T16:44:33+00:00` (string)

### companies.info [GET /companies.info]

Get details for a single company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e8d31ae7-8258-4fcd-9b2d-78f41b0aa5d5` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `e8d31ae7-8258-4fcd-9b2d-78f41b0aa5d5` (string)
            + name: `Pied Piper` (string)
            + business_type (object)
                + type: `businessType` (string)
                + id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string)
            + vat_number: `BE0899623035` (string)
            + local_business_number: `63326426` (string)
            + emails (array)
                + (object)
                    + type: `primary` (enum[string])
                        + Members
                            + primary
                            + invoicing
                    + email: `info@piedpiper.eu` (string)
            + telephones (array[CompanyTelephone])
            + website: `https://piedpiper.com` (string)
            + addresses (array)
                + (object)
                    + type: `primary` (enum[string])
                        + Members
                            + primary
                            + invoicing
                            + delivery
                            + visiting
                    + address (Addressee)
            + iban: `BE12123412341234` (string)
            + bic: `BICBANK` (string)
            + language: `nl` (string)
            + responsible_user (object)
                + type: `user`
                + id: `7ba98a20-5e2b-4b46-81b9-a3364432d4f0` (string)
            + remarks: `First contact at expo` (string)
            + added_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)

### companies.add [POST /companies.add]

Add a new company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + name: `Pied Piper` (string, required)
        + business_type_id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string, optional)
        + vat_number: `BE0899623035` (string, optional)
        + local_business_number: `63326426` (string, optional)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                + email: `info@piedpiper.eu` (string, required)
        + telephones (array[CompanyTelephone], optional)
        + website: `http://example.com` (string, optional)
        + addresses (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (Addressee, required) - Primary addresses can not contain an addressee
        + iban: `BE12 1234 1234 1234` (string)
        + bic: `BICBANK` (string, optional)
        + language: `en` (string, optional)
        + responsible_user_id: `2b12bd5d-d2d9-43ac-8755-36a1e00bd67f` (string, optional)
        + remarks: `Met at expo` (string, optional)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `company` (string)
            + id: `4784189d-610b-4488-b3a5-5f324f752417` (string)

### companies.update [POST /companies.update]

Update a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `4784189d-610b-4488-b3a5-5f324f752417` (string, required)
        + name: `Pied Piper` (string, optional)
        + business_type_id: `fd48d4a3-b9dc-4eac-8071-5889c9f21e5d` (string, optional, nullable)
        + vat_number: `BE0899623035` (string, optional, nullable)
        + local_business_number: `63326426` (string, optional, nullable)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                + email: `info@piedpiper.eu` (string, required)
        + telephones (array[CompanyTelephone], optional)
        + website: `http://example.com` (string, optional)
        + addresses (array, optional)
            + (object)
                + type: `primary` (enum[string], required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (Addressee, required) - Primary addresses can not contain an addressee
        + iban: `BE12 1234 1234 1234` (string, optional, nullable)
        + bic: `BICBANK` (string, optional, nullable)
        + language: `en` (string, optional, nullable)
        + responsible_user_id: `0ea94804-401d-4dbd-a577-c2d60998f798` (string, optional, nullable)
        + remarks: `Met at expo` (string, optional, nullable)

+ Response 204

### companies.delete [POST /companies.delete]

Delete a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `f3d67f3e-b8a9-45e8-99b1-17a3b14de8a6` (string, required)

+ Response 204

### companies.tag [POST /companies.tag]

Add a new or existing tag to a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `cadd94ba-a41e-4eb4-a46e-39a7f6f96070` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204
