## Companies [/companies]

### companies.list [GET /companies.list]

Get a list of companies.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `9aa13f8d-145a-448e-a332-cb4e0dfbad69`,`fdd4b1a8-a76b-43c1-9d89-e1ceb8fb669a` (array[string], optional)
            + tag: `upsell` (string, optional)
            + updated_after: `2017-04-26T10:01:49+00:00` (string, optional)
            + term: `teamleader` (string, optional)
            + telephone: `092980615` (string, optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + added_at
                + order (enum[string], optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `added_at`
                    + order: `desc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `96a38bbf-24ed-4083-8a5c-20db92aa471e` (string)
                + name: `Pied Piper` (string)
                + business_type: `NV` (string)
                + vat_number: `BE0899623035` (string)
                + local_business_number: `63326426` (string)
                + email: `info@piedpiper.eu` (string)
                + invoice_email: `invoicing@example.com` (string)
                + telephones (array[Telephone])
                + website: `https://piedpiper.com` (string)
                + avatar (string)
                + address (Address)
                + iban: `BE12123412341234` (string)
                + bic: `BICBANK` (string)
                + language: `nl` (string)
                + responsible_user (object)
                    + type: `user` (string)
                    + id: `9b99d8f8-183b-4c7b-8354-9b98b47a192e` (string)
                + tags: tag1, tag2 (array[string])
                + custom_fields (array)
                    + (object)
                        + field (object)
                            + type: `customField`
                            + id: `89d6faed-1cf1-4143-8d9b-24c1baf741fb` (string)
                        + value
                + added_at: `2016-02-04T16:44:33+00:00` (string)
                + updated_at: `2016-02-05T16:44:33+00:00` (string)

### companies.info [GET /companies.info]

Get details for a single company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e8d31ae7-8258-4fcd-9b2d-78f41b0aa5d5 (string)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `c5685b0f-87b8-456f-8d9e-a5866814c47a` (string)
            + name: `Pied Piper` (string)
            + business_type: `NV` (string)
            + vat_number: `BE0899623035` (string)
            + local_business_number: `63326426` (string)
            + email: `info@piedpiper.eu` (string)
            + invoice_email: `invoicing@example.com` (string)
            + telephones (array[Telephone])
            + website: `https://piedpiper.com` (string)
            + avatar (string)
            + address (Address)
            + delivery_address (Addressee)
            + visiting_address (Addressee)
            + invoice_address (Addressee)
            + iban: `BE12123412341234` (string)
            + bic: `BICBANK` (string)
            + language: `nl` (string)
            + responsible_user (object)
                + type: `user`
                + id: `7ba98a20-5e2b-4b46-81b9-a3364432d4f0` (string)
            + remarks: `First contact at expo` (string)
            + tags: tag1, tag2 (array[string])
            + custom_fields (array)
                + (object)
                    + field (object)
                        + type: `customField`
                        + id: `2d695501-0498-49ae-b088-ab9b41ea8aae` (string)
                    + value: `092980616`
            + added_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)

### companies.add [POST /companies.create]

Add a new company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + name: `Pied Piper` (string, required)
        + business_type: `NV` (string, optional)
        + vat_number: `BE0899623035` (string, optional)
        + local_business_number: `63326426` (string, optional)
        + email: `john@example.com` (string, required)
        + invoice_email: `invoicing@example.com` (string, optional)
        + telephones (array[Telephone], optional)
        + website: `http://example.com` (string, optional)
        + address (Address, optional)
        + delivery_address (Addressee, optional)
        + visiting_address (Addressee, optional)
        + invoice_address (Addressee, optional)
        + iban: `BE12 1234 1234 1234` (string)
        + bic: `BICBANK` (string, optional)
        + language: `en` (string, optional)
        + responsible_user_id: `2b12bd5d-d2d9-43ac-8755-36a1e00bd67f` (string, optional)
        + remarks: `Met at expo` (string, optional)
        + tags: expo, upsell (array[string], optional)
        + custom_fields (array, optional)
            + (object)
                + field_id: `23099afb-b944-48ea-898d-d79269b5ba0e` (string, required)
                + value (required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `company` (string)
            + id: `4784189d-610b-4488-b3a5-5f324f752417` (string)

### companies.update [POST /companies.update]

Update a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `e7dff0b5-ec37-4fcd-b574-1c88c3362d93` (string, required)
        + name: `Pied Piper` (string, optional)
        + business_type: `NV` (string, optional) - containing the company type (eg NV, BVBA,..)
        + vat_number: `BE0899623035` (string, optional)
        + local_business_number: `63326426` (string, optional) - the local business number (KVK in the Netherlands)
        + email: `john@example.com` (string, optional) - The email address of the new contact
        + invoice_email: `invoicing@example.com` (string, optional)
        + telephones (array[Telephone], optional)
        + website: `http://example.com` (string, optional)
        + address (Address, optional)
        + delivery_address (Addressee, optional)
        + visiting_address (Addressee, optional)
        + invoice_address (Addressee, optional)
        + iban: `BE12 1234 1234 1234` (string)
        + bic: `BICBANK` (string, optional)
        + language: `en` (string, optional)
        + responsible_user_id: `0ea94804-401d-4dbd-a577-c2d60998f798` (string, optional)
        + remarks: `Met at expo` (string, optional)
        + tags: expo, upsell (array[string], optional)
        + custom_fields (array, optional)
            + (object)
                + field_id: `afcfb4ac-01b6-4a59-89a7-61f528820961` (string, required)
                + value (required)

+ Response 204

### companies.delete [POST /companies.delete]

Delete a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `f3d67f3e-b8a9-45e8-99b1-17a3b14de8a6` (string, required)

+ Response 204

### companies.tag [POST /companies.tag]

Add a new or existing tag to a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `cadd94ba-a41e-4eb4-a46e-39a7f6f96070` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204

### companies.untag [POST /companies.untag]

Remove a tag from a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `518d2e5e-99bc-4c66-8509-78e6820a1418` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204
