## Contacts [/contacts]

Contacts are physical entities who are added to your CRM database. Contacts might be linked to one or more companies.

*Required scopes: `contacts`*

### contacts.list [GET /contacts.list]

Get a list of contacts.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + email (object, optional)
                + type: `primary` (enum, required)
                    + Members
                         + primary
                + email: `info@piedpiper.eu` (string, required)
            + ids: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
            + company_id: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5` (string, optional)
            + term: `James` (string, optional) - Filters on first_name, last_name, email and telephone
            + updated_since: `2016-02-04T16:44:33+00:00` (string, optional)
            + tags: `expo`,`prospect` (array[string], optional) - Filters on contacts coupled to all given tags
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + added_at - Sorts on added_at
                        + name - Sorts alphabetically on last_name and first_name
                        + updated_at - Sorts on updated_at
                + order (enum, optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2a39e420-3ba3-4384-8024-fa702ef99c9f` (string)
                + first_name: `Erlich` (string)
                + last_name: `Bachman` (string)
                + salutation: `Mr` (string)
                + emails (array)
                    + (object)
                        + type: `primary` (enum)
                            + Members
                                + primary
                        + email: `info@piedpiper.eu` (string)
                + telephones (array[Telephone])
                + website: `https://piedpiper.com` (string)
                + primary_address (AddressResponse)
                + gender: `male` (enum)
                    + Members
                        + male
                        + female
                + birthdate: `1987-04-25` (string)
                + iban: `BE12123412341234` (string)
                + bic: `BICBANK` (string)
                + national_identification_number: `86792345-L` (string)
                + language: `en` (string)
                + payment_term (PaymentTerm, nullable)
                + invoicing_preferences (object)
                    + electronic_invoicing_address (string, nullable)
                + tags: prospect, expo (array[string])
                + added_at: `2016-02-04T16:44:33+00:00` (string)
                + updated_at: `2016-02-05T16:44:33+00:00` (string)
                + `web_url`: `https://app.teamleader.eu/contact_detail.php?id=2a39e420-3ba3-4384-8024-fa702ef99c9f` (string)

### contacts.info [GET /contacts.info]

Get details for a single contact.

+ Request (application/json)

    + Attributes (object)
        + id: `cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string)
            + first_name: `Erlich` (string)
            + last_name: `Bachman` (string)
            + salutation: `Mr` (string)
            + vat_number: `BE0899623034` (string, nullable)
            + emails (array)
                + (object)
                    + type: `primary` (enum)
                        + Members
                            + primary
                    + email: `info@piedpiper.eu` (string)
            + telephones (array[Telephone])
            + website: `https://piedpiper.com` (string)
            + addresses (array)
                + (object)
                    + type: `invoicing` (enum)
                        + Members
                            + primary
                            + invoicing
                            + delivery
                            + visiting
                    + address (AddressWithAddresseeResponse) - Primary addresses can not contain an addressee
            + gender: `male` (enum)
                + Members
                    + male
                    + female
            + birthdate: `1987-04-25` (string)
            + iban: `BE12123412341234` (string)
            + bic: `BICBANK` (string)
            + national_identification_number: `00051730-A` (string)
            + companies (array)
                + (object)
                    + position: `CEO` (string)
                    + decision_maker: true (boolean)
                    + company (object)
                        + type: `company` (string)
                        + id: `40157f9d-1322-4f2e-b245-188efdc52cc2` (string)
            + language: `en` (string)
            + payment_term (PaymentTerm, nullable)
            + invoicing_preferences (object)
                + electronic_invoicing_address (string, nullable)
            + remarks: `First contact at expo` (string) - Uses Markdown formatting
            + tags: prospect, expo (array[string])
            + custom_fields (array[CustomField])
            + marketing_mails_consent: false (boolean)
            + added_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)
            + `web_url`: `https://app.teamleader.eu/contact_detail.php?id=cde0bc5f-8602-4e12-b5d3-f03436b54c0d` (string)

### contacts.add [POST /contacts.add]

Add a new contact.

+ Request (application/json)

    + Attributes (object)
        + first_name: `John` (string, optional)
        + last_name: `Smith` (string, required)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum, required)
                    + Members
                        + primary
                + email: `info@piedpiper.eu` (string, required)
        + salutation: `Mr` (string, optional)
        + telephones (array[Telephone], optional)
        + website: `http://example.com` (string, optional)
        + addresses (array, optional)
            + (object)
                + type: `invoicing` (enum, required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (AddressWithAddresseeRequest, required) - Primary addresses can not contain an addressee
        + language: `en` (string, optional)
        + gender: `male` (enum, optional)
            + Members
                + male
                + female
        + birthdate: `1989-08-19` (string, optional)
        + iban: `BE12123412341234` (string, optional)
        + bic: `BICBANK` (string, optional)
        + national_identification_number: `01234567-X` (string)
        + remarks: `Met at expo` (string, optional) - Uses Markdown formatting
        + tags: prospect, expo (array[string], optional)
        + custom_fields (array[CustomFieldValue], optional)
        + marketing_mails_consent: false (boolean, optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `contact` (string)
            + id: `7c1d8672-f502-4333-9ea4-7a45add15115` (string)

### contacts.update [POST /contacts.update]

Update a contact.

+ Request (application/json)

    + Attributes (object)
        + id: `76c9d03c-ec5c-4b21-9fc6-7ffee488b12d` (string, required)
        + first_name: `John` (string, optional, nullable)
        + last_name: `Smith` (string, optional)
        + salutation: `Mr` (string, optional, nullable)
        + emails (array, optional)
            + (object)
                + type: `primary` (enum, required)
                    + Members
                        + primary
                + email: `info@piedpiper.eu` (string, required, nullable)
        + telephones (array[Telephone], optional, nullable)
        + website: `http://example.com` (string, optional, nullable)
        + addresses (array, optional)
            + (object)
                + type: `invoicing` (enum, required)
                    + Members
                        + primary
                        + invoicing
                        + delivery
                        + visiting
                + address (AddressWithAddresseeRequest, required) - Primary addresses can not contain an addressee
        + language: `en` (string, optional)
        + gender: `male` (enum, optional, nullable)
            + Members
                + male
                + female
        + birthdate: `1989-08-19` (string, optional, nullable)
        + iban: `BE12123412341234` (string, optional, nullable)
        + bic: `BICBANK` (string, optional, nullable)
        + national_identification_number: `19346758-T` (string)
        + remarks: `Met at expo` (string, optional, nullable) - Uses Markdown formatting
        + tags: prospect, expo (array[string], optional)
        + custom_fields (array[CustomFieldValue], optional)
        + marketing_mails_consent: false (boolean, optional)

+ Response 204

### contacts.delete [POST /contacts.delete]

Delete a contact.

+ Request (application/json)

    + Attributes (object)
        + id: `4e235f27-0af0-40e5-82f3-d32d0aa9edb3` (string, required)

+ Response 204

### contacts.tag [POST /contacts.tag]

Add a new or existing tag to a contact.

+ Request (application/json)

    + Attributes (object)
        + id: `cadd94ba-a41e-4eb4-a46e-39a7f6f96070` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204

### contacts.untag [POST /contacts.untag]

Remove a tag from a contact.

+ Request (application/json)

    + Attributes (object)
        + id: `518d2e5e-99bc-4c66-8509-78e6820a1418` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204

### contacts.linkToCompany [POST /contacts.linkToCompany]

Link a contact to a company.

+ Request (application/json)

    + Attributes (object)
        + id: `75596038-b9c8-4a37-969d-61059e300a28` (string, required)
        + company_id: `4da20f00-0628-4336-b885-aa90e580dd85` (string, required)
        + position: `CEO` (string, optional)
        + decision_maker: true (boolean, optional)

+ Response 204

### contacts.unlinkFromCompany [POST /contacts.unlinkFromCompany]

Unlink a contact from a company.

+ Request (application/json)

    + Attributes (object)
        + id: `b4b3160a-b55e-4033-bdae-25b6d22949b4` (string, required)
        + company_id: `3f1c8650-4292-4187-bb02-4aa00bbe9632` (string, required)

+ Response 204
