## Settings [/]

### tags.list [GET /tags.list]

Get a list of all tags, sorted alphabetically

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `1f9eb655-8954-4597-8ede-482bec27da7f`,`f238bd4f-8032-4d8b-84f1-5388187599c7` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data : expo, upsell (array[string])

### businessTypes.list [GET /businessTypes.list]

Get the names of business types (legal structures) a company can have within a certain country, sorted alphabetically.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + country: `BE` (string, required)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data: `BVBA`, `NV` (array[string])

### dealPhases.list [GET /dealPhases.list]

Get a list of all phases a deal can go through, sorted by their order in the flow.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `53a7e592-a136-4bae-ae15-517befd3d75d`,`bb50af79-55cd-4be0-8306-e9626c70a90f` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `21efc56e-1ba8-469d-926a-e89502591b47` (string)
            + name: `New` (string)


### dealSources.list [GET /dealSources.list]

Get a list of all deal sources, sorted alphabetically (on description)

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `4bd112da-8a39-47b9-b1e2-8ce339c241a3`,`94bd8c65-72ce-4a43-9cdf-9b75f1966010` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `b18c298b-0e6f-495d-8fcd-31dfecaea741` (string)
            + description: `Referral` (string)


### lostReasons.list [GET /lostReasons.list]

Get a list of all deal sources, sorted alphabetically (on description)

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `5ece67c3-bbc7-431f-8cf2-e9cbdebe0e90`,`74ba701c-0252-4584-8fef-81cc7e0b1262` (array[string], optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `c64247f0-d5b1-46e1-befe-bf85f3fae352` (string)
            + description: `Lost to competitor` (string)
