## Tags [/tags]

### tags.list [GET /tags.list]

Get a list of tags.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + name
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `name`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `ee6fe9fa-bf92-0d25-9d10-f4e34ba1f7d1` (string)
                + name: `Client` (string)
