## Timetracking [/timetracking]

### timetracking.list [GET /timetracking.list]

Get a list of tracked time.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `404c1777-6b61-4368-a388-0301dde8e72a`,`409e3446-96f2-4d9a-b20b-7f7cd055053e` (array[string], optional)
            + user_id: `87982c96-f2fe-4b05-838c-ff42c0525758` (string, optional)
            + topic_id: `ce1287f0-0480-458d-b371-22862d864074` (string, optional)
            + tracked_after: `2017-04-26T10:01:49+00:00` (string, optional)
            + tracked_before: `2017-04-26T10:01:49+00:00` (string, optional)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum[string], required)
                    + Members
                        + started_on
                + order (enum[string], optional)
                    + Members
                        + asc
            + Default
                + (object)
                    + field: `started_on`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `4f4288b2-c21b-4dac-87f6-a97511309079` (string)
                + user (object)
                    + type: `user` (string)
                    + id: `eb1eb8b8-d0cb-4385-b60a-c995953ec6be` (string)
                + topic (object)
                    + type: `topic` (string)
                    + id: `8a146eda-c9af-4b11-b63a-ddac47bb254d` (string)
                + started_on: `2017-04-26` (string)
                + started_at: `2017-04-26T10:01:49+00:00` (string, nullable)
                + ended_at: `2017-04-26T11:01:49+00:00` (string, nullable)
                + duration: 3600 (number) - In seconds
                + description: `Timer description` (string)
                + subject (object)
                    + type: `project` (enum[string])
                        + Members
                            + company
                            + contact
                            + event
                            + todo
                            + project
                            + milestone
                            + ticket
                    + id: `58f5b799-51c4-4eb9-8308-b1aa02e0a873` (string)

### timetracking.info [GET /timetracking.info]

Get information about tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `6caeea11-aa83-4da9-9859-5b62bbf3a476` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `6caeea11-aa83-4da9-9859-5b62bbf3a476` (string)
            + user (object)
                + type: `user` (string)
                + id: `56bc6b39-b722-42f5-9ea7-acea4814d7dd` (string)
            + topic (object)
                + type: `topic` (string)
                + id: `d980dbc6-944e-47fc-bf16-2ed7d5a71889` (string)
            + started_on: `2017-04-26` (string)
            + started_at: `2017-04-26T10:01:49+00:00` (string, nullable)
            + ended_at: `2017-04-26T11:01:49+00:00` (string, nullable)
            + duration: 3600 (number) - In seconds
            + description: `Timer description` (string)
            + subject (object)
                + type: `project` (enum[string])
                    + Members
                        + company
                        + contact
                        + event
                        + todo
                        + project
                        + milestone
                        + ticket
                + id: `5883723a-b5aa-4c9d-a02b-ec0dd25f6ca2` (string)

### timetracking.current [GET /timetracking.current]

Get the current timetracking timer.

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `2b282dec-ba9d-4faa-9b39-944b99ee5c0a` (string)
            + user (object)
                + type: `user` (string)
                + id: `5443a1b9-7673-4922-921f-1da4ff557783` (string)
            + topic (object)
                + type: `topic` (string)
                + id: `d02de940-9435-4e35-bc0b-3d17f3d0ea7b` (string)
            + started_at: `2017-04-26T10:01:49+00:00` (string)
            + description: `Timer description` (string)
            + subject (object)
                + type: `project` (enum[string])
                    + Members
                        + company
                        + contact
                        + event
                        + todo
                        + project
                        + milestone
                        + ticket
                + id: `31931bc9-4ae8-4c50-ba8d-9ea88498c1c1` (string)

### timetracking.start [POST /timetracking.start]

Start a new timetracking timer.

+ Request (application/json)

    + Attributes (object)
        + topic_id: `db41328a-7a25-4e85-8fb9-830baacb7f40` (string, optional)
        + started_at: `2017-04-26T10:01:49+00:00` (string, optional) - If not provided, current time will be used
        + description (string, optional)
        + subject (object, optional)
            + type: `project` (enum[string], required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + project
                    + milestone
                    + ticket
            + id: `29ff471c-7d8f-40d5-8c95-9a9cab841e65` (string, required)

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `timetracking` (string)
            + id: `4ff475b2-f45b-4803-800e-350b9c02aeca` (string)

### timetracking.stop [POST /timetracking.stop]

Stop the current timetracking timer.

+ Request (application/json)

    + Attributes (object)
        + ended_at: `2017-04-26T10:01:49+00:00` (string, optional) - If not provided, current time will be used

+ Response 204 (application/json)

### timetracking.resume [POST /timetracking.resume]

Start a new timer based on previously tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `06dfa08a-b769-4005-a912-45ab885c5737` (string, required)
        + started_at: `2017-04-26T10:01:49+00:00` (string, optional) - If not provided, current time will be used

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `timetracking` (string)
            + id: `f01adf4a-bb9b-45de-b231-615cd0e941de` (string)

### timetracking.add [POST /timetracking.add]

Add tracked time.

+ Request (application/json)

    + Attributes (object)
        + topic_id: `2175597d-484e-4a1c-a781-cbc3d9f893ba` (string, optional)
        + One Of
            + started_on: `2017-04-26` (string, required)
            + started_at: `2017-04-26T10:01:49+00:00` (string, required)
        + One Of
            + ended_at: `2017-04-26T11:01:49+00:00` (string, required)
            + duration: 3600 (number, required) - In seconds
        + description (string, optional)
        + subject (object, optional)
            + type: `project` (enum[string], required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + project
                    + milestone
                    + ticket
            + id: `b40ea20d-4ae5-4a56-be12-03766ecaefae` (string, required)

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `timetracking` (string)
            + id: `6f052357-142e-499e-a647-36b55ecf447c` (string)

### timetracking.update [POST /timetracking.update]

Update tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `66621f54-3d0d-420f-8d4b-ddd7fc473bf2` (string, required)
        + topic_id: `a12f4289-3580-4780-bb6d-b4e9f84f80ad` (string, optional)
        + One Of
            + started_on: `2017-04-26` (string, optional)
            + started_at: `2017-04-26T10:01:49+00:00` (string, optional)
        + One Of
            + ended_at: `2017-04-26T11:01:49+00:00` (string, optional)
            + duration: 3600 (number, optional) - In seconds
        + description (string, optional)
        + subject (object, optional)
            + type: `project` (enum[string], required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + project
                    + milestone
                    + ticket
            + id: `88f14220-55d3-4ca6-802b-425e2f53c850` (string, required)

+ Response 204

### timetracking.delete [POST /timetracking.delete]

Delete tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `903b25ad-64b8-4633-9e93-d69f1268b496` (string, required)

+ Response 204
