## Tasks [/tasks]

### tasks.list [GET /tasks.list]

Get a list of tasks.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `9c475de2-1e99-0328-bc19-271b27e921d8`,`6325b4e5-c6a6-060b-b010-b81892e82fa7` (array[string], optional)
            + user_id: `f29abf48-337d-44b4-aad4-585f5277a456` (string, optional, nullable) - Returns tasks that are assigned to this user or to a team to which this user belongs. When passing `null`, it returns tasks that are unassigned.
            + milestone_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional)
            + completed: true (boolean, optional)
            + due_by: `2019-02-04` (string, optional)
            + due_from: `2019-10-20` (string, optional)
            + term: `website design` (string, optional) - Searches for a term in the title.
            + customer (object, optional)
                + type (enum, required)
                    + Members
                        + company
                        + contact
                + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string, required)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + due_on
                + order (enum, optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (object)
                    + field: `due_on`
                    + order: `asc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
                + title: `Prepare demo` (string)
                + description: `**Important note:** Bring VGA cable` (string, nullable) - Can contain markup (Markdown) and multiple lines
                + completed: false (boolean)
                + completed_at: `2016-02-04T16:44:33+00:00` (string, nullable)
                + due_on: `2016-02-04` (string)
                + estimated_duration (object)
                    + unit (enum)
                        + Members
                            + min - Minutes
                    + value: `60` (number)
                + work_type (object, nullable)
                    + type: `workType` (string)
                    + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
                + assignee (object)
                    + type: `user` (enum)
                        + Members
                            + user
                            + team
                    + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
                + customer (object, nullable)
                    + type: `contact` (enum)
                        + Members
                            + contact
                            + company
                    + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
                + milestone (object, nullable)
                    + type: `milestone` (string)
                    + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
                + deal (object, nullable)
                    + type: `deal` (string)
                    + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
                + project (object, nullable)
                    + type: `project` (string)
                    + id: `bbbb772b-e7ad-06c5-935c-b0f6ef61d6bc` (string)

### tasks.info [GET /tasks.info]

Get information about a task.

+ Request (application/json)

    + Attributes (object)
        + id: `6fac0bf0-e803-424e-af67-76863a3d7d16` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `6fac0bf0-e803-424e-af67-76863a3d7d16` (string)
            + title: `Prepare demo` (string)
            + description: `**Important note:** Bring VGA cable` (string, nullable) - Can contain markup (Markdown) and multiple lines
            + completed: false (boolean)
            + completed_at: `2016-02-04T16:44:33+00:00` (string, nullable)
            + due_on: `2016-02-04` (string)
            + estimated_duration (object)
                + unit (enum)
                    + Members
                        + min - Minutes
                + value: `60` (number)
            + work_type (object, nullable)
                + type: `workType` (string)
                + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
            + assignee (object)
                + type: `user` (enum)
                    + Members
                        + user
                        + team
                + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
            + customer (object, nullable)
                + type: `contact` (enum)
                    + Members
                        + contact
                        + company
                + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
            + milestone (object, nullable)
                + type: `milestone` (string)
                + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
            + deal (object, nullable)
                + type: `deal` (string)
                + id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string)
            + project (object, nullable)
                + type: `project` (string)
                + id: `bbbb772b-e7ad-06c5-935c-b0f6ef61d6bc` (string)
            + custom_fields (array[CustomField])

### tasks.create [POST /tasks.create]

Create a new task.

+ Request (application/json)

    + Attributes (object)
        + title: `Prepare demo` (string, required)
        + description: `**Important note:** Bring VGA cable` (string, optional) - May contain markup (Markdown) and multiple lines
        + due_on: `2016-02-04` (string, required)
        + work_type_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, required)
        + milestone_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional)
        + deal_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional)
        + estimated_duration (object, optional)
            + unit (enum, required)
                + Members
                    + min - Minutes
            + value: `60` (number, required)
        + assignee (object, optional)
            + type: `user` (enum)
                + Members
                    + user
                    + team
            + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
        + customer (object, optional)
            + type: `contact` (enum)
                + Members
                    + contact
                    + company
            + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `task` (string)
            + id: `1759dfc1-7365-4f1b-8d90-d29787a5d29d` (string)

### tasks.update [POST /tasks.update]

Update a task.

+ Request (application/json)

    + Attributes (object)
        + id: `00ed6266-a5bd-4aac-a292-2582017b6400` (string, required)
        + title: `Prepare final demo` (string, optional)
        + description: `**Important note:** Bring HDMI cable` (string, optional, nullable) - May contain markup (Markdown) and multiple lines
        + due_on: `2016-02-04` (string, optional)
        + work_type_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional)
        + milestone_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional, nullable)
        + deal_id: `32665afd-1818-0ed3-9e18-a603a3a21b95` (string, optional, nullable)
        + estimated_duration (object, optional)
            + unit (enum, required)
                + Members
                    + min - Minutes
            + value: `60` (number, required)
        + assignee (object, optional)
            + type: `user` (enum)
                + Members
                    + user
                    + team
            + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
        + customer (object, optional)
            + type: `contact` (enum)
                + Members
                    + contact
                    + company
            + id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 204

### tasks.complete [POST /tasks.complete]

Mark a task as complete.

+ Request (application/json)

    + Attributes (object)
        + id: `46156648-87c6-478d-8aa7-1dc3a00dacab` (string, required)

+ Response 204

### tasks.reopen[POST /tasks.reopen]

Reopen a task that had been marked as complete.

+ Request (application/json)

    + Attributes (object)
        + id: `46156648-87c6-478d-8aa7-1dc3a00dacab` (string, required)

+ Response 204

### tasks.delete [POST /tasks.delete]

Delete a task.

+ Request (application/json)

    + Attributes (object)
        + id: `5f0afd8a-8a40-48a4-bbe6-7d0e9c61bb6d` (string, required)

+ Response 204

### tasks.schedule [POST /tasks.schedule]

Schedule a task in your calendar.

+ Request (application/json)

    + Attributes (object)
        + id: `7c70c54e-6e50-4e6a-b5fd-80234eb535cf` (string, required)
        + starts_at: `2016-02-04T16:00:00+00:00` (string, required)
        + ends_at: `2016-02-04T18:00:00+00:00` (string, required)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `event` (string)
            + id: `d7d2d100-d440-46c2-a4a3-177ad4b2a860` (string)
