## Time Tracking [/timeTracking]

Time tracking allows users to record time spent on tasks or projects and the type of work. You are able to follow-up on the budgets of your projects and eventually you are able to invoice the billable time.

### timeTracking.list [GET /timeTracking.list]

Get a list of tracked time.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + user_id: `87982c96-f2fe-4b05-838c-ff42c0525758` (string, optional)
            + started_after: `2017-04-26T10:01:49+00:00` (string, optional)
            + started_before: `2017-04-26T10:01:49+00:00` (string, optional)
            + ended_after: `2017-04-26T10:01:49+00:00` (string, optional)
            + ended_before: `2017-05-26T10:01:49+00:00` (string, optional)
            + subject (object, optional)
                + type (enum, required)
                    + Members
                        + company
                        + contact
                        + event
                        + todo
                        + milestone
                        + ticket
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + started_on
                + order (enum, optional)
                    + Members
                        + desc
            + Default
                + (object)
                    + field: `started_on`
                    + order: `desc`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `4f4288b2-c21b-4dac-87f6-a97511309079` (string)
                + user (object)
                    + type: `user` (string)
                    + id: `eb1eb8b8-d0cb-4385-b60a-c995953ec6be` (string)
                + work_type (object)
                    + type: `workType` (string)
                    + id: `8a146eda-c9af-4b11-b63a-ddac47bb254d` (string)
                + started_on: `2017-04-26` (string)
                + started_at: `2017-04-26T10:01:49+00:00` (string, nullable)
                + ended_at: `2017-04-26T11:01:49+00:00` (string, nullable)
                + duration: 3600 (number) - In seconds
                + description: `Timer description` (string)
                + subject (object)
                    + type: `milestone` (enum)
                        + Members
                            + company
                            + contact
                            + event
                            + todo
                            + milestone
                            + ticket
                    + id: `58f5b799-51c4-4eb9-8308-b1aa02e0a873` (string)
                + invoiceable: true (boolean)

### timeTracking.info [GET /timeTracking.info]

Get information about tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `6caeea11-aa83-4da9-9859-5b62bbf3a476` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `6caeea11-aa83-4da9-9859-5b62bbf3a476` (string)
            + user (object)
                + type: `user` (string)
                + id: `56bc6b39-b722-42f5-9ea7-acea4814d7dd` (string)
            + work_type (object)
                + type: `workType` (string)
                + id: `d980dbc6-944e-47fc-bf16-2ed7d5a71889` (string)
            + started_on: `2017-04-26` (string)
            + started_at: `2017-04-26T10:01:49+00:00` (string, nullable)
            + ended_at: `2017-04-26T11:01:49+00:00` (string, nullable)
            + duration: 3600 (number) - In seconds
            + description: `Timer description` (string)
            + subject (object)
                + type: `milestone` (enum)
                    + Members
                        + company
                        + contact
                        + event
                        + todo
                        + milestone
                        + ticket
                + id: `5883723a-b5aa-4c9d-a02b-ec0dd25f6ca2` (string)
            + invoiceable: true (boolean)
            + locked: true (boolean)
        + meta (object)
            + can_update: true (boolean)

### timeTracking.add [POST /timeTracking.add]

Add tracked time.

+ Request (application/json)

    Note that the time tracking entry will be split up if the time span passes midnight.

    + Attributes (object)
        + work_type_id: `2175597d-484e-4a1c-a781-cbc3d9f893ba` (string, optional)
        + One Of
            + Properties
                + started_at: `2017-04-26T10:01:49+00:00` (string, required)
                + duration: 3600 (number, required) - In seconds
            + Properties
                + started_at: `2017-04-26T10:01:49+00:00` (string, required)
                + ended_at: `2017-04-26T16:02:00+00:00` (string, required)
        + description (string, optional)
        + subject (object, optional)
            + type: `milestone` (enum, required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + milestone
                    + ticket
            + id: `b40ea20d-4ae5-4a56-be12-03766ecaefae` (string, required)
        + invoiceable: true (boolean, optional)

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `timetracking` (string)
            + id: `6f052357-142e-499e-a647-36b55ecf447c` (string)

### timeTracking.update [POST /timeTracking.update]

Update tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `66621f54-3d0d-420f-8d4b-ddd7fc473bf2` (string, required)
        + work_type_id: `a12f4289-3580-4780-bb6d-b4e9f84f80ad` (string, optional, nullable)
        + One Of
            + Properties
                + started_at: `2017-04-26T10:01:49+00:00` (string, required)
                + duration: 3600 (number, required) - In seconds
        + description (string, optional, nullable)
        + subject (object, optional, nullable)
            + type: `milestone` (enum, required)
                + Members
                    + company
                    + contact
                    + event
                    + todo
                    + milestone
                    + ticket
            + id: `88f14220-55d3-4ca6-802b-425e2f53c850` (string, required)
        + invoiceable: true (boolean, optional)

+ Response 204

### timeTracking.resume [POST /timeTracking.resume]

Start a new timer based on previously tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `06dfa08a-b769-4005-a912-45ab885c5737` (string, required)
        + started_at: `2017-04-26T10:01:49+00:00` (string, optional) - If not provided, current time will be used

+ Response 201

    + Attributes (object)
        + data (object)
            + type: `timer` (string)
            + id: `f01adf4a-bb9b-45de-b231-615cd0e941de` (string)

### timeTracking.delete [POST /timeTracking.delete]

Delete a tracked time.

+ Request (application/json)

    + Attributes (object)
        + id: `6caeea11-aa83-4da9-9859-5b62bbf3a476` (string, required)

+ Response 204
