## Products [/products]

*Required scopes: `products`*

### products.list [GET /products.list]

Get a list of products.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids: `bbbfe0da-e692-4ee3-9d3d-0716808d6523`,`722e1eb9-53d5-4b8c-9d17-154dcc65c610` (array[string], optional)
            + term: `cookies` (string, optional) - Will filter on the name or the code.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2aa4a6a9-9ce8-4851-a9b3-26aea2ea14c4` (string)
                + name: `cookies` (string)
                + description: `dark chocolate` (string)
                + code: `123` (string)
