## Products [/products]

*Required scopes: `products`*

### products.list [POST /products.list]

Get a list of products.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + ids: `bbbfe0da-e692-4ee3-9d3d-0716808d6523`,`722e1eb9-53d5-4b8c-9d17-154dcc65c610` (array[string], optional)
            + term: `cookies` (string, optional) - Will filter on the name or the code.
            + updated_since: `2019-02-05T16:44:33+00:00` (string, optional)

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2aa4a6a9-9ce8-4851-a9b3-26aea2ea14c4` (string)
                + name: `cookies` (string, nullable)
                + description: `dark chocolate` (string, nullable) - The description of the product in Markdown
                + code: `COOK-DARKCHOC-42` (string, nullable)
                + unit (object, nullable)
                    + type: `unitOfMeasure` (string)
                    + id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string)
                + added_at: `2016-02-01T11:25:41+00:00` (string)
                + updated_at: `2016-02-01T11:25:41+00:00` (string)
                + stock (object, optional) - Only available when stock management feature is enabled
                    + amount: 123 (number, nullable)
                + configuration (ProductConfigurationRead, nullable)

### products.info [POST /products.info]

Get details for a single product.

+ Request (application/json)

    + Attributes (object)
        + id: `f8ae61ec-62f3-0538-b028-185c4a5f217f` (string)
        + includes: `suppliers` (string, optional) - Comma-separated list of optional includes

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `f8ae61ec-62f3-0538-b028-185c4a5f217f` (string)
            + name: `cookies` (string, nullable)
            + description: `dark chocolate` (string, nullable) - The description of the product in Markdown
            + code: `COOK-DARKCHOC-42` (string, nullable)
            + purchase_price (Money, nullable, optional) - The purchase price will only be returned if you have access to it
            + selling_price (Money, nullable)
            + unit (object, nullable)
                + type: `unitOfMeasure` (string)
                + id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string)
            + tax (object, nullable)
                + type: `taxRate` (string)
                + id: `df444ced-3129-0916-8f40-07ae5832bf98` (string)
            + suppliers: (array, optional) - Only included with request parameter `includes=suppliers`
                + (object)
                    + supplier (object)
                        + type: `contact` (enum)
                            + Members
                                + company
                                + contact
                        + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                    + purchase_price (Money, nullable)
                    + product_code: `prod-111` (string)
                    + minimum_order_amount: `3` (number)
                    + classification (enum)
                        + Members
                            + primary
                            + secondary
            + custom_fields (array[CustomField])
            + price_list_prices (PriceListPricesRead)
            + product_category (object, nullable)
                + type: `productCategory` (string)
                + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)
            + stock (object, optional) - Only available when stock management feature is enabled
                + amount: 123 (number, nullable)
            + configuration (ProductConfigurationRead, optional)
            + added_at: `2016-02-01T11:25:41+00:00` (string)
            + updated_at: `2016-02-01T11:25:41+00:00` (string)

### products.add [POST /products.add]

Add a new product.

+ Request (application/json)
    + Attributes (object)
        + One Of
            + Properties
                + name: `cookies` (string, required)
                + code: `COOK-DARKCHOC-42` (string, optional)
            + Properties
                + name: `cookies` (string, optional)
                + code: `COOK-DARKCHOC-42` (string, required)
        + description (string, optional) - The description of the product in Markdown
        + purchase_price (Money, optional)
        + selling_price (Money, optional)
        + unit_of_measure_id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string, optional, nullable)
        + price_list_prices (PriceListPricesWrite, optional)
        + stock (object, optional) - Only available when stock management feature is enabled
            + amount: 123 (number, nullable)
        + configuration (ProductConfigurationWrite, nullable)
        + department_id: `af48fe9e-d44c-0eac-8813-8be051b10921` (string, optional)
        + product_category_id: `624ca743-8998-4f8c-add1-c427bb022166` (string, optional)
        + tax_rate_id: `23097774-e51e-0371-9b42-98ef8ca8bbb6` (string, optional)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `product` (string)
            + id: `ee94b4c0-5786-0517-9d26-8dd1e6406f20` (string)

### products.update [POST /products.update]

Update a product.

+ Request (application/json)

    + Attributes (object)
        + id: `71e91f91-b222-033f-8c7e-59bcc1521e3d` (string, required)
        + name: `Hosting` (string, nullable, optional)
        + code: `c0d32` (string, nullable, optional)
        + purchase_price (Money, nullable, optional) - The currency must match the account currency
        + description: `Product used for hosting web solutions` (string, nullable, optional)
        + selling_price (Money, optional)
        + unit_of_measure_id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string, optional, nullable)
        + price_list_prices (PriceListPricesWrite, optional)
        + stock (object, optional) - Only available when stock management feature is enabled
            + amount: 123 (number, nullable)
        + configuration (ProductConfigurationWrite, nullable)
        + department_id: `af48fe9e-d44c-0eac-8813-8be051b10921` (string, optional)
        + product_category_id: `624ca743-8998-4f8c-add1-c427bb022166` (string, optional)
        + tax_rate_id: `23097774-e51e-0371-9b42-98ef8ca8bbb6` (string, optional)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 204

### products.delete [POST /products.delete]

Delete a product.

+ Request (application/json)

    + Attributes (object)
        + id: `71e91f91-b222-033f-8c7e-59bcc1521e3d` (string, required)

+ Response 204
