# Units of Measure [/unitsOfMeasure]

### unitsOfMeasure.list [POST /unitsOfMeasure.list]

Get a list of units of measure.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `data` (array)
            + (object)
                + id: `70af3fdd-b037-0936-ad1a-6d784dd44cf4` (string)
                + name: `kg` (string)
