FORMAT: 1A
HOST: https://api.teamleader.eu

# Teamleader API

:[Introduction](introduction.apib)

:[OAuth2](oauth2.apib)

# Group General

:[Users](./01-general/users.apib)

# Group Invoicing

:[Invoices](./04-invoicing/invoices.apib)
:[Settings](./04-invoicing/settings.apib)

:[Data Structures](datastructures.apib)
