FORMAT: 1A
HOST: https://api.teamleader.eu

# Teamleader API

:[Introduction](introduction.apib)

:[OAuth2](oauth2.apib)

# Group General

:[Departments](./01-general/departments.apib)

:[Users](./01-general/users.apib)

# Group CRM

:[Contacts](./02-crm/contacts.apib)

:[Companies](./02-crm/companies.apib)

:[Business Types](./02-crm/business-types.apib)

:[Quotations](./02-crm/quotations.apib)

# Group Calendar

:[Events](./03-calendar/events.apib)

:[Activity Types](./03-calendar/activity-types.apib)

# Group Invoicing

:[Invoices](./04-invoicing/invoices.apib)

:[Tax Rates](./04-invoicing/tax-rates.apib)

# Group Projects

:[Projects](./05-projects/projects.apib)

:[Milestones](./05-projects/milestones.apib)

# Group Other

:[Migrating](./99-other/migrating.apib)


:[Data Structures](datastructures.apib)
