FORMAT: 1A
HOST: https://api.focus.teamleader.eu

# Teamleader API

:[Introduction](introduction.apib)

:[Authentication](authentication.apib)

:[Sideloading](sideloading.apib)

:[Changes & upgrades](changes.apib)

:[API Roadmap](roadmap.apib)

# Group General

:[Departments](./01-general/departments.apib)

:[Users](./01-general/users.apib)

:[Teams](./01-general/teams.apib)

:[Custom Fields](./01-general/custom-fields.apib)

:[Work Types](./01-general/work-types.apib)

:[Document Templates](./01-general/document-templates.apib)

:[Currencies](./01-general/currencies.apib)

:[Notes](./01-general/notes.apib)

:[Email Tracking](./01-general/email-tracking.apib)

:[Closing Days](./01-general/closing-days.apib)

:[Day Off Types](./01-general/day-off-types.apib)

:[Days Off](./01-general/days-off.apib)

# Group CRM

:[Contacts](./02-crm/contacts.apib)

:[Companies](./02-crm/companies.apib)

:[Business Types](./02-crm/business-types.apib)

:[Tags](./02-crm/tags.apib)

:[Addresses](./02-crm/addresses.apib)

# Group Deals

:[Deals](./03-deals/deals.apib)

:[Deal Pipelines](./03-deals/deal-pipelines.apib)

:[Deal Phases](./03-deals/deal-phases.apib)

:[Deal Sources](./03-deals/deal-sources.apib)

:[Quotations](./03-deals/quotations.apib)

# Group Calendar

:[Meetings](./04-calendar/meetings.apib)

:[Calls](./04-calendar/calls.apib)

:[Call outcomes](./04-calendar/call-outcomes.apib)

:[Events](./04-calendar/events.apib)

:[Activity Types](./04-calendar/activity-types.apib)

# Group Invoicing

:[Invoices](./05-invoicing/invoices.apib)

:[Creditnotes](./05-invoicing/credit-notes.apib)

:[Subscriptions](./05-invoicing/subscriptions.apib)

:[Tax Rates](./05-invoicing/tax-rates.apib)

:[Payment Terms](./05-invoicing/payment-terms.apib)

:[Withholding Tax Rates](./05-invoicing/withholding-tax-rates.apib)

:[Commercial Discounts](./05-invoicing/commercial-discounts.apib)

:[Payment Methods](./05-invoicing/payment-methods.apib)

# Group Products

:[ProductCategories](./06-products/product-categories.apib)

:[Products](./06-products/products.apib)

:[UnitsOfMeasure](./06-products/units-of-measure.apib)

:[PriceLists](./06-products/pricelists.apib)

# Group Legacy Projects

:[Projects](./07-projects/projects.apib)

:[Milestones](./07-projects/milestones.apib)

# Group New Projects

:[Projects](./12-nextgen-projects/projects.apib)

:[Project lines](./12-nextgen-projects/projectLines.apib)

:[Groups](./12-nextgen-projects/projectGroups.apib)

:[Tasks](./12-nextgen-projects/tasks.apib)

:[Materials](./12-nextgen-projects/materials.apib)

# Group Tasks

:[Tasks](./08-tasks/tasks.apib)

# Group Time Tracking

:[Time Tracking](./09-time-tracking/time-tracking.apib)

:[Timers](./09-time-tracking/timers.apib)

# Group Tickets

:[Tickets](./12-tickets/tickets.apib)

:[Ticket Status](./12-tickets/ticket-status.apib)

# Group Files

:[Files](./10-files/files.apib)

# Group Templates

:[Mail Templates](./11-templates/mail-templates.apib)

# Group Other

:[Migrating](./99-other/migrating.apib)

:[Webhooks](./99-other/webhooks.apib)

:[Cloud Platforms](./99-other/cloud-platforms.apib)

:[Accounts](./99-other/accounts.apib)

:[Data Structures](datastructures.apib)
