## Changelog

You can follow our API progress and ongoing proposals via our [API Blueprint GitHub repository](https://github.com/teamleadercrm/api).

Upcoming breaking changes are listed [here](https://github.com/teamleadercrm/api/blob/master/CHANGELOG.md).