## Changes & upgrades

We want to keep this API backwards compatible as long as possible, but at the same time, we need to make changes to it to match our evolving product.

Therefore we assigned a dated version to your API client when it was created.
This version controls the API and webhooks behaviour for your API client.
When we change the API in a backwards-incompatible way, we release a new dated version.
To avoid breaking your code, you stay on your assigned version until you [upgrade your API version](#upgrading-your-api-version).

### Types of changes

We consider the following changes to be backwards-compatible:

- Adding new API endpoints.
- Adding new optional parameters to existing API requests.
- Adding new properties to existing API responses.
- Adding new webhook types.
- Making existing parameters optional.
- Changing the order of properties in existing API responses.
- Fixing (potential) bugs that made an endpoint unusable (HTTP 500 errors).
- (Currently, we also hold ourselves the right to return a different error format, as there is still room for improvement)

We consider the following changes to be backwards-incompatible:

- Renaming or removing an endpoint.
- Renaming or removing a parameter of API requests.
- Renaming or removing a property of API responses.
- Changing the format of a parameter of API responses (eg. integer to float)
- Making validation of a parameter more strict (eg. making it required)
- Returning a different HTTP status code.

:[Additions](changes-backwards-compatible.apib)

<a name="upgrading-your-api-version"></a>
### Upgrading your API version

This documentation only reflects the latest version of the API.
If you need to make changes to your client or you want to make use of the latest feature, you might need to upgrade your API version.

You can find your current API version, in the `X-Api-Version` header on any API response.
The current latest version is **2021-09-01**.

After checking the API [changelog](#changelog) to see which endpoints work differently, you can upgrade your API version:

Send an `X-Api-Version` header containing the identifier of a version (newer than your current version) with your requests.

_This will only affect the version for those API calls and won't affect any other calls done by your client._

:[Changes & upgrades](changes-backwards-incompatible.apib)

### Stay informed

You can follow our API progress and ongoing proposals via our [API Blueprint GitHub repository](https://github.com/teamleadercrm/api).
