<a name="additions"></a>
### Additions

We list all backwards-compatible additions here. These are currently available in all published versions.
(There is also a [list of backward-incompatible upgrades](#changelog) available, but those only apply if you [upgrade your API version](#upgrading-your-api-version).)

#### Latest

#### March 2019
