# Data Structures

## Telephone (object)
+ type: `phone` (enum[string], required)
    + Members
        + phone
        + mobile
        + fax
+ number: `092980615` (string, required)

## CompanyTelephone (object)
+ type: `phone` (enum[string], required)
    + Members
        + phone
        + fax
+ number: `092980615` (string, required)

## Address (object)
+ line_1: `Dok Noord 3A 101` (string, required, nullable)
+ postal_code: `9000` (string, required, nullable)
+ city: `Ghent` (string, required, nullable)
+ country: `BE` (string, required)

## Addressee (object)
+ addressee: `Teamleader HQ` (string, optional)
+ Include Address

## Money (object)
+ amount: `123.30` (number, required)
+ currency: `EUR` (enum[string], required)
    + Members
        + BAM
        + CAD
        + CHF
        + CLP
        + CNY
        + COP
        + CZK
        + DKK
        + EUR
        + GBP
        + INR
        + ISK
        + JPY
        + MAD
        + MXN
        + NOK
        + PEN
        + PLN
        + RON
        + SEK
        + TRY
        + USD
        + ZAR

## Page
+ size: `20` (number, optional)
    + Default: `20`
+ number: `1` (number, optional)
    + Default: `1`

## Pagination
+ size: `10` (number)
+ number: `2` (number)

## PaymentTerm  (object)
+ type (enum[string])
    + Members
        + cash - Direct payment, often cash
        + end_of_month - End of the month of Xth day after the invoice date
        + after_invoice_date - X days after invoice date
+ days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.

## CustomField (object)
+ definition (object)
    + type: `customFieldDefinition` (string)
    + id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)
+ One Of
    + value: `092980616` (string)
    + value: `123` (number) - For integer, number and auto-increment fields
    + value: `foo`,`bar` (array[string]) - For multiple selection fields
    + value: true (boolean) - For Yes/No fields
    + value (object) - For related Teamleader objects
        + type: `company` (enum[string])
            + Members
                + company
                + contact
                + product
                + user
        + id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)

## CustomFieldValue (object)
+ id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)
+ One Of
    + value: `092980616` (string)
    + value: `123` (number) - For integer, number, money and auto-increment fields
    + value: `foo`,`bar` (array[string]) - For multiple selection fields
    + value: true (boolean) - For Yes/No fields
    + value (object) - For related Teamleader objects
        + type: `company` (enum[string])
            + Members
                + company
                + contact
                + product
                + user
        + id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)

## WebHook (object)
+ url: `https://example.com` (string, required) - Your webhook URL
+ types (array[enum[string]], required) - Array of event types that fire the webhook
    + Members
        + account.deactivated
        + account.deleted
        + company.added
        + company.deleted
        + company.updated
        + contact.added
        + contact.deleted
        + contact.linkedToCompany
        + contact.unlinkedFromCompany
        + contact.updated
        + deal.created
        + deal.deleted
        + deal.lost
        + deal.moved
        + deal.won
        + invoice.booked
        + invoice.deleted
        + invoice.drafted
        + invoice.paymentRegistered
        + invoice.paymentRemoved
        + invoice.sent
        + invoice.updated
        + milestone.created
        + milestone.updated
        + project.created
        + project.deleted
        + project.updated
        + timeTracking.added
        + timeTracking.deleted
        + timeTracking.updated
        + user.deactivated

## WorkOrderInfo (object)
+ id: `4afb0a9c-91c6-49ed-a2e5-ce7c1e3a87fb` (string)
+ customer (object)
    + type (enum[string])
        + Members
            + contact
            + company
    + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string)
+ datetime: `2017-05-26T10:01:49+00:00` (string)
+ description (string)
+ department (object)
    + type: `department` (string)
    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
+ layout (object)
    + type: `layout` (string)
    + id: `a05320f6-b3ef-4ff9-a287-2074a12fb3e9` (string)
+ milestone (object)
    + type: `milestone` (string)
    + id: `e94c1363-3426-46a4-921d-fce03f39bbd5` (string)
+ event (object)
    + type: `event` (string)
    + id: `9fc14045-5c6c-4ba8-8672-42ea3f26aa63` (string)
+ intervention_address (object)
    + Include Address
    + customer (object)
        + type (enum[string])
            + Members
                + contact
                + company
        + id: `09e5d75f-f817-4872-9723-57fbb8ff710d` (string)
+ distance: `25.2` (number) - Distance in kilometres (km)

## WorkOrderInfoDetail (object)
+ Include WorkOrderInfo
+ users (array)
    + (object)
        + user (object)
            + type: `user` (string)
            + id: `4ec55a8c-2d80-472a-a9c2-5ff5ee7eac6a` (string)
        + hourly_rate: `65` (number)
        + work_hours (array)
            + (object)
                + One Of
                    + Properties
                        + started_at: `2017-04-26T10:01:49+00:00` (string)
                        + duration: 3600 (number) - In seconds
                    + Properties
                        + started_at: `2017-04-26T10:01:49+00:00` (string)
                        + ended_at: `2017-04-26T16:02:00+00:00` (string)
                + description (string)
+ line_items (array)
    + (object)
        + product (object)
            + type: `product` (string)
            + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
        + quantity: `3` (number)
        + description: `An awesome product` (string)
        + unit_price (object)
            + Include Money
            + tax: `excluding` (enum[string])
                + Members
                    + excluding
        + tax (object)
            + rate: `0.21` (number)
+ custom_fields (array[CustomField])
