# Data Structures

## Telephone (object)
+ type: `phone` (enum, required)
    + Members
        + phone
        + mobile
        + fax
+ number: `092980615` (string, required)

## CompanyTelephone (object)
+ type: `phone` (enum, required)
    + Members
        + phone
        + fax
+ number: `092980615` (string, required)

## AddressRequest (object)
+ line_1: `Dok Noord 3A 101` (string, required, nullable)
+ postal_code: `9000` (string, required, nullable)
+ city: `Ghent` (string, required, nullable)
+ country: `BE` (string, required)
+ area_level_two_id: `db232cf8-ad4a-024b-941f-15a7a74f0fd2`

## AddressResponse (object)
+ line_1: `Dok Noord 3A 101` (string, nullable)
+ postal_code: `9000` (string, nullable)
+ city: `Ghent` (string, nullable)
+ country: `BE` (string)
+ area_level_two (object, nullable)
    + type: `area_level_two` (string)
    + id: `db232cf8-ad4a-024b-941f-15a7a74f0fd2` (string)

## AddressWithAddresseeRequest (object)
+ addressee: `Teamleader HQ` (string, optional)
+ Include AddressRequest

## AddressWithAddresseeResponse (object)
+ addressee: `Teamleader HQ` (string, optional)
+ Include AddressResponse

## Currency (enum)
+ BAM
+ CAD
+ CHF
+ CLP
+ CNY
+ COP
+ CZK
+ DKK
+ EUR
+ GBP
+ INR
+ ISK
+ JPY
+ MAD
+ MXN
+ NOK
+ PEN
+ PLN
+ RON
+ SEK
+ TRY
+ USD
+ ZAR

## Money (object)
+ amount: `123.30` (number, required)
+ currency: `EUR` (Currency, required)

## Page
+ size: `20` (number, optional)
    + Default: `20`
+ number: `1` (number, optional)
    + Default: `1`

## Pagination
+ size: `10` (number)
+ number: `2` (number)

## PaymentTerm  (object)
+ type (enum)
    + Members
        + cash - Direct payment, often cash
        + end_of_month - End of the month of Xth day after the invoice date
        + after_invoice_date - X days after invoice date
+ days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.

## CustomField (object)
+ definition (object)
    + type: `customFieldDefinition` (string)
    + id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)
+ One Of
    + value: `092980616` (string)
    + value: `123` (number) - For integer, number and auto-increment fields
    + value: `foo`,`bar` (array[string]) - For multiple selection fields
    + value: true (boolean) - For Yes/No fields
    + value (object) - For related Teamleader objects
        + type: `company` (enum)
            + Members
                + company
                + contact
                + product
                + user
        + id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)

## CustomFieldValue (object)
+ id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)
+ One Of
    + value: `092980616` (string)
    + value: `123` (number) - For integer, number, money and auto-increment fields
    + value: `foo`,`bar` (array[string]) - For multiple selection fields
    + value: true (boolean) - For Yes/No fields
    + value (object) - For related Teamleader objects
        + type: `company` (enum)
            + Members
                + company
                + contact
                + product
                + user
        + id: `bf6765de-56eb-40ec-ad14-9096c5dc5fe1` (string)

## WebHook (object)
+ url: `https://example.com` (string, required) - Your webhook URL
+ types (array[enum], required) - Array of event types that fire the webhook
    + Members
        + account.deactivated
        + account.deleted
        + company.added
        + company.deleted
        + company.updated
        + contact.added
        + contact.deleted
        + contact.linkedToCompany
        + contact.unlinkedFromCompany
        + contact.updated
        + creditNote.booked
        + creditNote.deleted
        + creditNote.sent
        + creditNote.updated
        + deal.created
        + deal.deleted
        + deal.lost
        + deal.moved
        + deal.updated
        + deal.won
        + invoice.booked
        + invoice.deleted
        + invoice.drafted
        + invoice.paymentRegistered
        + invoice.paymentRemoved
        + invoice.sent
        + invoice.updated
        + milestone.created
        + milestone.updated
        + product.added
        + project.created
        + project.deleted
        + project.updated
        + subscription.added
        + subscription.deactivated
        + subscription.deleted
        + subscription.updated
        + timeTracking.added
        + timeTracking.deleted
        + timeTracking.updated
        + user.deactivated

## ExpectedPaymentMethod (object)
+ One Of
    + Properties
        + method: `sepa_direct_debit` (enum[string], required)
            + Members
                + `sepa_direct_debit`
                + `direct_debit`
                + `credit_card`
        + reference: `AB1234` (string, optional, nullable)
    + Properties
        + method: `cash` (enum[string], required)
            + Members
                + `cash`
                + `cheque`
                + `bankers_draft`
                + `bank_transfer`
                + `payment_card`

## Duration (object)
+ unit: `s` (enum[string], required)
    + Members
        + `s` - Seconds
+ value: `10800` (number, required)

## User (object)
+ type: `user` (string)
+ id: `bef8c53b-b6bc-0fde-944e-5c4b16e5155a` (string)

## Customer (object)
+ type: `contact` (enum)
    + Members
        + contact
        + company
+ id: `f29abf48-337d-44b4-aad4-585f5277a456` (string)

## CommercialDiscount (object)
+ type: `percentage` (enum)
    + Members
        + percentage - Values between 0 and 100
+ value: 15.5 (number)
+ description: `winter promotion` (string)

## MimeType (enum)
+ `application/msword`
+ `application/octet-stream`
+ `application/pdf`
+ `application/vnd.ms-excel`
+ `application/vnd.ms-powerpoint`
+ `application/vnd.openxmlformats-officedocument.presentationml.presentation`
+ `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
+ `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
+ `application/xml`
+ `application/zip`
+ `audio/mpeg`
+ `audio/wav`
+ `image/gif`
+ `image/jpeg`
+ `image/png`
+ `text/css`
+ `text/csv`
+ `text/html`
+ `text/javascript`
+ `text/plain`
+ `video/3gpp`
+ `video/mpeg`
+ `video/quicktime`
+ `video/x-msvideo`

## Priority (enum)
+ `A`
+ `B`
+ `C`
+ `D`

## Language (enum)
+ en
+ nl
+ fr
+ ch
+ jp
+ de
+ es
+ pt
+ it
+ gr
+ tr
+ cs
+ so
+ sk
+ ru
+ ko
+ ir
+ iq
+ hu
+ gh
+ bg
+ bs
+ br
+ ar
+ ag
+ al
+ af
+ ro
+ pl
+ ca
+ da
+ uk
+ no
+ fi
+ sv

## InvoiceGeneration (object)
+ One Of
    + Properties
        + action: `draft` (string, required)
    + Properties
        + action: `book` (string, required)
    + Properties
        + action: `book_and_send` (string, required)
        + sending_methods (array, required) - the `email` method is required.
            + (object)
                + method: `email` (enum, required)
                    + Members
                        + email
                        + postal_service

## LineItem (object)
+ quantity: `3` (number, required)
+ description: `An awesome product` (string, required)
+ extended_description: `Some more information about this awesome product` (string, optional, nullable) - Uses Markdown formatting
+ unit_of_measure_id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string, optional, nullable)
+ unit_price (object, required)
    + amount: `123.30` (number, required)
    + tax: `excluding` (enum, required)
        + Members
            + excluding
+ tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)
+ withholding_tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585824` (string, optional)
+ discount (object, optional)
    + value: 10 (number, required)
    + type (enum, required)
        + Members
            + percentage - Values between 0 and 100
+ product_category_id: `e2314517-3cab-4aa9-8471-450e73449041` (string, optional)
+ product_id: `d905ff57-e866-0f59-9d1e-1fd4538bfae1` (string, optional)

## Periodicity (object)
+ One Of
    + Properties
        + unit: `week` (string, required)
        + period: `2` (enum, required)
            + Members
                + 1
                + 2
                + 4
   + Properties
       + unit: `month` (string, required)
       + period: `4` (enum, required)
           + Members
               + 1
               + 2
               + 3
               + 4
               + 6
   + Properties
       + unit: `year` (string, required)
       + period: `7` (enum, required)
           + Members
               + 1
               + 2
               + 3
               + 4
               + 5
               + 6
               + 7
               + 8
               + 9
               + 10

## GroupedLineItem (object)
+ section (object)
    + title (string, nullable)
+ line_items (array)
    + (object)
        + product (object, nullable)
            + type: `product` (string)
            + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
        + product_category (object, nullable)
            + type: `productCategory` (string)
            + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)
        + quantity: 3 (number)
        + description: `An awesome product` (string)
        + extended_description: `Some more information about this awesome product` (string, nullable) - Uses Markdown formatting
        + unit (object, nullable)
            + type: `unitOfMeasure` (string)
            + id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string)
        + unit_price (object)
            + amount: `123.30` (number)
            + tax: `excluding` (enum)
                + Members
                    + excluding
        + tax (object)
            + type: `taxRate` (string)
            + id: `e2314517-3cab-4aa9-8471-450e73449042` (string)
        + discount (object, nullable)
            + type: `percentage` (enum)
                + Members
                    + percentage
            + value: 15.00 (number)
        + total
            + tax_exclusive (Money)
            + tax_exclusive_before_discount (Money)
            + tax_inclusive (Money)
            + tax_inclusive_before_discount (Money)
        + withheld_tax (object, nullable)
            + type: `withholding_tax` (string)
            + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)

## PriceListRead (object)
+ `id`: `d905ff57-e866-0f59-9d1e-1fd4538bfae1` (string)
+ `type`: `priceList` (string)

## ProductPriceRead (object)
+ `amount`: 100 (number)
+ `currency`: `EUR` (string)

## PriceListPriceRead (object)
+ `price_list` (PriceListRead)
+ `price` (ProductPriceRead)

## PriceListPricesRead (array)
+ (array)
    + (PriceListPriceRead)

## ProductPriceWrite (object)
+ `amount`: 100 (number, required)
+ `currency`: `EUR` (string, required)

## PriceListPriceWrite (object)
+ `price_list_id`: `d905ff57-e866-0f59-9d1e-1fd4538bfae1` (string, required)
+ `price` (ProductPriceWrite, required)

## PriceListPricesWrite (array)
+ (array)
    + (PriceListPriceWrite, required)

## ProductConfigurationWrite (object)
+ `stock_threshold` (object, nullable) - Only available when stock management feature is enabled
    + `minimum`: 4 (number, required) - Cannot be negative
    + `action`: `notify` (enum, required)
        + Members
            + `notify`

## ProductConfigurationRead (object)
+ `stock_threshold` (object, nullable) - Only available when stock management feature is enabled
    + `minimum`: 4 (number)
    + `action`: `notify` (enum)
        + Members
            + `notify`

## InvoiceGroupedLinesWrite (object)
+ section (object, optional)
    + title (string, required)
+ line_items (array, required)
    + (object)
        + quantity: `3` (number, required)
        + description: `An awesome product` (string, required)
        + extended_description: `Some more information about this awesome product` (string, optional, nullable) - Uses Markdown formatting
        + unit_of_measure_id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string, optional, nullable)
        + unit_price (object)
            + amount: `123.30` (number, required)
            + tax: `excluding` (enum)
                + Members
                    + excluding
        + tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585823` (string, required)
        + withholding_tax_rate_id: `c0c03f1e-77e3-402c-a713-30ea1c585824` (string, optional)
        + discount (object, optional)
            + value: 10 (number, required)
            + type (enum, required)
                + Members
                    + percentage - Values between 0 and 100
        + product_category_id: `e2314517-3cab-4aa9-8471-450e73449041` (string, optional)
        + product_id: `d905ff57-e866-0f59-9d1e-1fd4538bfae1` (string, optional)
