## API Evolution

| **Milestone**                                                                 | **ETA**           |
| ----------------------------------------------------------------------------- | ----------------- |
| Ability to change the currency for invoice                                    | October 1, 2023   |
| Ability to change the currency for quotation                                  | October 1, 2023   |
| Allow updating booked invoices                                                | October 1, 2023   |
| Webhooks for meetings and calls                                               | November 15, 2023 |
| Meeting endpoints                                                             | November 15, 2023 |
| Call endpoints                                                                | November 15, 2023 |
| Ability to manage Custom Fields on meetings and Calls                         | November 15, 2023 |
| Notes endpoints                                                               | December 15, 2023 |
| Ability to get days off                                                       | January 15, 2024  |
| Tickets endpoints                                                             | February 1, 2024  |


For customers that are still using legacy API v1 version which was deprecated in 2019, keep in mind that we will make all of the endpoints unavailable in 2024:
 - Read-only mode: May 1, 2024
 - Final sunsetting of API v1: August 1, 2024

[Contact Support](https://support.focus.teamleader.eu/en/support/tickets/new)
