## API Evolution

| **Milestone**                                                                 | **ETA**           |
| ----------------------------------------------------------------------------- | ----------------- |
| Notes endpoints                                                               | December 15, 2023 |
| Ability to get days off                                                       | January 15, 2024  |
| Tickets endpoints                                                             | February 1, 2024  |
| Task webhooks                                                                 | February 15, 2024 |


For customers that are still using legacy API v1 version which was deprecated in 2019, keep in mind that we will make all of the endpoints unavailable in 2024:
 - Active deprecation mode: June 1, 2024
 - Final sunsetting of API v1: August 1, 2024
> **Note:**
>
> + API uses UUIDs for all resources. If you need help to convert API v1 integer ids to UUIDs, please check this [guide](https://support.focus.teamleader.eu/hc/en-150/articles/26981214932625-Migrating-from-legacy-API-v1-Transitioning-from-Integer-IDs-to-UUIDs).

[Contact Support](https://support.focus.teamleader.eu/support/tickets/new)
