## API Evolution

| **Milestone**                                                                 | **ETA**           |
| ----------------------------------------------------------------------------- | ----------------- |
| Notes endpoints                                                               | December 15, 2023 |
| Ability to get days off                                                       | January 15, 2024  |
| Tickets endpoints                                                             | February 1, 2024  |
| Task webhooks                                                                 | February 15, 2024 |


For customers that are still using legacy API v1 version which was deprecated in 2019, keep in mind that we will make all of the endpoints unavailable in 2024:
 - Active deprecation mode: June 1, 2024
 - Final sunsetting of API v1: August 1, 2024

[Contact Support](https://support.focus.teamleader.eu/support/tickets/new)
