> _This is the documentation of the new projects module. See the **Legacy Projects** documentation for the endpoints concerning our legacy projects module._

> To avoid naming collisions, all endpoints of the new projects module can be found under `/nextgen`, for example `/nextgen/projects.list`.
> To avoid confusing "new projects" with "creating a new project", we opted for "nextgen" over "new" as the prefix.

## Projects [/nextgen/projects]
