## Invoices [/invoices]

Teamleader provides a whole set of endpoints to make it easy to develop integrations with invoices. New invoices are created in accordance with this flow: `invoice.draft` → `invoice.book`. Invoices can also be updated, deleted or credited.

*Required scopes: `invoices`*

### invoices.list [POST /invoices.list]

Get a list of invoices.

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + `ids`: `cb8da52a-ce89-4bf6-8f7e-8ee6cb85e3b5`,`f8a57a6f-dd1e-41a3-b8d3-428663f1d09e` (array[string], optional)
            + `term`: `Interesting invoice` (string, optional) - Filters on invoice number, purchase order number, payment reference and invoicee
            + `invoice_number`: `2017 / 5` (string, optional) - Filters on a full invoice number (fiscal year / number)
            + `department_id`: `af48fe9e-d44c-0eac-8813-8be051b10921` (string, optional) - Filters on a department (company entity)
            + `deal_id`: `4a219dae-7b80-4c79-97d2-bdadbab299ba` (string, optional) - Filters on a deal
            + `project_id`: `ba7d9731-c7d0-43d3-af95-fd7b3e818dbc` (string, optional) - Filters on a project
            + `status` (array[enum], optional) - The statuses you want to filter by.
                + Members
                    + draft
                    + outstanding
                    + matched
            + `updated_since`: `2016-02-04T16:44:33+00:00` (string, optional)
            + `purchase_order_number`: `000023` (string, optional)
            + `payment_reference`: `+++084/2613/66074+++` (string, optional)
            + `invoice_date_after`: `2020-01-01` (string, optional) - This date is inclusive
            + `invoice_date_before`: `2022-01-01` (string, optional) - This date is exclusive
            + `customer` (object, optional)
                + type (enum, required)
                    + Members
                        + company
                        + contact
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + invoice_number
                        + invoice_date
                + order (enum, optional)
                    + Members
                        + asc
                        + desc
            + Default
                + (object)
                    + field: `invoice_number`
                    + order: `asc`
        + includes: `late_fees` (string, optional) - when used, the response will include `totals.due_incasso_inclusive`, `totals.fixed_late_fee` and `totals.interest`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `2aa4a6a9-9ce8-4851-a9b3-26aea2ea14c4` (string)
                + department (object)
                    + type: `department` (string)
                    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
                + invoice_number: `2017 / 5` (string, nullable)
                + invoice_date: `2016-02-04` (string, nullable)
                + status: `matched` (enum)
                    + Members
                        + draft
                        + outstanding
                        + matched
                + due_on: `2016-03-03` (string, nullable)
                + paid: true (boolean)
                + paid_at: `2016-02-04T16:44:33+00:00` (string, nullable)
                + sent: true (boolean)
                + purchase_order_number: `000023` (string, nullable)
                + payment_reference: `+++084/2613/66074+++` (string, nullable)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + vat_number: `BE0899623035` (string, nullable)
                    + customer (object)
                        + type: `contact` (string)
                        + id: `4b0f959a-27e3-4080-b1b2-a05b374863cb` (string)
                    + for_attention_of (object, nullable)
                        + name: `Radja Nainggolan` (string, nullable)
                        + contact (object, nullable)
                            + type: `contact` (string)
                            + id: `d4391f46-a32c-458c-b2ee-833fd27a348d` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: 0.21 (number)
                            + taxable (Money)
                            + tax (Money)
                    + due (Money)
                    + due_incasso_inclusive (Money) - Only included with request parameter `includes=late_fees`
                    + fixed_late_fee (Money) - Only included with request parameter `includes=late_fees`
                    + interest (Money) - Only included with request parameter `includes=late_fees`
                + currency_exchange_rate (object)
                    + from: `USD` (string)
                    + to: `EUR` (string)
                    + rate: 1.1234 (number)
                + created_at: `2016-02-04T16:44:33+00:00` (string)
                + updated_at: `2016-02-05T16:44:33+00:00` (string)
                + `web_url`: `https://focus.teamleader.eu/invoice_detail.php?id=2aa4a6a9-9ce8-4851-a9b3-26aea2ea14c4` (string)
                + file (object, nullable)
                    + type: `file` (string)
                    + id: `39a02b79-b9a9-46e3-a44d-6c473b2fe350` (string)
                + deal (object, nullable)
                    + type: `deal` (string)
                    + id: `a8ef428a-0e70-48a5-8696-58be0c45a772` (string)
                + project (object, nullable)
                    + type: `project` (string)
                    + id: `179e1564-493b-4305-8c54-a34fc80920fc` (string)

### invoices.info [POST /invoices.info]

Get details for a single invoice.

+ Request (application/json)

    + Attributes (object)
        + id: `27300f09-6250-4a23-8557-d84c52f99ecf` (string)
        + includes: `late_fees` (string, optional) - when used, the response will include `totals.due_incasso_inclusive`, `totals.fixed_late_fee` and `totals.interest`


+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + id: `e540fe7e-dce2-459e-bf7e-24e605fc18b3` (string)
            + department (object)
                + type: `department` (string)
                + id: `8f802cba-443b-4c69-800f-5852e967000b` (string)
            + invoice_number: `2017 / 5` (string, nullable)
            + invoice_date: `2016-02-04` (string, nullable)
            + status: `outstanding` (enum)
                + Members
                    + draft
                    + outstanding
                    + matched
            + due_on: `2016-03-03` (string, nullable)
            + paid: true (boolean)
            + paid_at: `2016-02-04T16:44:33+00:00` (string, nullable)
            + sent: true (boolean)
            + purchase_order_number: `000023` (string, nullable)
            + invoicee (object)
                + name: `De Rode Duivels` (string)
                + vat_number: `BE0899623035` (string, nullable)
                + customer (object)
                    + type: `contact` (string)
                    + id: `c7db7f80-762a-4e65-8d0c-522700198284` (string)
                + for_attention_of (object, nullable)
                    + name: `Radja Nainggolan` (string, nullable)
                    + contact (object, nullable)
                        + type: `contact` (string)
                        + id: `f88ab83c-b8ca-497b-a2c6-1ad631fe1cea` (string)
                + email: `duivels@test.com` (string, nullable)
                + national_identification_number: `123` (string, nullable)
            + discounts (array[CommercialDiscount])
            + grouped_lines (array)
                + (object)
                    + section (object)
                        + title (string)
                    + line_items (array)
                        + (object)
                            + product (object, nullable)
                                + type: `product` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                            + product_category (object, nullable)
                                + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)
                                + type: `productCategory` (string)
                            + quantity: 3 (number)
                            + description: `An awesome product` (string)
                            + extended_description: `Some more information about this awesome product` (string, nullable) - Uses Markdown formatting
                            + unit (object, nullable)
                                + type: `unitOfMeasure` (string)
                                + id: `f79d3e04-b8dc-0637-8f18-ca7c8fc63b71` (string)
                            + unit_price (object)
                                + amount: `123.30` (number)
                                + tax: `excluding` (enum)
                                    + Members
                                        + excluding
                            + tax (object)
                                + type: `taxRate` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449042` (string)
                            + discount (object, nullable)
                                + type: `percentage` (enum)
                                    + Members
                                        + percentage
                                + value: 15.00 (number)
                            + total
                                + tax_exclusive (Money)
                                + tax_exclusive_before_discount (Money)
                                + tax_inclusive (Money)
                                + tax_inclusive_before_discount (Money)
                            + withheld_tax (object, nullable)
                                + type: `withholding_tax` (string)
                                + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
            + total (object)
                + tax_exclusive (Money)
                + tax_exclusive_before_discount (Money)
                + tax_inclusive (Money)
                + tax_inclusive_before_discount (Money)
                + taxes (array)
                    + (object)
                        + rate: 0.21 (number)
                        + taxable (Money)
                        + tax (Money)
                + withheld_taxes (array)
                    + (object)
                        + id: `e2314517-3cab-4aa9-8471-450e73449040` (string)
                        + taxable (Money)
                        + withheld (Money)
                + payable (Money)
                + due (Money)
                + due_incasso_inclusive (Money) - Only included with request parameter `includes=late_fees`
                + fixed_late_fee (Money) - Only included with request parameter `includes=late_fees`
                + interest (Money) - Only included with request parameter `includes=late_fees`
            + payment_term (PaymentTerm)
            + payments (array)
                + (object)
                    + paid_at: `2016-03-03T16:44:33+00:00` (string)
                    + payment (object)
                        + Include Money
            + payment_reference: `+++084/2613/66074+++` (string, nullable)
            + note: `'Some extra remarks about the invoice'` (string, nullable) - plaintext
            + currency: `USD` (string)
            + currency_exchange_rate (object)
                + from: `USD` (string)
                + to: `EUR` (string)
                + rate: 1.1234 (number)
            + expected_payment_method (ExpectedPaymentMethod, nullable)
            + file (object, nullable)
                + type: `file` (string)
                + id: `39a02b79-b9a9-46e3-a44d-6c473b2fe350` (string)
            + deal (object, nullable)
                + type: `deal` (string)
                + id: `a8ef428a-0e70-48a5-8696-58be0c45a772` (string)
            + project (object, nullable)
                + type: `project` (string)
                + id: `179e1564-493b-4305-8c54-a34fc80920fc` (string)
            + on_hold_since: `2016-02-01` (string, nullable)
            + custom_fields (array[CustomField])
            + created_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)
            + document_template (object)
                + type: `documentTemplate` (string)
                + id: `179e1564-493b-4305-8c54-a34fc80920fc` (string)

### invoices.download [POST /invoices.download]

Download an invoice in a specific format.

+ Request (application/json)

    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)
        + format: `pdf` (enum, required)
            + Members
                + pdf
                + `ubl/e-fff`

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + location: `https://cdn.teamleader.eu/file` (string) - A temporary url where the requested file can be downloaded
            + expires: `2018-02-05T16:44:33+00:00` (string) - Expiration time of the temporary download link

### invoices.draft [POST /invoices.draft]

Draft a new invoice.

+ Request (application/json)

    + Attributes (object)
        + invoicee (object, required)
            + customer (object, required)
                + type (enum)
                    + Members
                        + contact
                        + company
                + id: `ebafa4c5-fa8a-4409-92e5-1b192243372f` (string)
            + for_attention_of (object, optional)
                + One Of
                    + name: `Finance Dept.` (string, required)
                    + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + department_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac7` (string, required)
        + payment_term (PaymentTerm, required)
        + currency (object)
            + code: `EUR` (Currency, required)
            + exchange_rate: `1.1238` (number)
        + project_id: `624ca743-8998-4f8c-add1-c427bb022166` (string, optional)
        + purchase_order_number: `000023` (string, optional)
        + grouped_lines (array[InvoiceGroupedLinesWrite], required)
        + invoice_date: `2016-02-04` (string, optional)
        + discounts (array[CommercialDiscount], optional)
        + note: `Invoice comments` (string, optional)
        + expected_payment_method (ExpectedPaymentMethod, optional).
        + custom_fields (array[CustomFieldValue], optional)
        + document_template_id: `179e1564-493b-4305-8c54-a34fc80920fc` (string, optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `invoice` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### invoices.update [POST /invoices.update]

Update a draft invoice. Booked invoices cannot be updated.

+ Request (application/json)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)
        + invoicee (object, optional)
            + customer (object, required)
                + type (enum)
                    + Members
                        + contact
                        + company
                + id: `ebafa4c5-fa8a-4409-92e5-1b192243372f` (string)
            + for_attention_of (object, optional)
                + One Of
                    + name `Finance Dept.` (string, required)
                    + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + payment_term (PaymentTerm, optional)
        + currency (object)
            + code: `EUR` (Currency, required)
            + exchange_rate: `1.1238` (number)
        + project_id: `624ca743-8998-4f8c-add1-c427bb022166` (string, optional)
        + purchase_order_number: `000023` (string, optional)
        + grouped_lines (array[InvoiceGroupedLinesWrite], optional)
        + invoice_date: `2016-02-04` (string, optional)
        + note: `Some comments about the invoice` (string, optional, nullable)
        + discounts (array[CommercialDiscount], optional)
        + expected_payment_method (ExpectedPaymentMethod, optional, nullable)
        + custom_fields (array[CustomFieldValue], optional)
        + document_template_id: `179e1564-493b-4305-8c54-a34fc80920fc` (string, optional)

+ Response 204

### invoices.updateBooked [POST /invoices.updateBooked]

Update a booked invoice. Only available when editing booked invoices is allowed through the settings.

+ Request (application/json)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)
        + invoicee (object, optional)
            + customer (object, required)
                + type (enum)
                    + Members
                        + contact
                        + company
                + id: `ebafa4c5-fa8a-4409-92e5-1b192243372f` (string)
            + for_attention_of (object, optional)
                + One Of
                    + name `Finance Dept.` (string, required)
                    + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + payment_term (PaymentTerm, optional)
        + project_id: `624ca743-8998-4f8c-add1-c427bb022166` (string, optional)
        + grouped_lines (array[InvoiceGroupedLinesWrite], optional)
        + invoice_date: `2016-02-04` (string, optional)
        + note: `Some comments about the invoice` (string, optional, nullable)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 204

### invoices.copy [POST /invoices.copy]

Creates a new draft invoice based on another invoice

+ Request (application/json)

    + Attributes (object)
        + id: `b7023c11-455e-4fa5-bb96-87f37dbc7d07` (string, required)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `invoice` (string)
            + id: `e4bf74ca-e900-471f-84b1-276e5d3afae4` (string)

### invoices.book [POST /invoices.book]

Book a draft invoice.

+ Request (application/json)

    + Attributes (object)
        + id: `7abb325c-e063-42a4-8fb4-1b730759645a` (string, required)
        + on: `2016-02-04` (string, required)

+ Response 204

### invoices.delete [POST /invoices.delete]

Delete an existing invoice. Only possible for draft invoices or the last booked invoice.

+ Request (application/json)

    + Attributes (object)
        + id: `7517d21c-75c1-4b89-8956-0e67f46c8532` (string, required)

+ Response 204

### invoices.registerPayment [POST /invoices.registerPayment]

Register a payment for an invoice.

+ Request (application/json)

    + Attributes (object)
        + id: `7abb325c-e063-42a4-8fb4-1b730759645a` (string, required)
        + payment (object, required)
            + Include Money
        + paid_at: `2016-03-03T16:44:33+00:00` (string, required)
        + payment_method_id: `bb9589ec-6e08-0d5f-9b23-7be9b9c3ea2d` (string, optional)

+ Response 204

### invoices.removePayments [POST /invoices.removePayments]

Marks an invoice as unpaid and removes all linked payments. This will also trigger a re-rendering of the invoice PDF.

+ Request (application/json)
    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)

+ Response 204

### invoices.credit [POST /invoices.credit]

Credit an invoice completely.

+ Request (application/json)

    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)
        + credit_note_date: `2016-02-04` (string, optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `creditNote` (string)
            + id: `d885e5d5-bacb-4607-bde9-abc4a04a901c` (string)


### invoices.creditPartially [POST /invoices.creditPartially]

Credit an invoice partially.

+ Request (application/json)

    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)
        + credit_note_date: `2016-02-04` (string, optional)
        + grouped_lines (array[InvoiceGroupedLinesWrite], required)
        + discounts (array[CommercialDiscount], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `creditNote` (string)
            + id: `d885e5d5-bacb-4607-bde9-abc4a04a901c` (string)


### invoices.send [POST /invoices.send]

Send an invoice via e-mail.

+ Request (application/json)

    + Attributes (object)
        + id: `d885e5d5-bacb-4607-bde9-abc4a04a901b` (string, required)
        + content (object, required)
             + subject: `Invoice` (string, required)
             + body: `Please find your invoice attached to this mail` (string, required)
             + mail_template_id: `045cd6a9-7527-09c9-aa16-fd5ac7953e71` (string, optional, nullable)
        + recipients (object, optional)
            + to (array)
                + (object)
                    + customer (object, optional, nullable)
                        + type (enum, required)
                            + Members
                                + company
                                + contact
                        + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
                    + email: `info@teamleader.eu` (string, required)
            + cc (array, optional)
                + (object)
                    + customer (object, optional, nullable)
                        + type (enum, required)
                            + Members
                                + company
                                + contact
                        + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
                    + email: `info@teamleader.eu` (string, required)
           + bcc (array, optional)
                + (object)
                   + customer (object, optional, nullable)
                       + type (enum, required)
                           + Members
                               + company
                               + contact
                       + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string, required)
                   + email: `info@teamleader.eu` (string, required)
       + attachments: `e76d381a-f7ea-04d1-9a32-14aab27bc1e2` (array[string], optional) - an array of file ids

+ Response 204
