## Payment Terms [/paymentTerms]

Payment terms are the conditions under which an invoice need to be paid.

### paymentTerms.list [POST /paymentTerms.list]

Get a list of available payment terms.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `c93ddb52-0af8-47d9-8551-441435be66a7` (string)
                + Include PaymentTerm
