### paymentTerms.list [GET /paymentTerms.list]

Get a list of available payment terms.

+ Request (application/json;charset=utf-8)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `c93ddb52-0af8-47d9-8551-441435be66a7` (string)
                + Include PaymentTerm
