## Subscriptions [/subscriptions]

### subscriptions.list [GET /subscriptions.list]

Get a list of subscriptions

+ Request (application/json)
    + Attributes (object)
        + filter (object, optional)
            + ids: `46156648-87c6-478d-8aa7-1dc3a00dacab`, `46156648-87c6-478d-8aa7-1dc3a00daca4` (array[string], optional)
            + invoice_id: `60f03745-4289-4ae7-8c74-d797860bc887` (string, optional) - Find subscriptions that generated the given invoice
            + deal_id: `fddf42f9-bda1-0c49-a22b-0bf147cd1e3f` (string, optional) - Filter on subscriptions created from a deal
            + department_id: `af48fe9e-d44c-0eac-8813-8be051b10921` (string, optional) - Filter on subscriptions of a specific department (company entity)
            + customer (Customer)
            + status (array[enum], optional) - Filters on status
                + Members
                    + active - Filters on active subscriptions
                    + deactivated - Filters on deactivated subscriptions
        + page (Page, optional)
        + sort (array, optional)
            + (object)
                + field (enum, required)
                    + Members
                        + title
                        + created_at
                        + status
                + order (enum, optional)
                    + Members
                        + asc
                        + desc

+ Response 200 (application/json)
    + Attributes (object)
        + data (array)
            + (object)
                + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)
                + title: `Subscription for cookies` (string)
                + remarks: `Some more **information** about this subscription` (string, nullable) - Uses Markdown formatting
                + status: `active` (enum[string])
                    + Members
                        + active
                        + deactivated
                + department (object)
                    + type: `department` (string)
                    + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
                + invoicee (object)
                    + customer (Customer)
                    + for_attention_of (object, nullable)
                        + contact (object, nullable)
                            + type: `contact` (string)
                            + id: `d4391f46-a32c-458c-b2ee-833fd27a348d` (string)
                        + name: `Radja Nainggolan` (string, nullable)
                + project (object, nullable)
                    + type: `project` (string)
                    + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
                + next_renewal_date: `2022-06-21` (string, nullable)
                + periodicity: `monthly` (enum)
                    + Members
                        + weekly
                        + two_weekly
                        + four_weekly
                        + monthly
                        + two_monthly
                        + quarterly
                        + four_monthly
                        + six_monthly
                        + yearly
                        + two_yearly
                        + three_yearly
                        + four_yearly
                        + five_yearly
                        + six_yearly
                        + seven_yearly
                        + eight_yearly
                        + nine_yearly
                        + ten_yearly
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + taxes (array)
                        + (object)
                            + rate: 0.21 (number)
                            + taxable (Money)
                            + tax (Money)
                + `web_url`: `https://focus.teamleader.eu/subscription_detail.php?id=e2314517-3cab-4aa9-8471-450e73449041` (string)

### subscriptions.info [GET /subscriptions.info]

Get details for a single subscription

+ Request (application/json)
    + Attributes (object)
        + id: `e2314517-3cab-4aa9-8471-450e73449041` (string, required)

+ Response 200 (application/json)
    + Attributes (object)
        + data (object)
            + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)
            + title: `Subscription for cookies` (string)
            + note: `Some more **information** about this subscription` (string, nullable) - Uses Markdown formatting
            + status: `active` (enum[string])
                + Members
                    + active
                    + deactivated
            + department (object)
                + type: `department` (string)
                + id: `5e90eb0a-b502-4344-aa0f-3b8525af6186` (string)
            + invoicee (object)
                + customer (Customer)
                + for_attention_of (object, nullable)
                    + contact (object, nullable)
                        + type: `contact` (string)
                        + id: `d4391f46-a32c-458c-b2ee-833fd27a348d` (string)
                    + name: `Radja Nainggolan` (string, nullable)
            + project (object, nullable)
                + type: `project` (string)
                + id: `2659dc4d-444b-4ced-b51c-b87591f604d7` (string)
            + next_renewal_date: `2022-06-21` (string, nullable)
            + total (object)
                + tax_exclusive (Money)
                + tax_inclusive (Money)
                + taxes (array)
                    + (object)
                        + rate: 0.21 (number)
                        + taxable (Money)
                        + tax (Money)
            + `web_url`: `https://focus.teamleader.eu/subscription_detail.php?id=e2314517-3cab-4aa9-8471-450e73449041` (string)
            + starts_on: `2022-05-21` (string)
            + ends_on: `2023-07-21` (string, nullable)
            + billing_cycle (object) - Only available for api-version 9999-99-99
                + periodicity (Periodicity)
                + days_in_advance: `7` (enum[number])
                    + Members
                        + 0
                        + 7
                        + 14
                        + 21
                        + 28
            + payment_term (PaymentTerm)
            + grouped_lines (array)
                + (GroupedLineItem)
            + invoice_generation (object)
                + action: `book` (enum)
                    + Members
                        + draft
                        + book
                        + book_and_send
                + sending_methods (array, optional) - only provided when action is "book and send".
                    + (object)
                        + method: `email` (enum)
                            + Members
                                + email
                                + postal_service
            + custom_fields (array[CustomField])

### subscriptions.create [POST /subscriptions.create]

Create a new subscription.

+ Request (application/json)

    + Attributes (object)
        + invoicee (object, required)
            + customer (Customer, required)
            + for_attention_of (object, optional)
                + One Of
                    + name: `Finance Dept.` (string, required)
                    + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + department_id: `6a6343fc-fdd8-4bc0-aa69-3a004c710e87` (string, required)
        + starts_on: `2022-04-26` (string, required)
        + billing_cycle (object, required)
            + periodicity (Periodicity, required)
            + days_in_advance: `7` (enum[number], required)
                + Members
                    + 0
                    + 7
                    + 14
                    + 21
                    + 28
        + title: `Subscription for cookies` (string, required)
        + grouped_lines (array, required)
            + (object)
                + section (object)
                    + title (string)
                + line_items (array, required)
                    + (LineItem)
        + ends_on: `2022-05-26` (string, nullable, optional)
        + deal_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac8` (string, optional)
        + project_id: `ebafa4c5-fa8a-4409-92e5-1b192243372f` (string, optional)
        + note: `Subscription comments` (string, optional)
        + payment_term (PaymentTerm, required)
        + invoice_generation (InvoiceGeneration, required)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + type: `subscription` (string)
            + id: `e2314517-3cab-4aa9-8471-450e73449041` (string)

### subscriptions.update [POST /subscriptions.update]

Update a subscription.

+ Request (application/json)

    + Attributes (object)
        + id: `5b16f6ee-e302-0079-901b-50c26c4a55b1` (string, required)
        + starts_on: `2022-04-26` (string, optional) - can only be provided if no invoices have been created yet.
        + billing_cycle (object, optional) - can only be provided if no invoices have been created yet.
            + periodicity (Periodicity, required)
            + days_in_advance: `7` (enum[number], required)
                + Members
                    + 0
                    + 7
                    + 14
                    + 21
                    + 28
        + ends_on: `2022-05-26` (string, nullable, optional)
        + title: `Subscription for cookies` (string, optional)
        + invoicee (object, optional)
            + customer (Customer, required)
            + for_attention_of (object, optional)
                + One Of
                    + name: `Finance Dept.` (string, required)
                    + contact_id: `417a2231-c3c7-4e1c-a6bb-1b014836ca60` (string, required)
        + department_id: `6a6343fc-fdd8-4bc0-aa69-3a004c710e87` (string, optional)
        + payment_term (PaymentTerm, optional)
        + project_id: `cef01135-7e51-4f6f-a6eb-6e5e5a885ac8` (string, optional)
        + deal_id: `f6871b06-6513-4750-b5e6-ff3503b5a029` (string, optional)
        + note: `Subscription comments` (string, nullable, optional)
        + grouped_lines (array, optional)
            + (object)
                + section (object)
                    + title (string)
                + line_items (array, required)
                    + (LineItem)
        + invoice_generation (InvoiceGeneration, optional)
        + custom_fields (array[CustomFieldValue], optional)

+ Response 204

### subscriptions.deactivate [POST /subscriptions.deactivate]

+ Request (application/json)
    + Attributes (object)
        + id: `46156648-87c6-478d-8aa7-1dc3a00dacab` (string, required)

+ Response 204
