## Tax Rates [/taxRates]

Tax rates provide an overview of different taxation rates used to bill customers. Teamleader provides a default list of tax rates based on the country of residence of the company that’s using Teamleader. The end user also has the option to add additional tax rates.

### taxRates.list [GET /taxRates.list]

Get a list of available tax rates.

+ Request (application/json;charset=utf-8)

+ Attributes (object)
    + filter (object, optional)
        + department_id: `080aac72-ff1a-4627-bfe3-146b6eee979c` (string, optional) - The ID of the department you wish to filter on.
    + page (Page, optional)
    + sort (array, optional)
        + Default
            + (array)
                + (object)
                    + field: `department_id`
                    + order: `asc`
                + (object)
                    + field: `rate`
                    + order: `asc`
                + (object)
                    + field: `description`
                    + order: `asc`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `c93ddb52-0af8-47d9-8551-441435be66a7` (string)
                + description: `21%` (string)
                + rate: 0.21 (number)
                + department (object)
                    + type: `department` (string)
                    + id: `182af0a8-3f68-409b-8941-cf8caf8f28a0` (string)
