name: Pull Request

on:
  pull_request:

defaults:
  run:
    shell: 'script -q -e -c "export TERM=xterm-256color; bash {0}"'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '9'
      - name: lint
        run: |
          npm install && npm run build && npm run lint