---
name: Pull Request

on:
  pull_request:

defaults:
  run:
    shell: 'script -q -e -c "export TERM=xterm-256color; bash {0}"'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
        run: |
          npm install && npm run build && npm run lint
