---
name: Pull Request

on:
  pull_request:

defaults:
  run:
    shell: 'script -q -e -c "export TERM=xterm-256color; bash {0}"'

jobs:
  lint:
    container:
      image: node:16
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Lint
        run: |
          npm install && npm run build && npm run lint
